### PR TITLE
fix(l10n): Ensure tooltips are translated in local dev

### LINKED ISSUE #6871: tooltips not translated in local development
Tooltips are fine on prod, but not local development:

### local
screenshot 2019-01-11 at 15 32 32

### prod
screenshot 2019-01-11 at 15 32 54

### PR DESCRIPTION
**Pull request by shane-tomlinson**
The translator instance was not passed to the Tooltip. This
affects dev because only the instance created in app-start
fetches translations. The problem does not affect prod
because translations are built into the Translator object.

fixes #6871

@mozilla/fxa-devs - r?

screenshot 2019-01-11 at 20 52 12

### CODE REVIEW

File: app/tests/spec/views/form.js [hunk 1]
```diff
@@ -336,11 +336,15 @@ describe('views/form', function () {
   });
 
   describe('showValidationError', function () {
-    it('creates a tooltip', function () {
-      view.on('validation_error', function (done) {
```
Comment (shane-tomlinson) [inline app/tests/spec/views/form.js]: This test was wrong before, `done` wasn't a function but the error wasn't being caught because this is inside an event handler. `done` should be on the `it`.
