### PR TITLE
fix(avatars): show error if avatar removal fails

### LINKED ISSUE #2116: no error displayed on delete avatar failure
My profile server in fxa-local-dev is not working correctly and errors whenever deleting a profile image. When this occurs, no user visible error message is displayed:

screen shot 2015-02-19 at 13 05 53

### PR DESCRIPTION
**Pull request by zaach**
Fixes #2116.

@shane-tomlinson or @vladikoff r?

### CODE REVIEW

File: app/tests/spec/views/settings/avatar_change.js [hunk 1]
```diff
@@ -104,14 +105,32 @@ function (chai, _, $, sinon, View, RouterMock, FileReaderMock, ProfileMock,
...
+          });
+      });
 
-            return view.remove()
-              .then(function () {
-                assert.isTrue(profileClientMock.deleteAvatar.calledWith(
-                  accessToken, 'foo'));
-                assert.isNull(account.get('profileImageUrl'));
-                assert.equal(routerMock.page, 'settings');
-              });
```
Comment (zaach) [inline app/tests/spec/views/settings/avatar_change.js]: Unrelated: fix the unnecessary promise nesting.
