### PR TITLE
fix(pw-strength): Make the pw-strength balloon more a11y friendly. 

### LINKED ISSUE #6299: Follow best a11y practices for the password strength bubble.
Marco Zehe reminded me to keep accessibility in mind for the new password strength bubble. Showing the checkboxes as background images is not screen reader friendly.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fix(pw-strength): Make the pw-strength balloon more a11y friendly.

* Use `aria-invalid` on the input element whenever the element is invalid
* Use `aria-described-by` to point to the criterion that failed when invalid
* Remove the focus on blur behavior, instead focus on submit if a validation error

fixes #6299

### CODE REVIEW

File: app/scripts/views/password_strength/password_with_strength_balloon.js [hunk 1]
```diff
@@ -67,11 +56,31 @@ const PasswordWithStrengthBalloonView = FormView.extend({
     const { hasEnteredPassword, isValid } = this.model.toJSON();
 
     if (hasEnteredPassword && ! isValid) {
-      this.$el.addClass('invalid');
+      this.$el.addClass('invalid').attr('aria-invalid', 'true');
```
Comment (philbooth) [inline app/scripts/views/password_strength/password_with_strength_balloon.js]: Is this pattern of setting/unsetting `aria-invalid` at the same time as the `invalid` class something we should be applying elsewhere too? If so is it worth pulling out somewhere more generally usable?

Comment (shane-tomlinson) [reply app/scripts/views/password_strength/password_with_strength_balloon.js]: That's a good idea @philbooth, we *will* need it for https://github.com/mozilla/fxa-content-server/issues/6310. Extracting now.
