### PR TITLE
fix(oauth): translate oauth permissions

### LINKED ISSUE #4758: OAuth permissions are not translated
Signing up to Pocket from their website, using the “Sign up with Firefox Accounts” button, I get this screen with two hardcoded strings:

capture d ecran 2017-02-27 a 20 29 08

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4758

### CODE REVIEW

**Comment by vladikoff** [comment]
after fix: 

image

File: app/tests/spec/views/permissions.js [hunk 1]
```diff
@@ -123,6 +123,29 @@ define(function (require, exports, module) {
...
+              if (untranslatedText === 'Email address') {
+                return TRANSLATED_PERMISSION_NAME;
+              }
+
+              return untranslatedText;
+            }
+          };
+
+          return view.render().then(() => {
+            assert.equal(view.$('.fxa-checkbox__label:eq(0)').text(), 'Адрес электронной почты (обязательно)');
```
Comment (vbudhram) [inline app/tests/spec/views/permissions.js]: Nice 👍
