### PR TITLE
fix(tests): Fix the `sign in, open settings in a second tab` test.

### LINKED ISSUE #4337: flaky test - 'sign in, open settings in a second tab, sign out'
I've seen this fail frequently on both latest w/ teamcity and now circle.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
When run against a remote server, it was possible to open the settings
tab the second tab before the user was signed in in the first tab.
Wait for the user to be fully signed in and the settings page to appear
in the first tab before opening the second tab.

fixes #4337 

@vladikoff - r?

### CODE REVIEW

File: tests/functional/settings.js [hunk 1]
```diff
@@ -172,27 +174,21 @@ define([
 
     'sign in, open settings in a second tab, sign out': function () {
       var windowName = 'sign-out inter-tab functional test';
-      var self = this;
-      return FunctionalHelpers.fillOutSignIn(this, email, FIRST_PASSWORD)
-        .then(function () {
-          return FunctionalHelpers.openSettingsInNewTab(self, windowName);
```
Comment (shane-tomlinson) [inline tests/functional/settings.js]: This is where the original problem was, we didn't wait for the original tab to sign in before opening settings in the new tab.

**Comment by vladikoff** [comment]
Needs rebase....

**Comment by shane-tomlinson** [comment]
@vladikoff - rebased
