### PR TITLE
fix(test): Ensure `addEventListener` exists before invoking.

### LINKED ISSUE #3408: flaky oauth tests - 'Permission denied to access property "addEventListener"'
I've noticed this occasionally in test runs. So I put it in a loop focused on a small grep of tests. 2 of 10 fail on latest.dev.lcip.org (and also fail on accounts.stage.mozaws.net, which was running the same version of fxa-*-server as latest).

```
for i in `seq 10`; do ./node_modules/.bin/intern-runner config=tests/intern_functional_full fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 fxaContentRoot=https://latest.dev.lcip.org/ fxaOauthApp=https://123done-latest.dev.lcip.org/ fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ fxaIframeOauthApp=https://123done-latest.dev.lcip.org/iframe fxaEmailRoot=http://restmail.net fxaProduction=true firefoxBinary=/home/jrgm/firefox-channels/latest-beta/en-US/firefox/firefox-bin grep="oauth sign up - sign up, bounce email, allow user to restart flow but force a different email|oauth sign up verification_redirect|oauth reset password" | grep -v '~'; sleep 5; done
```

Example set of failure messages (interesting message about 'Permission denied to access property "addEventListener"')
```
TOTAL: tested 1 platforms, 0/403 tests failed (393 skipped)
Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (44954d11-d7e9-4924-8ff7-233473e622e3)
✓ firefox on any platform - oauth sign up - sign up, bounce email, allow user to restart flow but force a different email (16.012s)
✓ firefox on any platform - oauth sign up verification_redirect - signup, same browser same window, verification_redirect=always (8.705s)
✓ firefox on any platform - oauth sign up verification_redirect - signup, same browser, original tab closed, verification_redirect=always (14.312s)
× firefox on any platform - oauth sign up verification_redirect - signup, same browser different window, verification_redirect=always (37.469s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/44954d11-d7e9-4924-8ff7-233473e622e3/element / {"using":"css selector","value":"#loggedin"}] Unable to locate element: {"method":"css selector","selector":"#loggedin"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-68-generic', java.version: '1.7.0_85'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1125:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16>
  at Test.registerSuite.signup, same browser different window, verification_redirect=always [as test]  <tests/functional/oauth_sign_up_verification_redirect.js:113:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
✓ firefox on any platform - oauth sign up verification_redirect - signup, verify different browser, verification_redirect=always (8.751s)
× firefox on any platform - oauth reset password - reset password, verify same browser (6.272s)
JavaScriptError: [POST http://localhost:4444/wd/hub/session/44954d11-d7e9-4924-8ff7-233473e622e3/execute / {"script":"return (function openWindow(url, name) {\n    var newWindow = window.open(url, name);\n\n    // Hook up the new window to listen for WebChannel messages.\n    // XXX TODO: this is pretty gross to do universally like this...\n    // XXX TODO: it will go away if we can make the original tab\n    //           reliably be the one to complete the oauth flow.\n    newWindow.addEventListener('WebChannelMessageToChrome', function (e) {\n      var command = e.detail.message.command;\n      var data = e.detail.message.data;\n      var element = newWindow.document.createElement('div');\n      element.setAttribute('id', 'message-' + command.replace(/:/g, '-'));\n      element.innerText = JSON.stringify(data);\n      newWindow.document.body.appendChild(element);\n    });\n\n    // from http://dev.w3.org/html5/webstorage/\n    // When a new top-level browsing context is created by a script in\n    // an existing browsing context, then the session storage area of\n    // the origin of that Document must be copied into the new\n    // browsing context when it is created. From that point on,\n    // however, the two session storage areas must be considered\n    // separate, not affecting each other in any way.\n    //\n    // We want to pretend this is a new tab that the user opened using\n    // CTRL-T, which does NOT copy sessionStorage over. Wipe\n    // sessionStorage in this new context;\n    newWindow.sessionStorage.clear();\n\n    return true;\n  }).apply(this, arguments);","args":["https://latest.dev.lcip.org/v1/complete_reset_password?token=c19eb95c712fd6fffac7b6ab40bc9c92790ea4190dd0a0f3ed6d7bd59d56e97b&code=53d4aac4e84d0fb6a124e5895842ee1c&email=signin0.020739965373650193%40restmail.net&service=dcdb5ae7add825d2&resume=eyJjYW1wYWlnbiI6bnVsbCwiZW50cnlwb2ludCI6bnVsbCwic3RhdGUiOiIzZDM4ZGI2Y2Q5ZmI0MWJlZjY5MjRmNTU4NDc4YjljMDhmYWQxMDhlZjUwMDI0MWE5ZWUzMDg5NGYwMTNmNWI3IiwidW5pcXVlVXNlcklkIjoiNjQ1Y2JkZjgtOTliOC00OTk1LTliMWItZjY1MjZiZWU1ZWJlIiwidXRtQ2FtcGFpZ24iOm51bGwsInV0bUNvbnRlbnQiOm51bGwsInV0bU1lZGl1bSI6bnVsbCwidXRtU291cmNlIjpudWxsLCJ1dG1UZXJtIjpudWxsLCJ2ZXJpZmljYXRpb25SZWRpcmVjdCI6Im5vIn0%3D","newwindow"]}] Permission denied to access property "addEventListener"
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-68-generic', java.version: '1.7.0_85'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.execute  <node_modules/intern/node_modules/leadfoot/Session.js:638:21>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:635:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.target.(anonymous function) [as execute]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at <tests/functional/lib/helpers.js:251:31>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.reset password, verify same browser [as test]  <tests/functional/oauth_reset_password.js:81:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
× firefox on any platform - oauth reset password - reset password, verify same browser with original tab closed (4.741s)
JavaScriptError: [POST http://localhost:4444/wd/hub/session/44954d11-d7e9-4924-8ff7-233473e622e3/execute / {"script":"return (function openWindow(url, name) {\n    var newWindow = window.open(url, name);\n\n    // Hook up the new window to listen for WebChannel messages.\n    // XXX TODO: this is pretty gross to do universally like this...\n    // XXX TODO: it will go away if we can make the original tab\n    //           reliably be the one to complete the oauth flow.\n    newWindow.addEventListener('WebChannelMessageToChrome', function (e) {\n      var command = e.detail.message.command;\n      var data = e.detail.message.data;\n      var element = newWindow.document.createElement('div');\n      element.setAttribute('id', 'message-' + command.replace(/:/g, '-'));\n      element.innerText = JSON.stringify(data);\n      newWindow.document.body.appendChild(element);\n    });\n\n    // from http://dev.w3.org/html5/webstorage/\n    // When a new top-level browsing context is created by a script in\n    // an existing browsing context, then the session storage area of\n    // the origin of that Document must be copied into the new\n    // browsing context when it is created. From that point on,\n    // however, the two session storage areas must be considered\n    // separate, not affecting each other in any way.\n    //\n    // We want to pretend this is a new tab that the user opened using\n    // CTRL-T, which does NOT copy sessionStorage over. Wipe\n    // sessionStorage in this new context;\n    newWindow.sessionStorage.clear();\n\n    return true;\n  }).apply(this, arguments);","args":["https://latest.dev.lcip.org/v1/complete_reset_password?token=19f5defb18d0f7935b218aec3cb48937b95ed6110568e0ad9619bf63a9d7cc98&code=7eafda7a41407ce95b4d3d58659772cb&email=signin0.5263229398988187%40restmail.net&service=dcdb5ae7add825d2&resume=eyJjYW1wYWlnbiI6bnVsbCwiZW50cnlwb2ludCI6bnVsbCwic3RhdGUiOiI5OWQ1YzU5NGEyMjJkNDExMjIzZTJkMTMyYmZhZjE4MGQyZjhkMzM0YTIyZmNmMmU2ODcyZjQ5MjhiYjc3MDg2IiwidW5pcXVlVXNlcklkIjoiNWU4MWU2ZWItNzI4NS00ZGMyLTkyZjgtMjU1NmUyYzNmMjBlIiwidXRtQ2FtcGFpZ24iOm51bGwsInV0bUNvbnRlbnQiOm51bGwsInV0bU1lZGl1bSI6bnVsbCwidXRtU291cmNlIjpudWxsLCJ1dG1UZXJtIjpudWxsLCJ2ZXJpZmljYXRpb25SZWRpcmVjdCI6Im5vIn0%3D","newwindow"]}] Permission denied to access property "addEventListener"
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-68-generic', java.version: '1.7.0_85'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.execute  <node_modules/intern/node_modules/leadfoot/Session.js:638:21>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:635:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.target.(anonymous function) [as execute]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at <tests/functional/lib/helpers.js:251:31>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.reset password, verify same browser with original tab closed [as test]  <tests/functional/oauth_reset_password.js:137:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
✓ firefox on any platform - oauth reset password - reset password, verify same browser by replacing the original tab (11.356s)
✓ firefox on any platform - oauth reset password - reset password, verify in a different browser, from the original tab's P.O.V. (9.564s)
✓ firefox on any platform - oauth reset password - reset password, verify in a different browser, from the new browser's P.O.V. (8.806s)
No unit test coverage for firefox on any platform
firefox on any platform: 3/403 tests failed (393 skipped)


TOTAL: tested 1 platforms, 3/403 tests failed (393 skipped)
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
If `addEventListener` is not yet available on the window where the
tests are being run, try again after a short timeout.

fixes #3408 

@jrgm, @vladikoff - r?

I'd really like to consolidate the code, though since those all run in an `remove.execute`, I'm not really sure how unless we execute one script that injects the common code, and a second script that runs the code we want to invoke.

### CODE REVIEW

File: tests/functional/lib/helpers.js [hunk 1]
```diff
@@ -581,7 +592,7 @@ define([
           document.body.appendChild(element);
         });
       } else {
-        setImmediate(startListening);
+        setTimeout(startListening, 0);
```
Comment (shane-tomlinson) [inline tests/functional/lib/helpers.js]: Firefox doesn't yet support `setImmediate`, what was I thinking?

**Comment by vladikoff** [comment]
logic is sound, let's if this destroys the error forever!
