### PR TITLE
fix(back-mixin): Fix the "New broker method needed for click" error.

### LINKED ISSUE #5515: [Sentry] New broker method needed for click
Ref https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/647600/events/12083839/

@shane-tomlinson is this something to worry about?

### PR DESCRIPTION
**Pull request by shane-tomlinson**
The back-mixin erroneously passed the back button click event
as `nextViewData` when it invoked the `back` method.

The fix is to use a delegate method that invoked `back`
without the event.

fixes #5515 

@vladikoff - r?

### CODE REVIEW

File: app/scripts/views/mixins/back-mixin.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ define(function (require, exports, module) {
     },
 
     events: {
-      'click #back,.back': preventDefaultThen('back'),
```
Comment (vladikoff) [inline app/scripts/views/mixins/back-mixin.js]: 👍

**Comment by vladikoff** [comment]
Awesome! I'm happy we fixed this in this train :)
