### PR TITLE
fix(tests): add oauth app functional tests

### LINKED ISSUE #4109: Add functional tests for apps once OAuth api lands
Add functional tests for apps once OAuth api lands:

https://github.com/mozilla/fxa-oauth-server/pull/405

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4109

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson r?

you can test it locally or against latest via:

> npm run test-latest grep="rp list"  firefoxBinary=/Users/[user]/Desktop/FF46.app/Contents/MacOS/firefox-bin

File: tests/functional/oauth_settings_clients.js [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+    },
+
+    'rp listed in apps, can be deleted': function () {
+      this.timeout = 90 * 1000;
+
+      return openFxaFromRp(this, 'signup')
+        .then(fillOutSignUp(this, email, PASSWORD))
+        .then(testElementExists('#fxa-confirm-header'))
+        .then(getVerificationLink(email, 0))
+        .then((verificationLink) => {
```
Comment (shane-tomlinson) [inline tests/functional/oauth_settings_clients.js]: Are we allowed to use fat arrows in our functional tests before we are fully ES6 ready?

Comment (vladikoff) [inline tests/functional/oauth_settings_clients.js]: from mtg: not right now, but soon!
