### PR TITLE
fix(client): Log the correct screen name for the settings panels.

### LINKED ISSUE #3029: All settings panels report the screen name as `settings`
```
["settings.communication-prefs-link.visible.true","screen.settings","settings.newsletter.optin.false","settings.refresh","settings.profile_image_not_shown","screen.settings","screen.settings","screen.settings","screen.settings"]
```

Not a problem if we banish the settings page from being iframed (#2945), but something I found while testing #3006.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
There were two problems:
* Subviews always took the screen name of their parent because subviews
  are created with the same options as the parent view, which includes
  the parent view's screen name.
* If the user opened the site directly to a subview, the settings panel
  would take the screen name of the child view, because the settings panel
  took its screen name from the URL, which was the subview's URL.

Add a `screenName` property with the correct name to all settings pages.
If `screenName` is set on the prototype, ignore the screen name passed
in on construction.

fixes #3029

@philbooth or @vladikoff - r?

### CODE REVIEW

File: app/scripts/views/base.js [hunk 1]
```diff
@@ -92,23 +92,39 @@ function (Cocktail, _, Backbone, Raven, $, p, AuthErrors,
...
+     * The default screen name
+     *
+     * @property screenName
+     */
+    screenName: '',
+
     constructor: function (options) {
       options = options || {};
 
-      this.subviews = [];
```
Comment (shane-tomlinson) [inline app/scripts/views/base.js]: I couldn't help but take the opportunity to alphabetize the list of items that don't depend on `this.window`.

File: app/scripts/views/settings/avatar_camera.js [hunk 2]
```diff
@@ -34,6 +34,7 @@ function (_, Cocktail, canvasToBlob, FormView, ProgressIndicator,
   var View = FormView.extend({
     template: Template,
     className: 'avatar-camera',
+    screenName: 'settings.avatar.camera',
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/avatar_camera.js]: I used the same screen name that *should* be passed in by the router so that we are able to remove these hard coded names in the future.

**Comment by philbooth** [comment]
Looks good to me.

**Comment by vladikoff** [comment]
Nice, thanks for fixing the delete account settings events too!
