### PR TITLE
fix(test): Fix the sign_up->afterVisible test

### LINKED ISSUE #6290: unit test failure when run in isolation: views/sign_up->afterVisible->shows a tooltip...
I noticed this while trying to debug #6273 

> views/sign_up
>    afterVisible
>        shows a tooltip on the email element if model.bouncedEmail is set ‣
>        AssertionError: expected false to be true

blocks #6273

### PR DESCRIPTION
**Pull request by shane-tomlinson**
There were two problems, the first is that the assertion needed to be wrapped to ensure
failures were always surfaced. The second problem was TestHelpers.wrapAssertion would
call `done` twice if a test failed.

fixes #6290 

@mozilla/fxa-devs - r?

### CODE REVIEW

File: app/tests/lib/helpers.js [hunk 1]
```diff
@@ -68,6 +68,7 @@ define(function (require, exports, module) {
       fn();
     } catch (e) {
       done(e);
+      return;
```
Comment (philbooth) [inline app/tests/lib/helpers.js]: I'm bike-shedding to the extreme here, so feel free to ignore, but I notice this could also be achieved without the need for an explicit `return` by moving the outer `done()` in to the `try` block. Not sure why but I find the arrangement here a little bit jarring to read.

Comment (shane-tomlinson) [reply app/tests/lib/helpers.js]: I imagine it's jarring because you have to think about the flow control this way and forced thought is annoying. Will update.
