### PR TITLE
fix(signup): show red border only after tooltip rendered

### LINKED ISSUE #1865: invalid input red border turns blue if user clicks "submit"
The red border used for invalid input elements stays red if the user submits via the "enter" key, but turns blue if the user clicks the submit button.

### STR
1) Open the /signup page
2) Enter a valid email
3) Enter a 7 character password
4) Click the "sign up" button or press "enter"
5) Press "Enter" and see that the input field border remains red.
6) Click the "sign up" button again
7) The password field's border is now blue

### Expected
The password field's border remains red

### Actual
The password field's border turns blue.

invalid-input-coloring

### PR DESCRIPTION
**Pull request by npestana**
Add addClass('invalid') to invalid field only after the tooltip rendered.

Closes #1865

### CODE REVIEW

**Comment by vladikoff** [comment]
Tests are failing if you open http://localhost:3030/tests/index.html?grep=views%2Fform

**Comment by npestana** [comment]
Updated the tests to wait for the tooltip to be rendered.

File: app/tests/spec/views/form.js [hunk 1]
```diff
@@ -354,7 +354,9 @@ function (chai, sinon, $, p, FormView, Template, Constants, Metrics, AuthErrors,
 
       it('adds invalid class to the invalid element', function () {
```
Comment (vladikoff) [inline app/tests/spec/views/form.js]: this needs a `done` callback , + `done()` in the timeout, you can find it in other tests

File: app/tests/spec/views/sign_up.js [hunk 2]
```diff
@@ -306,12 +306,16 @@ function (chai, $, sinon, p, View, CoppaDatePicker, Session, AuthErrors, Experim
...
 
+        var self = this;
         return view.render()
           .then(function () {
             return view.afterVisible();
           })
           .then(function () {
             assert.isTrue(view.showValidationError.called);
+            self.timeout(function () {
+              assert.isTrue(view.$('input[type="email"]').hasClass('invalid'));
```
Comment (vladikoff) [inline app/tests/spec/views/sign_up.js]: same as https://github.com/mozilla/fxa-content-server/pull/3120/files#r40874212

**Comment by vladikoff** [comment]
@npestana go ahead and squash these commits when you have time

**Comment by npestana** [comment]
Commits squashed. :)

**Comment by vladikoff** [comment]
Thanks again!
