### PR TITLE
fix(client): Only request keys from the server for Sync users.

### LINKED ISSUE #237: Determine when to use /account/login and /account/login?keys=true
I propose based on the `service` parameter, specifically if `service=sync`. Additionally, if `service` is not `sync` then we shouldn't try to do the whole browser communication channel thing. Let's hold off on merging this until https://bugzilla.mozilla.org/show_bug.cgi?id=959859 lands in m-c, which I expect will be soon.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@ckarlof - could you review this to see if this matches expectations for #237?

fixes #237

### CODE REVIEW

File: app/tests/spec/lib/fxa-client.js [hunk 1]
```diff
@@ -64,19 +64,42 @@ function (chai, $, sinon, p, testHelpers, Session, FxaClientWrapper,
...
+          .then(function (sessionData) {
             assert.isTrue(realClient.signUp.calledWith(trim(email), password, {
               keys: true,
               service: SERVICE,
               redirectTo: REDIRECT_TO,
               resume: expectedResumeToken
             }));
+
+            assert.equal(sessionData.unwrapBKey, 'unwrapBKey');
+            assert.equal(sessionData.keyFetchToken, 'keyFetchToken');
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/fxa-client.js]: I am checking to ensure the keys from the server [are added to the updatedSessionData](https://github.com/mozilla/fxa-content-server/pull/2005/files#diff-341971be75d35dbd724949cda527a0efR119) when expected. I can add further assertions in the test below. Perhaps the [guard](https://github.com/mozilla/fxa-content-server/pull/2005/files#diff-341971be75d35dbd724949cda527a0efR118) is not necessary and we just return the keys if they are in the server returned accountData.
