### PR TITLE
fix(sentry): update to latest raven.js, fix up validation rules

### LINKED ISSUE #4828: Sentry not working on the client-side, not sending reports in prod
Testing this in prod and no reports are being sent from client-side
Server-side is working fine.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4828

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson r?

**Comment by vladikoff** [comment]
Configuration link: https://docs.google.com/a/mozilla.com/document/d/1VKFsMjI08nOJH4T9xPVLb9VFmVXfnIYsYbopux7lbQM/edit?usp=sharing

File: server/lib/routes/post-metrics-errors.js [hunk 1]
```diff
@@ -126,7 +116,7 @@ function setExtraSentryData(data) {
  *          Body of the error request.
  */
 function reportError(query, body) {
-  if (! query || ! body || ! _.isObject(query) || ! _.isString(body)) {
+  if (! query || ! body || ! _.isObject(query) || ! _.isObject(body)) {
     return;
```
Comment (jrgm) [inline server/lib/routes/post-metrics-errors.js]: Can you add a log line when the data is not ok?

Comment (vladikoff) [inline server/lib/routes/post-metrics-errors.js]: Sure! thanks @jrgm

File: server/lib/routes/post-metrics-errors.js [hunk 2]
```diff
@@ -91,31 +91,21 @@ const QUERY_SCHEMA = {
 /**
  * Attaches extra tags to sentry data
  *
- * @param {String} data - stringified Sentry data object
+ * @param {String} sentryData - stringified Sentry data object
```
Comment (shane-tomlinson) [inline server/lib/routes/post-metrics-errors.js]: Since this works directly with the data object, `stringified` no longer seems applicable, and the type should be `Object`.

File: server/lib/routes/post-metrics-errors.js [hunk 3]
```diff
@@ -91,31 +91,21 @@ const QUERY_SCHEMA = {
...
  * @returns {String} data - stringified Sentry data object with extra tags
```
Comment (shane-tomlinson) [inline server/lib/routes/post-metrics-errors.js]: `stringified` no longer applies here either it seems. And an `Object` is returned.

**Comment by shane-tomlinson** [comment]
@vladikoff - could you add this patch to add tests for the changes:

```diff
diff --git a/tests/server/metrics-errors.js b/tests/server/metrics-errors.js
index 4f1376bf..c5a8d205 100644
--- a/tests/server/metrics-errors.js
+++ b/tests/server/metrics-errors.js
@@ -33,25 +33,29 @@ define([
   };
 
   suite['#post /metrics-errors - returns 200'] = {
-    'culprit ()': testValidMetricsErrorField('culprit', undefined),
-    'exception w/ empty value': testValidException('value', ''),
-    'level ()': testValidMetricsErrorField('level', undefined),
+    'culprit (undefined)': testValidMetricsErrorField('culprit', undefined),
+    'exception value (empty)': testValidException('value', ''),
+    'level (undefined)': testValidMetricsErrorField('level', undefined),
+    'message (undefined)': testValidMetricsErrorField('message', undefined),
     'no query params': testValidMetricsError(VALID_METRICS_ERROR),
     'query': testValidMetricsError(VALID_METRICS_ERROR, '?sentry_version=4'),
-    'release ()': testValidMetricsErrorField('release', undefined),
-    'stacktrace frame w/ null colno': testValidStacktraceFrame('colno', null),
-    'stacktrace frame w/ null lineno': testValidStacktraceFrame('colno', null),
-    'tags ()': testValidMetricsErrorField('tags', undefined),
-    'tags.code ()': testValidTagValue('code', undefined),
+    'release (undefined)': testValidMetricsErrorField('release', undefined),
+    'stacktrace frame w/ colno (null)': testValidStacktraceFrame('colno', null),
+    'stacktrace frame w/ colno (undefined)': testValidStacktraceFrame('colno', undefined),
+    'stacktrace frame w/ function (undefined)': testValidStacktraceFrame('function', undefined),
+    'stacktrace frame w/ lineno (null)': testValidStacktraceFrame('colno', null),
+    'stacktrace frame w/ lineno (undefined)': testValidStacktraceFrame('colno', undefined),
+    'tags (undefined)': testValidMetricsErrorField('tags', undefined),
     'tags.code (400)': testValidTagValue('code', 400),
-    'tags.context ()': testValidTagValue('context', undefined),
+    'tags.code undefined': testValidTagValue('code', undefined),
     'tags.context (settings.avatar.gravatar)': testValidTagValue('context', 'settings.avatar.gravatar'),
     'tags.context (settings.change-password)': testValidTagValue('context', 'settings.change-password'),
+    'tags.context (undefined)': testValidTagValue('context', undefined),
     'tags.context (unknown context)': testValidTagValue('context', 'unknown context'),
-    'tags.errno ()': testValidTagValue('errno', undefined),
     'tags.errno (400)': testValidTagValue('errno', 400),
     'tags.errno (Error)': testValidTagValue('errno', 'Error'),
     'tags.errno (QuotaRandomError)': testValidTagValue('errno', 'QuotaRandomError'),
+    'tags.errno (undefined)': testValidTagValue('errno', undefined),
   };
 
   suite['#post /metrics-errors - returns 400 with invalid body'] = function () {
```

With the additional tests, r+, thanks for this!

**Comment by vladikoff** [comment]
@shane-tomlinson thanks for the test updates!
