### PR TITLE
fix(email): Add success message when removing secondary email

### LINKED ISSUE #5367: Add success feedback when secondary email is removed
STEPS TO REPRODUCE
1. Remove a secondary email from your Firefox Account

EXPECTED RESULTS
* Section closes
* Green success message appears letting user know "Secondary email removed"

image

ACTUAL RESULTS
* Section stays open, no success message is presented

### PR DESCRIPTION
**Pull request by vbudhram**
This PR Fixes #5367 and updates selectors. I split into separate commits to help with review.

@shane-tomlinson @mozilla/fxa-devs r?

### CODE REVIEW

File: tests/functional/settings_secondary_emails.js [hunk 1]
```diff
@@ -77,6 +77,8 @@ define([
         .then(click('.email-add:not(.disabled)'))
         .then(testElementExists('.not-verified'))
         .then(click('.email-address .settings-button.warning.email-disconnect'))
+        .then(visibleByQSA('.success'))
+        .then(click('#emails .settings-unit-stub button'))
```
Comment (vbudhram) [inline tests/functional/settings_secondary_emails.js]: @shane-tomlinson This test consistently fails in circle-ci but not locally,

```
The element reference of <button class="settings-button settings-unit-toggle hidden secondary"> stale: either the element is no longer attached to the DOM or the page has been refreshed
```

At a glance, is there anything that jumps out that I am not doing with the test?

Comment (vladikoff) [reply tests/functional/settings_secondary_emails.js]: @vbudhram After disconnect, is the panel re-rendered? If so then there will be 2 of those elements matching the selector, the old one that got removed and the new rendered one

**Comment by vbudhram** [comment]
Able to replicate errors locally when testing against FF53 which is what circle ci uses.
