### PR TITLE
fix(timers): Always destroy timers created in view.setTimeout.

### LINKED ISSUE #6291: setTimeout timers are not always cleared on destroy
If [`clearTimeout` is called with `undefined`](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/timer-mixin.js#L37), `this._timeouts` ends up with the value of `[]`. If `setTimeout` is then called, [the `destroy` listener will not be attached](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/timer-mixin.js#L23).

blocks #6273

### PR DESCRIPTION
**Pull request by shane-tomlinson**
clearTimeout did not check whether `timeout` was defined
before trying to clear the timer and update the list of timers.

The fix is to check for a `timeout` reference in clearTimeout
before updating `this._timers`

fixes #6291

@mozilla/fxa-devs - r?

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Note, I updated the modules to ditch the AMD wrappers, this is easiest to review with `?w=1`

File: app/tests/spec/views/mixins/timer-mixin.js [hunk 1]
```diff
@@ -2,82 +2,77 @@
...
+      view.setTimeout(function () {
+        TestHelpers.wrapAssertion(() => {
+          assert.strictEqual(this, view);
+        }, done);
+      }, 1);
     });
+  });
+
+  describe('clearTimeout', function () {
+    it('clears an outstanding timeout', function (done) {
```
Comment (philbooth) [inline app/tests/spec/views/mixins/timer-mixin.js]: Is it possible/worth adding a test that asserts the behaviour when calling `clearTimeout` with `undefined`? (not sure if there's any observable/assertable effects from that)

Comment (shane-tomlinson) [reply app/tests/spec/views/mixins/timer-mixin.js]: Good point. Will add a test.
