### PR TITLE
fix(client): Do not skip "reset password" screen in force_auth.

### LINKED ISSUE #3477: Stop skipping the first step of reset password for force auth users
CURRENT:
When users are forced to authenticate, they have the option to reset their password. Currently this skips the first screen and sends the reset email directly. This is problematic because many users don't understand the ramifications of resetting their password (and potentially losing sync data).

PROPOSED:
Take them to the Reset Password form with their email filled in, read-only.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
The "Forgot password" from force_auth should go to the "reset password" screen
where the email should not be editable.

fixes #3477

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
I'm pulling the WIP label off of this, all the tests pass. :D

I'd like to get @ryanfeeley's feedback on whether the UX is as expected before merge. 

@vbudhram - care to do a preliminary code review?

File: app/scripts/views/force_auth.js [hunk 1]
```diff
@@ -136,8 +141,8 @@ define(function (require, exports, module) {
       };
     },
 
-    events: _.extend(SignInView.prototype.events, {
```
Comment (shane-tomlinson) [inline app/scripts/views/force_auth.js]: This was an error earlier, the only reason we didn't come across it is because the signin page has no links to `/confirm_reset_password`. Unfortunately the signin page does have a link to `/reset_password` and this handler overwrote the signin variant for the signin screen.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Sounds like exactly what we need!

File: tests/functional/force_auth.js [hunk 2]
```diff
@@ -151,13 +151,17 @@ define([
...
         .then(openForceAuth({ query: { email: email }}))
         .then(click('.reset-password'))
 
-        .then(testElementExists('#fxa-confirm-reset-password-header'))
+        .then(testElementExists('#fxa-reset-password-header'))
+        .then(testElementValueEquals('input[type=email]', email))
+        .then(testElementDisabled('input[type=email]'))
+        .then(testElementTextInclude('.prefillEmail', email))
+
         // user remembers her password, clicks the "sign in" link. They
```
Comment (shane-tomlinson) [inline tests/functional/force_auth.js]: Oooh.. Add a second test here to ensure that a user who resets their password and is at the confirm screen, then clicks "sign in" still goes back to force auth.

**Comment by shane-tomlinson** [comment]
>  For some reason, I was expecting email to have more of input text field disabled look.

I used the same HTML we use for force_auth to keep consistency. If we change the way the email is displayed to an input field, I'd like to keep consistency and change it in both places.

**Comment by shane-tomlinson** [comment]
> I used the same HTML we use for force_auth to keep consistency. 

`force_auth` should be `force_auth and signup with forced email` in that statement.

**Comment by shane-tomlinson** [comment]
Assigning to @ryanfeeley for UX review. Thanks @vbudhram!

**Comment by vladikoff** [comment]
Needs rebase

**Comment by ryanfeeley** [comment]
:+1:
