### PR TITLE
fix(pw-strength): Report password strength metrics to amplitude

### LINKED ISSUE #6349: pw strength metrics are not reported to amplitude

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #6349 

@philbooth - r?

### CODE REVIEW

File: app/scripts/lib/experiments/password-strength.js [hunk 1]
```diff
@@ -15,24 +15,24 @@ class PasswordStrengthExperiment extends BaseExperiment {
...
-      this.savePasswordBlockedState('common');
+      this.logPasswordBlockedError('common');
     }
   }
 
-  savePasswordBlockedState (state) {
-    this.saveState('blocked');
-    this.saveState(state);
+  logPasswordBlockedError (state) {
+    this.logEvent('blocked');
```
Comment (shane-tomlinson) [inline app/scripts/lib/experiments/password-strength.js]: I changed from `saveState` to `logEvent` because `saveState` will allow at most one of each event type per browser, unless the user clears their localStorage.

**Comment by shane-tomlinson** [comment]
I'd like to create a content-server point release for this PR to ship once train-116 goes to prod, and then a separate point release for #6355 once we know metrics are being reported to amplitude correctly.

File: server/lib/amplitude.js [hunk 2]
```diff
@@ -54,6 +54,10 @@ const VIEW_ENGAGE_SUBMIT_EVENT_GROUPS = {
 // In the following regular expressions, the first match group is
 // exposed as `eventCategory` and the second as `eventTarget`.
 const FUZZY_EVENTS = new Map([
+  [ /^experiment\.(?:designF|designG)\.passwordStrength\.([\w]+)$/, {
```
Comment (shane-tomlinson) [inline server/lib/amplitude.js]: The regexp needs to include `control`

File: server/lib/amplitude.js [hunk 3]
```diff
@@ -54,6 +54,10 @@ const VIEW_ENGAGE_SUBMIT_EVENT_GROUPS = {
 // In the following regular expressions, the first match group is
 // exposed as `eventCategory` and the second as `eventTarget`.
 const FUZZY_EVENTS = new Map([
+  [ /^experiment\.(?:control|designF|designG)\.passwordStrength\.([\w]+)$/, {
```
Comment (shane-tomlinson) [inline server/lib/amplitude.js]: @philbooth - will the F and G in designF and designG be a problem?

Comment (shane-tomlinson) [reply server/lib/amplitude.js]: From the output, it looks like those are automagically converted to snake case.

**Comment by shane-tomlinson** [comment]
Here's an example of the output for control:

```json
{"op":"amplitudeEvent","event_type":"fxa_reg - password_blocked","time":1531327011280,"device_id":"6ac896fd1ee14fa3a3157fe95cb0ed18","session_id":1531326844360,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.13","event_properties":{"service":"sync"},"user_properties":{"flow_id":"bd776c017a055f388afc73f1acf8eafe9ff0f57e91d5f215ae0b3c22c171d97b","ua_browser":"Firefox","ua_version":"61.0","$append":{"fxa_services_used":"sync","experiments":["password_strength_control"]}}}
{"op":"amplitudeEvent","event_type":"fxa_reg - password_missing","time":1531327011280,"device_id":"6ac896fd1ee14fa3a3157fe95cb0ed18","session_id":1531326844360,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.13","event_properties":{"service":"sync"},"user_properties":{"flow_id":"bd776c017a055f388afc73f1acf8eafe9ff0f57e91d5f215ae0b3c22c171d97b","ua_browser":"Firefox","ua_version":"61.0","$append":{"fxa_services_used":"sync","experiments":["password_strength_control"]}}}
```
Here's an example of the output for "designF":

```json
{"op":"amplitudeEvent","event_type":"fxa_reg - password_blocked","time":1531327164748,"device_id":"b93dbb8a41f04f16a66db702d60b8c07","session_id":1531327159781,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.13","event_properties":{"service":"sync"},"user_properties":{"flow_id":"9997a3df1d474cfee7573f14d2367e26b41e92872c95506232d39812a7d65e5d","ua_browser":"Firefox","ua_version":"61.0","$append":{"fxa_services_used":"sync","experiments":["password_strength_design_f"]}}}
{"op":"amplitudeEvent","event_type":"fxa_reg - password_too_short","time":1531327164749,"device_id":"b93dbb8a41f04f16a66db702d60b8c07","session_id":1531327159781,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.13","event_properties":{"service":"sync"},"user_properties":{"flow_id":"9997a3df1d474cfee7573f14d2367e26b41e92872c95506232d39812a7d65e5d","ua_browser":"Firefox","ua_version":"61.0","$append":{"fxa_services_used":"sync","experiments":["password_strength_design_f"]}}}
```

**Comment by shane-tomlinson** [comment]
@philbooth is on PTO, removing his review request (do not review this @philbooth!). 

@mozilla/fxa-devs - r?
