### PR TITLE
fix(firstrun): increase response timeout for iframing

### LINKED ISSUE #2946: firstrun - throwing "can only be placed into an IFRAME on approved sites"
image

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2946

### CODE REVIEW

File: app/scripts/lib/origin-check.js [hunk 1]
```diff
@@ -77,7 +80,11 @@ define([
         .fail(function (err) {
           if (/Timed out/.test(String(err))) {
             // a timeout is A-OK, no allowed origins are listening.
+            Raven.captureException(new Error('Origin check timed out'));
+
             return null;
```
Comment (zaach) [inline app/scripts/lib/origin-check.js]: There seems to be a logical error in the original code, like it was supposed to re-throw the error if the conditional wasn't satisfied. Otherwise, this return statement is a no-op.

Comment (vladikoff) [inline app/scripts/lib/origin-check.js]: from irc: let's fix that in the later train, for now just adjusting the timeout.

**Comment by vladikoff** [comment]
Waiting for CIs to pass...

File: app/scripts/lib/origin-check.js [hunk 2]
```diff
@@ -25,11 +25,14 @@
...
-], function (p, IFrameChannel) {
+  'lib/channels/iframe',
+  'raven'
+], function (p, IFrameChannel, Raven) {
   'use strict';
 
-  var RESPONSE_TIMEOUT_MS = 100;
+  // This timeout needs to be long enough for slow machines to able to respond to
+  // See https://github.com/mozilla/fxa-content-server/issues/2946 for details
+  var RESPONSE_TIMEOUT_MS = 5000;
```
Comment (TDA) [inline app/scripts/lib/origin-check.js]: Is there a reason for 5000? or is it a magic number? from irc: `absolute worst case was 1634ms`.

Comment (vladikoff) [inline app/scripts/lib/origin-check.js]: @TDA it's a "tested" number for now. it is doubled because the firstrun page is heavier. 
However in case of timeout we do nothing anyway and just log a message. Only those who are iframing without permission have to wait 5 seconds to get a respone back.

Comment (vladikoff) [inline app/scripts/lib/origin-check.js]: and by response back is "iframing is only allowed by approved origins"

Comment (TDA) [inline app/scripts/lib/origin-check.js]: All right, that kinds makes sense. @vladikoff

**Comment by zaach** [comment]
:+1: LGTM
