### PR TITLE
fix(test): Fix the Sync v1 reset_password test.

### LINKED ISSUE #5528: failing functional test - Firefox Desktop Sync v1 reset_password - reset password, verify same browser
STR

1. Run `npm run test-functional grep="Firefox Desktop Sync v1 reset_password - reset password, verify same browser"`

> NoSuchElement: [POST http://localhost:4444/wd/hub/session/57f68a6e-de8d-4b74-8b51-b62db6e6b5a7/element / {"using":"css selector","value":"#message-login"}] Unable to locate element: #message-login
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'stomlinson-30887', ip: '192.168.0.22', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/cq/drrh74v57_x_x6ksf_7pk2x80000gn/T/rust_mozprofile.OTyKhJM5U0Qg, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=16.7.0, moz:processID=21622.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 1e3d17db-1641-aa40-ab25-e86d4fa2274a
*** Element info: {Using=css selector, value=#message-login}
  at Command.<anonymous>  <tests/functional/lib/fx-desktop.js:77:10>
  at Test.reset password, verify same browser [as test]  <tests/functional/sync_reset_password.js:71:10>

Fails because `customizeSync` is not set in the Account.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
The `customizeSync` attribute was not available on the account.

This is a regression due to us filtering out `undefined` values
on login data, introduced in d31de3522a6e57bf172009ad5eb3a9369eff3624.

fixes #5528 

@vladikoff or @vbudhram - r?

### CODE REVIEW

File: app/scripts/models/auth_brokers/fx-sync-channel.js [hunk 1]
```diff
@@ -182,6 +182,15 @@ define(function (require, exports, module) {
     },
 
     afterResetPasswordConfirmationPoll (account) {
+      // We wouldn't expect `customizeSync` to be set when completing
+      // a password reset, but the field must be present for the message
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-sync-channel.js]: `for the message to be sent for the login message to be sent`. Seems like only the 2nd half of the sentence is useful.
