### PR TITLE
fix(email): Add ability for content server to delegate sending emails

### LINKED ISSUE #4105: Add ability to delegate sending emails to auth-server
As part of https://github.com/mozilla/fxa-auth-server/issues/1325, we need to give the content server the ability to delegate sending verification emails on login to the auth-server.

This is part of https://github.com/mozilla/fxa-auth-server/pull/1435#issuecomment-243655573. Once this has been added, we can set the default action of the auth-server to [send verification email](https://github.com/mozilla/fxa-auth-server/pull/1435/files#r76800227) on login, if unverified.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #4105

### CODE REVIEW

File: app/scripts/models/user.js [hunk 1]
```diff
@@ -360,8 +360,11 @@ define(function (require, exports, module) {
         .then(function () {
           var isSignUp =
             account.get('verificationReason') === VerificationReasons.SIGN_UP;
+          var emailSent = !! account.get('emailSent');
 
-          if (! account.get('verified') && isSignUp) {
+          // Only send account verification email, it signing up
```
Comment (shane-tomlinson) [inline app/scripts/models/user.js]: `it signing` => `if signing`

File: app/tests/spec/models/user.js [hunk 2]
```diff
@@ -674,62 +674,80 @@ define(function (require, exports, module) {
         });
       });
 
-      describe('with an unverified account', function () {
-        beforeEach(function () {
-          account = user.initAccount({ email: 'email', uid: 'uid' });
+      // Ensure that content-server can correctly handle any emailSent response
+      var emailSentTestCases = [{
```
Comment (shane-tomlinson) [inline app/tests/spec/models/user.js]: Can you use `const` instead of `var` here? We're living in the (mostly) present in the content server!

File: app/tests/spec/models/user.js [hunk 3]
```diff
@@ -674,62 +674,80 @@ define(function (require, exports, module) {
...
+              return p();
+            });
 
-          sinon.stub(account, 'get', function (property) {
-            if (property === 'verified') {
-              return false;
-            } else if (property === 'verificationReason') {
-              return VerificationReasons.SIGN_UP;
-            }
+            sinon.stub(account, 'get', function (property) {
```
Comment (shane-tomlinson) [inline app/tests/spec/models/user.js]: Is there a reason to use a stub and not a simple `set` on the account?

```js
account.set({
  emailSent: testCase.emailSent,
  verificationReason: VerificationReasons.SIGN_UP,
  verified: false
});
```
I don't see the stub checked for whether it's called, so I'm not sure overriding it provides any value.

File: app/scripts/models/user.js [hunk 4]
```diff
@@ -360,8 +360,11 @@ define(function (require, exports, module) {
         .then(function () {
           var isSignUp =
             account.get('verificationReason') === VerificationReasons.SIGN_UP;
+          var emailSent = !! account.get('emailSent');
```
Comment (shane-tomlinson) [inline app/scripts/models/user.js]: Might as well `const` these two variables too.

File: app/scripts/models/user.js [hunk 5]
```diff
@@ -360,8 +360,11 @@ define(function (require, exports, module) {
...
 
-          if (! account.get('verified') && isSignUp) {
+          // Only send account verification email, it signing up
+          // and a verification email has not been sent by auth-server.
+          if (! account.get('verified') && isSignUp && ! emailSent) {
```
Comment (shane-tomlinson) [inline app/scripts/models/user.js]: Are you going to send the `sendEmailIfUnverified` directly from the fxa-js-client? It'd probably be best to only use the fxa-js-client as a pipe that transfers `sendEmailIfUnverified` from the fxa-js-client consumer to the auth server to avoid making an assumption about who is consuming the client, we don't want to inadvertently break anyone.

File: app/tests/spec/models/user.js [hunk 6]
```diff
@@ -674,62 +674,80 @@ define(function (require, exports, module) {
...
 
-          sinon.stub(user, 'setSignedInAccount', function () {
-            return p(account);
-          });
+            sinon.stub(account, 'retrySignUp', function () {
+              return p();
+            });
 
-          sinon.spy(notifier, 'triggerRemote');
+            sinon.stub(user, 'setSignedInAccount', function () {
```
Comment (shane-tomlinson) [inline app/tests/spec/models/user.js]: Is it possible to use a spy instead of a stub here? `setSignedInAccount` doesn't seem like it has any side effects that should cause problems elsewhere.

File: app/scripts/models/user.js (hunk 5 above)
Comment (shane-tomlinson) [inline app/scripts/models/user.js]: Can you update the comment that once we are reasonably sure all consumers delegate email sending to the auth-server, this branch can be removed?

File: app/tests/spec/models/user.js (hunk 3 above)
Comment (shane-tomlinson) [inline app/tests/spec/models/user.js]: It seems like in your account.signIn stub, you should set these values to mimic real life.

File: app/scripts/models/user.js (hunk 5 above)
Comment (vbudhram) [inline app/scripts/models/user.js]: That was my original plan, but decided against it for that reason, the js-client sets the default of `sendEmailIfUnverified=false` if it is not passed. Will update so that value gets propagated to client.

**Comment by vbudhram** [comment]
@shane-tomlinson Updated from review, sending back to you!

**Comment by shane-tomlinson** [comment]
LGTM, once the fxa-js-client merges and we can run the full functional test suite, let's test and merge!

**Comment by vladikoff** [comment]
Needs a new fxa-js-client

**Comment by vbudhram** [comment]
Thanks! @shane-tomlinson @vladikoff
