### PR TITLE
fix(client): getUserMedia check for avatar change.

### LINKED ISSUE #2224: Fx for iOS - Attempt to use camera to set avatar results in "Could not initialize camera"
STR:

1. Install Fx for iOS
1. Sign in to the browser from the preferences. Sign in with a mozilla.com address.
1. When signed in, click on name in Fx preferences to re-open FxA. The "Manage account" page should open.
1. Click on the "Change" link.
1. Select "Camera"
1. BOOM.

We should determine whether a camera upload is supported before showing the Camera option.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Do not show the "camera" icon if the user agent does not support navigator.getUserMedia or any of the vendor specific variants.

fixes #2224

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@zaach or @vladikoff - r?

File: app/scripts/views/settings/avatar_camera.js [hunk 1]
```diff
@@ -71,11 +72,6 @@ function (_, Cocktail, canvasToBlob, FormView, ProgressIndicator,
                              nav.mozGetUserMedia ||
                              nav.msGetUserMedia;
 
-      if (! getUserMedia) {
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/avatar_camera.js]: Since the existence of getUserMedia is checked in beforeRender, it no longer needs to be checked here.

**Comment by zaach** [comment]
Looks good :+1:. There's a separate discussion on whether we want to disable the camera for mobile OSes, since they provide that option natively from the upload option.

**Comment by zaach** [comment]
The coverage says it has decreased, but the report is not available so I'm not sure if that's significant, but maybe worth another look.
