### PR TITLE
fix(avatars): render the camera preview properly in portrait mode

### LINKED ISSUE #2879: Avatar preview get clipped when rotating camera
Found in https://latest.dev.lcip.org/ver.json (commit 9b6beda3ce88c81bed0b877447c6bc6be5a044f4)

```js
{
  version: "0.42.0",
  commit: "9b6beda3ce88c81bed0b877447c6bc6be5a044f4",
  l10n: "d4eafc2302",
  tosPp: "27d35cc967"
}
```

---

### Steps to reproduce:
1. Tested on my trusty LG Nexus 4.
2. Go to https://latest.dev.lcip.org/settings/ and change your avatar.
3. Select Camera, then share your front or back facing camera.
4. Rotate your phone from portrait to landscape.

### Actual results:
screenshot_2015-08-04-09-42-43
**Figure 1 (before):** Phone in portrait mode. Lookin' good!

screenshot_2015-08-04-09-42-57
**Figure 2 (after):** Phone in landscape mode. Note that half my preview gets clipped. Despite that, clicking the "Take picture" button takes a normal looking photo. So only the preview is messed up.

### Expected results:
Circular preview should remain circular while rotating the phone.

### PR DESCRIPTION
**Pull request by zaach**
Fixes #2879.

How's it look @pdehaan?

### CODE REVIEW

**Comment by vladikoff** [comment]
ping @pdehaan

**Comment by zaach** [comment]
@vladikoff if you want to test it out instead that'd also work

File: app/scripts/views/settings/avatar_camera.js [hunk 1]
```diff
@@ -119,17 +119,16 @@ function (_, Cocktail, canvasToBlob, FormView, ProgressIndicator,
...
-      this.height = 0;
+      this.width = 0;
+      this.height = this.displayLength;
 
       this.video[0].addEventListener('canplay', _.bind(this.canPlay, this), false);
     },
 
     canPlay: function () {
       if (! this.streaming) {
+        this.width = this.video[0].videoWidth / (this.video[0].videoHeight / this.height);
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/avatar_camera.js]: If `this.height` is 0, or `this.video[0].videoHeight` is 0, there will be a divide by 0 error. Should this be guarded against?

**Comment by shane-tomlinson** [comment]
@zaach - on my Galaxy S6, portrait mode has cut off sides:

#### Portrait 

screenshot_2015-09-07-11-10-08

#### Landscape

screenshot_2015-09-07-11-10-21

**Comment by shane-tomlinson** [comment]
Test it here: https://stomlinson.dev.lcip.org/

**Comment by pdehaan** [comment]
I see the same thing as @shane-tomlinson on my Galaxy S5:
```js
{
  version: "0.44.1",
  commit: "8a259fcb65761e12630dce03946ffbbd112caba9",
  l10n: "83b33cbb08",
  tosPp: "9f7f0d72e3",
  source: "https://github.com/mozilla/fxa-content-server.git"
}
```

screenshot_2015-09-08-11-13-20

screenshot_2015-09-08-11-13-09

File: app/scripts/views/settings/avatar_camera.js (hunk 1 above)
Comment (zaach) [inline app/scripts/views/settings/avatar_camera.js]: `this.height` would default to 240 rather than ever being 0. `this.video[0].videoHeight` should not be 0 at this point sans browser bugs. We could log an error though to see if it ever happens in practice.

Comment (shane-tomlinson) [inline app/scripts/views/settings/avatar_camera.js]: :+1:

File: app/scripts/views/settings/avatar_camera.js [hunk 2]
```diff
@@ -114,29 +114,42 @@ function (_, Cocktail, canvasToBlob, FormView, ProgressIndicator,
...
+      this.video = this.$('#video')[0];
 
       this._avatarProgressIndicator.start(this.$('.progress-container'));
 
       this.canvas = this.$('#canvas')[0];
-      this.width = 320;
-      this.height = 0;
 
-      this.video[0].addEventListener('canplay', _.bind(this.canPlay, this), false);
+      this.video.addEventListener('loadedmetadata', _.bind(this.onLoadedMetaData, this), false);
```
Comment (zaach) [inline app/scripts/views/settings/avatar_camera.js]: Switched to a more appropriate event `loadedmetadata` so we know video dimensions are set.

**Comment by zaach** [comment]
Can y'all verify the latest fix? Looks like https://stomlinson.dev.lcip.org/signin is still on the old version though.

**Comment by vladikoff** [comment]
@zaach I'll try to take a check this in ~ 2-3 hours or tomorrow morning

**Comment by vladikoff** [comment]
Tested and Camera worked really well in stable Fennec 

However I saw that issue with upload:


Should we open an issue?
