### PR TITLE
fix(back): Clicks on the hash button no longer append # to the URL.

### LINKED ISSUE #5290: Clicks on a "back" link with href="#" append a "#" on the URL, cannot be opened in a new tab
STR

1. In Fx Desktop using a fresh firefox profile, open https://accounts.firefox.com/signup?context=fx_desktop_v3&service=sync
2. Fill out the /signup page
3. On CWTS, click "Mistyped email?"
4. A hash appears on the URL

hash-on-url

This happens because most back links have an href of `#` and we do not call `event.preventDefault()` in the back-mixin's [click #back handler](https://github.com/mozilla/fxa-content-server/blob/3c14509b389952ac5a96ab2e3595bf9ce6873109/app/scripts/views/mixins/back-mixin.js#L24)

Is this a big deal? No. 

This same problem also prevents back links from being opened in a new tab.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
`preventDefaultThen` was being called in the wrong place. We were not
calling it on click handlers, but we were always calling it on keyup,
event if the key was not `ENTER`.

fixes #5290

@mozilla/fxa-devs - r?

### CODE REVIEW

File: app/tests/spec/views/mixins/back-mixin.js [hunk 1]
```diff
@@ -69,21 +68,27 @@ define(function (require, exports, module) {
     });
```
Comment (philbooth) [inline app/tests/spec/views/mixins/back-mixin.js]: Do we need an assertion that `preventDefault` is called for `back` as well?

Comment (shane-tomlinson) [inline app/tests/spec/views/mixins/back-mixin.js]: Added.

**Comment by philbooth** [comment]
LGTM, r+

File: app/scripts/views/mixins/back-mixin.js [hunk 2]
```diff
@@ -56,6 +60,8 @@ define(function (require, exports, module) {
      */
     backOnEnter (event) {
       if (event.which === KeyCodes.ENTER) {
+        event.preventDefault();
```
Comment (vladikoff) [inline app/scripts/views/mixins/back-mixin.js]: 👍
