### PR TITLE
fix(client): Do not allow firstrun Sync based flows to sign out.

### LINKED ISSUE #2658: user is able to sign out if they sign in from firstrun flow
STR

1. Get yer hands on the development firstrun flow (https://github.com/shane-tomlinson/firstrun-example/)
1. Update the SERVER_ORIGIN to `http://127.0.0.1:3030` in https://github.com/shane-tomlinson/firstrun-example/blob/master/client/index.html#L14
1. Start the firstrun sample server.
1. Update the Firefox profile's user.js to point to the local stack
1. open 127.0.0.1:8111
1. Sign up or sign in. Complete verification if signing up
1. Re-open 127.0.0.1:8111 after signup/signin completes.
1. The "sign out" link should not be displayed

ref #2101

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@zaach - can you review this? I'm trying to get this into Train-43 so that users who sign up via the first run flow are unable to sign out, causing their Sync session to be destroyed.

My firefox profile's user.js is [in this gist](https://gist.github.com/shane-tomlinson/7b50f687c80b3987bc7e).

Ah yes, you can fake signing in to sync via the firstrun flow by going to:
http://127.0.0.1:3030/signup?service=sync&context=iframe

or, you can clone https://github.com/shane-tomlinson/firstrun-example/
and add http://127.0.0.1:8111 to the list of allowed_parent_origins in your
local.json

fixes #2658
ref #2101

### CODE REVIEW

File: app/scripts/lib/app-start.js [hunk 1]
```diff
@@ -538,7 +538,7 @@ function (
     },
 
     upgradeStorageFormats: function () {
-      return this._user.upgradeFromSession(Session, this._fxaClient);
+      return this._user.upgradeStorageFormat(Session);
```
Comment (shane-tomlinson) [inline app/scripts/lib/app-start.js]: user already had an fxaClient, no reason to pass it in again.

File: app/scripts/models/account.js [hunk 2]
```diff
@@ -298,24 +312,37 @@ define([
...
+          self.storeSessionData(updatedSessionData, relier);
         });
     },
 
+    storeSessionData: function (sessionData, relier) {
+      var self = this;
+
+      sessionData.isSessionSharedWithFirefox =
+        self.get('isSessionSharedWithFirefox') || relier.isSync();
+
```
Comment (shane-tomlinson) [inline app/scripts/models/account.js]: I want to move [this branch from fxa-client.js](https://github.com/mozilla/fxa-content-server/pull/2853/files#diff-341971be75d35dbd724949cda527a0efR127) here too, but that bloated the PR more. I'll do some other cleanup in a follow on. Down with fxa-client.

File: app/scripts/models/account.js [hunk 3]
```diff
@@ -298,24 +312,37 @@ define([
...
-          self.set(updatedSessionData);
+          self.storeSessionData(updatedSessionData, relier);
         });
     },
 
+    storeSessionData: function (sessionData, relier) {
+      var self = this;
+
+      sessionData.isSessionSharedWithFirefox =
+        self.get('isSessionSharedWithFirefox') || relier.isSync();
```
Comment (zaach) [inline app/scripts/models/account.js]: Perhaps we can just pass the result of `relier.isSync()` so this method doesn't have to know about `relier`.

File: app/scripts/models/account.js [hunk 4]
```diff
@@ -298,24 +312,37 @@ define([
...
-          // prevents sync users from seeing the `sign out` button on the
-          // settings screen.
           return fxaClient.signIn(
             email,
             newPassword,
             relier,
             {
-              reason: fxaClient.SIGNIN_REASON.PASSWORD_CHANGE,
-              sessionTokenContext: self.get('sessionTokenContext')
+              reason: fxaClient.SIGNIN_REASON.PASSWORD_CHANGE
```
Comment (zaach) [inline app/scripts/models/account.js]: Tangent: maybe we should create new methods like `fxaClient.signInAfterPasswordChange` to keep these "reasons" encapsulated within fxaClient.

File: app/scripts/models/account.js [hunk 5]
```diff
@@ -298,24 +312,37 @@ define([
...
             }
           );
         })
         .then(function (updatedSessionData) {
-          self.set(updatedSessionData);
+          self.storeSessionData(updatedSessionData, relier);
         });
     },
 
+    storeSessionData: function (sessionData, relier) {
```
Comment (zaach) [inline app/scripts/models/account.js]: Nit: perhaps call this `setSessionData`– "store" suggests persistence.

File: app/scripts/models/account.js [hunk 6]
```diff
@@ -335,8 +362,67 @@ define([
...
+     * it must be updated through each version. For example, if the current
+     * version number is 3, and the stored account is unversioned, the
+     * sequence is: unversioned->1->2->3
+     *
+     * Each time the data format changes, two things need to happen:
+     * 1. Bump `CURRENT_STORAGE_VERSION`
+     * 2. Add a new function `upgradeTo<N>` where N is the new value of
+     *    `CURRENT_STORAGE_VERSION`. The function should update data
+     *    formats. The function does not need to update `storageVersion`,
+     *    that is handled automatically.
```
Comment (zaach) [inline app/scripts/models/account.js]: Should we go full schema migration and add a downgrade method as well?

File: app/scripts/models/account.js [hunk 7]
```diff
@@ -335,8 +362,67 @@ define([
...
+     */
+    CURRENT_STORAGE_VERSION: 1,
+    upgradeStorageFormat: function () {
```
Comment (zaach) [inline app/scripts/models/account.js]: As far as the account model is concerned, this seems like more of a "data format upgrade" than a "storage format upgrade".

File: app/scripts/models/account.js (hunk 3 above)
Comment (shane-tomlinson) [inline app/scripts/models/account.js]: That's a good idea; part of my goal with this factoring is to rip out the relier from a [similar function in fxa-client](https://github.com/mozilla/fxa-content-server/pull/2853/files#diff-341971be75d35dbd724949cda527a0efR127). It seems like setting session data based on relier information should be the realm of the account instead of the fxa-client. What'cha think?

File: app/scripts/models/account.js (hunk 4 above)
Comment (shane-tomlinson) [inline app/scripts/models/account.js]: Hmm, I hadn't thought of that before, but that does seem to be a much more elegant approach. :+1:

File: app/scripts/models/account.js (hunk 7 above)
Comment (shane-tomlinson) [inline app/scripts/models/account.js]: You are right, I have conflated the two concepts. Hmm.. How can I get out of this?

**Comment by zaach** [comment]
:+1: woot
