### PR TITLE
fix(client): Do not use the OAuth Redirect broker to verify Sync sign ups.

### LINKED ISSUE #3125: Enable Romanian in production
Romanian (ro) is fully translated, could you enable it in production?

@stelistcristi

### LINKED ISSUE #3215: OAuth authentication broker used when verifying Sync
This hasn't caused us problems in the past, though this behavior blocks #3140.

#### STR
1. Apply the patch from below
1. Load up a Firefox profile that is set up to talk to sync with the local stack
1. Sign up for a new account
1. In a new tab, open the dev console, then paste in the verification link in the URL bar.
1. Look in the console for the message "using oauth authentication broker" (shown in the screen shot).

#### Expected
The console message says "using the direct access broker"

screen shot 2015-10-26 at 10 40 43

```diff
diff --git a/app/scripts/lib/app-start.js b/app/scripts/lib/app-start.js
index 1381bd6..5be6d2b 100644
--- a/app/scripts/lib/app-start.js
+++ b/app/scripts/lib/app-start.js
@@ -461,6 +461,7 @@ function (
             window: this._window
           });
         } else if (this._isOAuth()) {
+          console.log('using oauth authentication broker');
           this._authenticationBroker = new RedirectAuthenticationBroker({
             assertionLibrary: this._assertionLibrary,
             metrics: this._metrics,
@@ -470,6 +471,7 @@ function (
             window: this._window
           });
         } else {
+          console.log('using the direct access broker');
           this._authenticationBroker = new BaseAuthenticationBroker({
             relier: this._relier
           });
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Use the direct access authentication broker instead. In the future,
verifications in the same browser will use the same authentication broker used
for signup.

fixes #3215

### CODE REVIEW

**Comment by vladikoff** [comment]
Is this ready or wip?

**Comment by shane-tomlinson** [comment]
@vladikoff - :shipit:

File: app/scripts/lib/app-start.js [hunk 1]
```diff
@@ -659,16 +659,28 @@ function (
...
+    _isServiceOAuth: function () {
+      var service = this._searchParam('service');
+      // any service that is not the sync service is automatically
+      // considered an OAuth service
+      return service && ! this._isServiceSync();
+    },
+
+    _isService: function (compareToService) {
+      var service = this._searchParam('service');
+      return !! (service && compareToService && service === compareToService);
```
Comment (vladikoff) [inline app/scripts/lib/app-start.js]: :+1:
