### PR TITLE
fix(metrics): make metrics.flush safely re-entrant

### LINKED ISSUE #4468: Duplicate flow begin events are emitted
Some flow begin events appear to be emitted twice, with identical timestamp, type and flow id. These are visible both [in redash](https://sql.telemetry.mozilla.org/queries/1794/source) and kibana, so it's definitely not caused by any processing weirdness in the metrics pipeline:

```
fxa=# select e.timestamp, e.flow_id, e.flow_time, e.type from flow_events as e where flow_id = 'ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54';
      timestamp      |                             flow_id                              | flow_time |          type
---------------------+------------------------------------------------------------------+-----------+------------------------
 2016-11-26 23:57:47 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |         0 | flow.force-auth.begin
 2016-11-26 23:57:47 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |         0 | flow.force-auth.begin
 2016-11-26 23:57:55 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |      8314 | flow.force-auth.engage
 2016-11-26 23:57:56 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |      8460 | flow.force-auth.engage
 2016-11-26 23:58:08 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |     20759 | flow.force-auth.submit
 2016-11-26 23:58:08 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |     20995 | flow.signin.attempt
 2016-11-26 23:58:08 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |     20613 | flow.force-auth.submit
 2016-11-26 23:58:08 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |     20849 | flow.signin.attempt
 2016-11-26 23:58:09 | ebafd8e1103968aab73b94f512382f5a3e1cadc1d925457202baadb3fb798a54 |     21769 | account.login
(9 rows)
```

Screenshot showing duplicate content server flow events in Kibana

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #4468. Also see discussion at #4471.

@shane-tomlinson r?

### CODE REVIEW

File: app/tests/spec/lib/metrics.js [hunk 1]
```diff
@@ -288,8 +288,12 @@ define(function (require, exports, module) {
...
             });
 
-            it('does not clear the event stream', function () {
-              assert.equal(metrics.getFilteredData().events.length, 3);
+            it('clears the event stream', () => {
+              assert.equal(metrics.getFilteredData().events.length, 0);
+            });
+
+            it('calls navigator.sendBeacon twice', () => {
+              assert.equal(windowMock.navigator.sendBeacon.callCount, 2);
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/metrics.js]: 👍

**Comment by philbooth** [comment]
> Oddly, or perhaps this is part of the spec, if I have POST /metrics return a 503, the XHR path retries, whereas the sendBecon path does not, sendBeacon reports everything is A-OK.

Yeah, that's part of the spec. The return value from `sendBeacon` only indicates whether the browser has successfully queued the data to be sent, it says nothing about the request itself. Essentially it is specced with a synchronous result from an async function.
