### PR TITLE
fix(validation): accept emails containing an apostrophe on the front-end

### LINKED ISSUE #6702: Apostrophe in username triggers "Valid email required" message
This came up on SuMo: https://support.mozilla.org/questions/1239965

The following appears when clicking "Create account":

fx63-accounts-firefox-valid-email-required

I only see beacons in the Network Monitor so I'm not sure how the validation is being done.

When I look at the isValidEmailAddress() function in /lib/routes/validators.js, it allows apostrophes in the username part of the email address (parts[0]).

Something else??

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #6702.

@mozilla/fxa-devs r?

### CODE REVIEW

File: app/scripts/lib/validate.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ const unblockCodeRegExp = new RegExp(unblockCodeRegExpStr, 'i');
 //   * http://tools.ietf.org/html/rfc5321#section-4.5.3.1.1
 // '/' in the character class is (redundantly) backslash-escaped to produce
 // the same minimized form in node 4.x and node 0.10.
-const emailRegex = /^[\w.!#$%&’*+\/=?^`{|}~-]{1,64}@[a-z\d](?:[a-z\d-]{0,253}[a-z\d])?(?:\.[a-z\d](?:[a-z\d-]{0,253}[a-z\d])?)+$/i;
+const emailRegex = /^[\w.!#$%&'*+\/=?^`{|}~-]{1,64}@[a-z\d](?:[a-z\d-]{0,253}[a-z\d])?(?:\.[a-z\d](?:[a-z\d-]{0,253}[a-z\d])?)+$/i;
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: !@#% autocorrecting editors!
