### PR TITLE
fix(refresh): adds `Last checked:` as tooltip

### LINKED ISSUE #6043: TOTP: Suggest adding Refresh messaging
It is not entirely clear what the Refresh button does within the MFA Settings. It would be helpful to add a tooltip, or some sort of visible messaging after a user clicks it.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #6043 

- [x]  Update all panels that use `Refresh` to `Refresh Status`
- [x]  Show a tooltip with a synthesized Last update time.
- [x]  Tooltip shows `none` when panel is first opened
- [x]  Tooltip shows `none` when page is refreshed
- [x]  Tooltip shows `time` when refreshed button was clicked (only locally)

WIP for tests

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs No rush on this, r?

File: app/scripts/views/mixins/last-checked-time-mixin.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    if (! date) {
+      date = new Date();
+    }
+    this.lastCheckedTime = date.toLocaleTimeString([], {
+      hour: '2-digit',
+      minute: '2-digit'
+    });
+  },
+
+  _getLastCheckedTimeString() {
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/last-checked-time-mixin.js]: Can you make both of these methods public since they are called by the consumers?

File: app/scripts/views/mixins/last-checked-time-mixin.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    let time = 'none';
+    if (this.lastCheckedTime) {
+      time = this.lastCheckedTime;
+    }
+    return `Last checked: ${time}`;
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/last-checked-time-mixin.js]: This will need to be translated, can you wrap this in the `t` helper function and use the normal string interpolation methods for `time`? `none` needs to be translated too.

File: app/scripts/views/mixins/upgrade-session-mixin.js [hunk 3]
```diff
@@ -95,6 +100,7 @@ define(function (require, exports, module) {
           emailSent: this.model.get('emailSent'),
           gatedHref: options.gatedHref,
           isPanelOpen: this.isPanelOpen(),
+          lastCheckedTime: this._getLastCheckedTimeString(),
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/upgrade-session-mixin.js]: You can add a `setInitialContext` method inside of the mixin that sets only `lastCheckedTime` so that you don't have to add this field to every view that uses it.

**Comment by vbudhram** [comment]
@shane-tomlinson Updated!

File: app/scripts/views/mixins/last-checked-time-mixin.js [hunk 4]
```diff
@@ -21,12 +29,12 @@ const Mixin = {
...
 
-  _getLastCheckedTimeString() {
-    let time = 'none';
+  getLastCheckedTimeString() {
+    let time = t('none');
     if (this.lastCheckedTime) {
       time = this.lastCheckedTime;
     }
-    return `Last checked: ${time}`;
+    return t('Last checked') + `: ${time}`;
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/last-checked-time-mixin.js]: Localizers get a bit twitchy when we do string concatenation to form strings. I'd suggest doing something like:

```js
return this.translate(t('Last checked: %(lastCheckTime)s'), { lastCheckTime: time );
```

File: app/scripts/views/mixins/last-checked-time-mixin.js [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+      minute: '2-digit'
+    });
+  },
+
+  getLastCheckedTimeString() {
+    let time = t('none');
+    if (this.lastCheckedTime) {
+      time = this.lastCheckedTime;
+    }
+    return t('Last checked') + `: ${time}`;
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/last-checked-time-mixin.js]: Localizers get a bit twitchy when we do string concatenation to form strings, sometimes the format is different for their locale. I'd suggest doing something like:

```js
return this.translate(t('Last checked: %(lastCheckTime)s'), { lastCheckTime: time );
```

This way the localizers have control over how to best form that string for their particular locale.

**Comment by vbudhram** [comment]
Thank you!
