### PR TITLE
fix(client): Ensure status messages are shown on the signup page.

### LINKED ISSUE #3402: success/error messages not displayed on signup page
Success and error messages are not being displayed on the signup page like they are on the signin page.

STR

1. Create and verify an account
1. Open the settings page.
1. Delete the account.
1. No success message on the signup page. It should say [Account deleted successfully](https://github.com/mozilla/fxa-content-server/blob/70f2656bdc57a48610231fd29288da11136c05ad/app/scripts/views/mixins/signed-out-notification-mixin.js#L38)

#### No "Account deleted successfully" message on /signup
no-success-message-signup

#### "Signed out successfully" message displayed on /signin

success-message-signin

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Done using better data sandboxing with View models!

`model` is used for current view data. A View's Model data is created and
passed in to the View, based on data sent from the previous View.

`ephemeralMessages` is no more, it was global mutable state. Terrible.

This is being done in conjunction with #3419

fixes #3402

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@philbooth - I want to dot `i`s and cross `t`s w/ the tests, but I think this is ready for another round of your feedback!

File: app/scripts/views/base.js [hunk 1]
```diff
@@ -18,11 +17,7 @@ define(function (require, exports, module) {
   var TimerMixin = require('views/mixins/timer-mixin');
 
   var DEFAULT_TITLE = window.document.title;
-  var EPHEMERAL_MESSAGE_ANIMATION_MS = 150;
-
-  // Share one ephemeral messages across all views. View can be
-  // intialized with an ephemeralMessages for testing.
-  var ephemeralMessages = new EphemeralMessages();
+  var STATUS_MESSAGE_ANIMATION_MS = 150;
```
Comment (shane-tomlinson) [inline app/scripts/views/base.js]: Only a naming fix to stay consistent with `showStatusMessages`

File: app/scripts/views/base.js [hunk 2]
```diff
@@ -253,27 +246,26 @@ define(function (require, exports, module) {
       return 'signin';
     },
 
-    showEphemeralMessages: function () {
-      var success = this.ephemeralMessages.get('success');
+    displayStatusMessages: function () {
```
Comment (shane-tomlinson) [inline app/scripts/views/base.js]: We have `displaySuccess`, `displayError` - `showEphemeralMessages` was the odd one out. It because `displayEphemeralMessages`, then `displayStatusMessages` since `Ephemeral` was a bit of a bunk name.

File: app/scripts/views/base.js [hunk 3]
```diff
@@ -253,27 +246,26 @@ define(function (require, exports, module) {
...
 
-      var error = this.ephemeralMessages.get('error');
+      var error = this.model.get('error');
       if (error) {
         this.displayError(error);
+        this.model.unset('error');
       }
     },
 
-    ephemeralData: function () {
```
Comment (shane-tomlinson) [inline app/scripts/views/base.js]: Replaced by direct `get` on `this.model`.

File: app/scripts/views/base.js [hunk 4]
```diff
@@ -631,31 +623,26 @@ define(function (require, exports, module) {
     },
 
     /**
-     * navigate to another view
+     * navigate to another screen
+     *
+     * @param {string} url - url of screen
+     * @param [{object}] nextViewData - data to pass to the next view
```
Comment (shane-tomlinson) [inline app/scripts/views/base.js]: This JSDoc doesn't follow convention, fix it. `{object} [nextViewData]`

File: app/scripts/views/choose_what_to_sync.js [hunk 5]
```diff
@@ -20,8 +20,7 @@ define(function (require, exports, module) {
 
     initialize: function () {
       // Account data is passed in from sign up flow.
-      var data = this.ephemeralData();
-      this._account = data && this.user.initAccount(data.account);
+      this._account = this.user.initAccount(this.model.get('account'));
```
Comment (shane-tomlinson) [inline app/scripts/views/choose_what_to_sync.js]: Simpler, isn't it?

File: app/scripts/views/confirm_account_unlock.js [hunk 6]
```diff
@@ -94,7 +77,7 @@ define(function (require, exports, module) {
           // the continuation path depends on the action that triggered
           // the account lockout notice. The only time the broker should
           // be notified is if the user was trying to sign in.
-          if (isLockoutSourceSignIn(self._lockoutSource)) {
+          if (isLockoutSourceSignIn(self.model.get('lockoutSource'))) {
```
Comment (shane-tomlinson) [inline app/scripts/views/confirm_account_unlock.js]: Simpler, isn't it?

File: app/scripts/lib/router.js [hunk 7]
```diff
@@ -112,12 +112,19 @@ define(function (require, exports, module) {
...
       this.notifier.on('navigate', this.onNavigate.bind(this));
+      this.notifier.on('navigate-back', this.onNavigateBack.bind(this));
 
       this.storage = Storage.factory('sessionStorage', this.window);
     },
 
-    onNavigate: function (data) {
-      this.navigate(data.url, _.omit(data, 'url'));
+    onNavigate: function (event) {
+      this._nextViewData = event.nextViewData || {};
```
Comment (philbooth) [inline app/scripts/lib/router.js]: Bike-shedding the name: is `nextViewData` or `nextModel` better?

**Comment by philbooth** [comment]
> ...this is ready for another round of your feedback!

I haven't got much to say other than I like it tbh. Looks good, get those i's and t's dotted and crossed! :smile:

File: app/tests/spec/views/app.js [hunk 8]
```diff
@@ -423,6 +426,14 @@ define(function (require, exports, module) {
         assert.isTrue(childView.logView.called);
       });
 
+      it('updates the child\'s model', function () {
+        assert.equal(childView.model.get('new-key'), 'new-value');
+      });
+
+      it('displays the child\'s message', function () {
```
Comment (shane-tomlinson) [inline app/tests/spec/views/app.js]: `message` => `status messages`

File: app/tests/spec/views/confirm_account_unlock.js [hunk 9]
```diff
@@ -69,8 +69,8 @@ define(function (require, exports, module) {
         email: EMAIL
       });
 
-      ephemeralMessages = new EphemeralMessages();
-      ephemeralMessages.set('data', {
+      model = new Backbone.Model();
```
Comment (shane-tomlinson) [inline app/tests/spec/views/confirm_account_unlock.js]: Combine lines 72 and 83

File: app/tests/spec/views/settings/avatar_crop.js [hunk 10]
```diff
@@ -39,7 +39,7 @@ define(function (require, exports, module) {
     var view;
 
     beforeEach(function () {
-      ephemeralMessages = new EphemeralMessages();
+      model = new Backbone.Model();
```
Comment (shane-tomlinson) [inline app/tests/spec/views/settings/avatar_crop.js]: sort order between lines 42 and 43

File: app/tests/spec/views/sub_panels.js [hunk 11]
```diff
@@ -62,6 +63,9 @@ define(function (require, exports, module) {
     beforeEach(function () {
       metrics = new Metrics();
       notifier = new Notifier();
+      parent = {
```
Comment (shane-tomlinson) [inline app/tests/spec/views/sub_panels.js]: Is this needed?

Comment (shane-tomlinson) [inline app/tests/spec/views/sub_panels.js]: Yes, yes it is.

File: app/scripts/views/sub_panels.js [hunk 12]
```diff
@@ -76,6 +77,10 @@ define(function (require, exports, module) {
 
       var view = self._createView(ChildView, {
         el: self.$(selector),
+        // Each child view receives its own model on creation. When
+        // the child view is shown in `showChildView`, it's model
```
Comment (shane-tomlinson) [inline app/scripts/views/sub_panels.js]: This comment is incorrect, the child view's model is updated by app.js before showChildView is called.

**Comment by shane-tomlinson** [comment]
@philbooth - I removed the WIP label, this is ready!

**Comment by philbooth** [comment]
Looks good to me. :+1:
