### PR TITLE
fix(avatars): show a default avatar if a uploaded avatar does not load

### LINKED ISSUE #1804: Better fallback avatar image if remote image cannot be resolved
Found in https://accounts.stage.mozaws.net/ver.json (commit 83ec3798f4f4330981dcfd0b6bde70f3b727020c)

```json
{
  "version": "0.24.0",
  "commit": "83ec3798f4f4330981dcfd0b6bde70f3b727020c",
  "l10n": "bf5bfdbc4b",
  "tosPp": "69110966d5"
}
```

---

### Steps to reproduce:
1. Currently stage is a bit messed up and points to a https://mozillausercontent.com/ domain and is failing to load profile images.
2. Sign in to https://accounts.stage.mozaws.net/settings/avatar and click the [change] link and upload a new avatar.

### Actual results:
Currently, in the oddly configured stage profile server, I'm getting a broken image and the following error message in mein console:

> _"Failed to load resource: net::ERR_NAME_NOT_RESOLVED"_

Not sure if this is possible, but it'd be nice if we could have a nicer experience than a broken image and possibly display the default avatar or an error message or something if we receive a non 200/304 status code from the profile server for an avatar image.

account_picture
**Figure 1:** 13 console errors, but the first 12 all seem to be CSP "Report Only" errors.

### Expected results:

Error message and more pretty broken image experience (perhaps setting the `` tag's background-image style to the default avatar, or whatever).

### PR DESCRIPTION
**Pull request by zaach**
Fixes #1804.

@vladikoff or @shane-tomlinson r?

### CODE REVIEW

File: app/scripts/lib/profile-errors.js [hunk 1]
```diff
@@ -29,6 +29,10 @@ define([
       errno: 103,
       message: t('Image processing error')
     },
+    IMAGE_LOAD_ERROR: {
+      errno: 997,
+      message: t('Unexpected error')
```
Comment (zaach) [inline app/scripts/lib/profile-errors.js]: This string if not displayed to the user, so I opted for no new strings.

File: app/scripts/views/mixins/avatar-mixin.js [hunk 2]
```diff
@@ -50,18 +51,19 @@ define([
...
-            self.$(wrapperClass).addClass('with-default');
+            self.logEvent(self.className + '.profile_image_not_shown');
           }
-          return result;
-        }, function () {
+        })
+        .then(null, function () {
           // Ignore errors; the default image will be shown.
           self.$(wrapperClass).addClass('with-default');
+          self.logEvent(self.className + '.profile_image_not_shown');
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: Can you document these new errors in https://github.com/mozilla/fxa-content-server/blob/master/docs/client-metrics.md?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 3]
```diff
@@ -50,18 +51,19 @@ define([
...
       return this._fetchProfileImage(account)
-        .then(function (result) {
-          if (result && result.avatar) {
-            self.$(wrapperClass).append(new Image());
-            self.$(wrapperClass + ' img').attr('src', result.avatar);
+        .then(function (img) {
+          if (img) {
+            self.$(wrapperClass).append(img);
             self.$(wrapperClass).removeClass('with-default');
+            self.logEvent(self.className + '.profile_image_shown');
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: Can you just do a `self.logScreenEvent('profile_image_shown')`?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 4]
```diff
@@ -50,18 +51,19 @@ define([
...
           } else {
-            self.$(wrapperClass).addClass('with-default');
+            self.logEvent(self.className + '.profile_image_not_shown');
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: If no image is returned, is the default automatically displayed?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 5]
```diff
@@ -17,14 +19,13 @@ define([
       return account.getAvatar()
         .then(function (result) {
           if (result && result.avatar && result.id) {
-            self.logEvent(self.className + '.profile_image_shown');
-          } else {
-            self.logEvent(self.className + '.profile_image_not_shown');
+            return ImageLoader.load(result.avatar);
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: It seems like this section (lines 22-27) should be in their own model. For another PR.

File: app/scripts/views/settings/avatar_change.js [hunk 6]
```diff
@@ -61,7 +54,11 @@ function ($, _, Cocktail, FormView, AvatarMixin, SettingsMixin, Template, AuthEr
 
     remove: function () {
       var self = this;
-      return self.getSignedInAccount().deleteAvatar(self.avatarId)
+      var account = self.getSignedInAccount();
+      return account.getAvatar()
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/avatar_change.js]: Does `getAvatar` mean `get the current avatar`? If so, should the name be updated to reflect its purpose? Can `account.deleteAvatar` be called without the initial call to `account.getAvatar`? I'm asking myself whether the API can be cleaned up a bit.

File: app/scripts/lib/load-profile-image.js [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+], function (p, ImageLoader, ProfileErrors) {
+
+  return function (imgUrl) {
+    return ImageLoader.load(imgUrl)
+      .then(null, function () {
+        return p.reject(ProfileErrors.toError('IMAGE_LOAD_ERROR'));
+      });
+  };
+});
+
```
Comment (zaach) [inline app/scripts/lib/load-profile-image.js]: Ugh ignore this.

**Comment by zaach** [comment]
@shane-tomlinson I started refactoring profile images! It's already a lot cleaner. Still need to clean it up and write tests.

**Comment by shane-tomlinson** [comment]
@zaach - It's 1am!

**Comment by zaach** [comment]
@shane-tomlinson ha, yeah I wasn't going to do that tonight. But feel free to check out the new approach and comment.

**Comment by zaach** [comment]
This has been rebased and updated. /cc @shane-tomlinson

File: app/scripts/models/profile-image.js [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+    fetch: function () {
+      var self = this;
+      if (! self.has('url')) {
+        return p();
+      }
+      return ImageLoader.load(this.get('url'))
+        .then(function (img) {
+          self.set('img', img);
+        }, function () {
+          return p.reject(ProfileErrors.toError('IMAGE_LOAD_ERROR'));
```
Comment (shane-tomlinson) [inline app/scripts/models/profile-image.js]: Should the original error returned by the ImageLoader be saved to the returned error so that it can be logged? Is this error logged eventually?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 9]
```diff
@@ -7,81 +7,58 @@
...
-      return this._fetchProfileImage(account)
-        .then(function (result) {
-          if (result && result.avatar) {
-            self.$(wrapperClass).append(new Image());
-            self.$(wrapperClass + ' img').attr('src', result.avatar);
-            self.$(wrapperClass).removeClass('with-default');
-          } else {
+      return account.fetchCurrentProfileImage(account)
+        .then(function (profileImage) {
+          self.displayedProfileImage = profileImage;
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: `displayedProfileImage` only looks like it is used in [avatar change](https://github.com/mozilla/fxa-content-server/pull/2136/files#diff-4170b02cafae3656dba3a0892df9e0dbR54). Does it make sense to make `displayedProfileImage` a private variable that is only accessed from the `avatar-mixin`, add a `deleteDisplayedAvatar` (or similar) function to avatar-mixin that is called [from avatar change](https://github.com/mozilla/fxa-content-server/pull/2136/files#diff-4170b02cafae3656dba3a0892df9e0dbR54)? I'm trying to think of ways to increase proximity of variable usage here.

Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: You already have a `clearProfileImage` here, but it does not update the account, that is taken care of outside of here. Consolidation possibility?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 10]
```diff
@@ -7,81 +7,58 @@
...
+], function (ProfileImage) {
 
   return {
     initialize: function (options) {
       this.notifications = options.notifications;
     },
 
-    // Attempt to load a profile image from the profile server
-    _fetchProfileImage: function (account) {
+    displayProfileImage: function (account, wrapperClass) {
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: This is always called with an account, could the name be made more clear if called `displayAccountProfileImage`?

File: app/scripts/models/account.js [hunk 11]
```diff
@@ -153,8 +155,28 @@ define([
 
     toPersistentJSON: function () {
       return _.pick(this.attributes, ALLOWED_PERSISTENT_KEYS);
-    }
+    },
 
+    setProfileImage: function (profileImage) {
+      this.set('profileImageUrl', profileImage.get('url'));
+      this.set('profileImageId', profileImage.get('id'));
```
Comment (shane-tomlinson) [inline app/scripts/models/account.js]: Is this used anywhere besides here?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 12]
```diff
@@ -7,81 +7,58 @@
...
       }
 
-      return this._fetchProfileImage(account)
-        .then(function (result) {
-          if (result && result.avatar) {
-            self.$(wrapperClass).append(new Image());
-            self.$(wrapperClass + ' img').attr('src', result.avatar);
-            self.$(wrapperClass).removeClass('with-default');
-          } else {
+      return account.fetchCurrentProfileImage(account)
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: Not for this PR; I feel like a little bit of MVC could be used to make this code clearer. fetchCurrentProfileImage would immediately return a ProfileImageModel. A corresponding ProfileImageView would be created & rendered, by default it renders the default image. When the XHR request finishes, the ProfileImageModel is updated, which notifies the ProfileImageView, which re-renders itself.

**Comment by shane-tomlinson** [comment]
The functional tests are failing at:

> Running: settings
Test main - settings - sign in, go to settings with setting param set to avatar redirects to avatar change page  FAILED on firefox 36.0 on MAC:
CancelError: Timeout reached on main - settings - sign in, go to settings with setting param set to avatar redirects to avatar change page
Error: Timeout reached on main - settings - sign in, go to settings with setting param set to avatar redirects to avatar change page
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:110:15>

**Comment by shane-tomlinson** [comment]
The above test is also failing in master, something we need to dig into.

**Comment by vladikoff** [comment]
> The above test is also failing in master, something we need to dig into.

You probably need to run `bower install` and make sure you have Backbone 1.1.1

**Comment by shane-tomlinson** [comment]
> You probably need to run bower install and make sure you have Backbone 1.1.1

Bingo.

File: app/scripts/models/profile-image.js (hunk 8 above)
Comment (zaach) [inline app/scripts/models/profile-image.js]: Good idea– we could log it here.

**Comment by shane-tomlinson** [comment]
@zaach - seeing a different error with all my deps up to date.

> Test main - settings/avatar - visit gravatar with gravatar set FAILED on firefox 36.0 on MAC:
ScriptTimeout: [POST http://localhost:4444/wd/hub/session/31110813-cf18-4a3e-a99d-14adbc5c4cc7/execute_async / {"script":"return (function (poller, args, timeout, pollInterval, done) {\n\t\t\t\t\t/* jshint evil:true */\n\t\t\t\t\tpoller = new Function(poller);\n\n\t\t\t\t\tvar endTime = Number(new Date()) + timeout;\n\n\t\t\t\t\t(function poll() {\n\t\t\t\t\t\tvar result = poller.apply(this, args);\n\n\t\t\t\t\t\t/*jshint evil:true */\n\t\t\t\t\t\tif (result != null) {\n\t\t\t\t\t\t\tdone(result);\n\t\t\t\t\t\t}\n\t\t\t\t\t\telse if (Number(new Date()) < endTime) {\n\t\t\t\t\t\t\tsetTimeout(poll, pollInterval);\n\t\t\t\t\t\t}\n\t\t\t\t\t\telse {\n\t\t\t\t\t\t\tdone(null);\n\t\t\t\t\t\t}\n\t\t\t\t\t})();\n\t\t\t\t}).apply(this, arguments);","args":["return (function (selector) {\n      /* global document */\n      var match = document.querySelectorAll(selector);\n\n      if (match.length > 1) {\n        throw new Error('Multiple elements matched. Make a more precise selector');\n      }\n\n      return match[0] && match[0].offsetWidth > 0 ? true : null;\n    }).apply(this, arguments);",[".success"],10000,67]}] Timed out waiting for async script result after 10000ms
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Shanes-Retina-MBP.local', ip: '192.168.1.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_31'
Driver info: driver.version: unknown
  at Server._post  <node_modules/intern-geezer/node_modules/leadfoot/Server.js:68:9>
  at ProxiedSession._post  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:57:30>
  at ProxiedSession.Session.executeAsync  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:616:15>
  at <node_modules/intern-geezer/node_modules/leadfoot/helpers/pollUntil.js:83:20>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
  at processImmediate [as _immediateCallback]  <timers.js:330:15>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:172:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:174:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) [as getVisibleText] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:175:12>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:176:12>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:179:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:181:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findById] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:184:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:185:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:188:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:189:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>

**Comment by shane-tomlinson** [comment]
screen shot 2015-04-07 at 20 31 05

File: app/scripts/views/mixins/avatar-mixin.js (hunk 9 above)
Comment (zaach) [inline app/scripts/views/mixins/avatar-mixin.js]: :+1:

File: app/tests/spec/views/mixins/avatar-mixin.js [hunk 13]
```diff
@@ -73,12 +70,24 @@ define([
...
-        view.updateAvatarUrl('url');
-        assert.isTrue(account.has('profileImageUrl'));
-        view.updateAvatarUrl(null);
-        assert.isFalse(account.has('profileImageUrl'));
-        assert.isTrue(user.setAccount.calledWith(account));
-        assert.isTrue(notifications.profileChanged.calledWith({ uid: UID }));
+        sinon.stub(account, 'fetchCurrentProfileImage', function () {
+          return p(new ProfileImage({ url: 'url', id: 'foo' }));
+        });
+        sinon.stub(account, 'deleteAvatar', function () {
```
Comment (shane-tomlinson) [inline app/tests/spec/views/mixins/avatar-mixin.js]: Not for this PR, but is there a difference between `Avatar` and `ProfileImage`? If not, should the names be unified?

**Comment by shane-tomlinson** [comment]
@zaach - aside from logging the error, r+
