### PR TITLE
fix(webchannel): handle errors from Firefox WebChannels

### LINKED ISSUE #3668: Listen for WebChannel errors and report them in Sentry
https://bugzilla.mozilla.org/show_bug.cgi?id=1255302 added some client-side plumbing to report errors in the form of `{ command, messageId, data: { error: { message, stack } } }`.

This issue tracks wiring up `WebChannelReceiver` to report these errors. As before, we don't report successes; as before, the only command that sends a reply is `fxaccounts:can_link_account`.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3668

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson r?

This should handle the error reports (with stacks) that [Kit integrated](https://github.com/mozilla/fxa-content-server/issues/3668) and also handle messages from WebChannel module once this lands: https://bugzilla.mozilla.org/show_bug.cgi?id=1320189

File: app/scripts/lib/channels/receivers/web-channel.js [hunk 1]
```diff
@@ -50,7 +51,23 @@ define(function (require, exports, module) {
       // Ignore events with no `message` field.
       var message = detail.message;
       if (message) {
-        this.trigger('message', message);
+        if (message.error) {
```
Comment (vladikoff) [inline app/scripts/lib/channels/receivers/web-channel.js]: Need to update this 

```
[20:08:48]  <markh>	so yeah, sadly I think we still want that patch, but your error handler will need to handle error being a string (meaning it probably came from WebChannel.jsm) or an object (meaning it came from our module)
[20:09:03]  <vladikoff>	so we got this http://v14d.com/i/58378f10217ca.png from Kit's error catcher, `error` is Object. the other thing is a String
[20:09:17]  <markh>	yeah
[20:09:34]  <markh>	we can't sanely change the repr of WebChannel.jsm errors
```

Comment (vladikoff) [inline app/scripts/lib/channels/receivers/web-channel.js]: > we need to be prepared to handle error as String OR Object

> only because we have that strange exception handler

**Comment by vladikoff** [comment]
Example of Webchannel  with stack error: https://sentry.prod.mozaws.net/operations/content-dev/issues/370016/

**Comment by vladikoff** [comment]
String error example: https://sentry.prod.mozaws.net/operations/content-dev/issues/369829/

File: app/scripts/lib/channels/receivers/web-channel.js [hunk 2]
```diff
@@ -48,12 +49,51 @@ define(function (require, exports, module) {
...
+        reportedError = true;
+      } else if (message.data && message.data.error) {
+        // if it has an error Object that means it is a component error with a stack
+        errorMsg = message.data.error.message;
+        errorStack = message.data.error.stack;
+        reportedError = true;
+      }
+
+      if (reportedError) {
+        this._logger.error('WebChannel error:', errorMsg);
```
Comment (shane-tomlinson) [inline app/scripts/lib/channels/receivers/web-channel.js]: Two comments about this section:

1. Reporting the error is a pretty big side effect when the function name implies the function only checks whether the message contains an error. Can the reporting logic be moved out of here into `receiveMessage` or the function renamed?
2. Before propagating the error message/stack, should the existing of the `errorMsg` and `errorStack` be done?
3. It looks like it's possible for `errorStack` to be `null` if the `if (message.error && _.isString(message.error))` is taken, will that cause any issues on Raven?

**Comment by shane-tomlinson** [comment]
@vladikoff - other than the logging side-effect, this PR works well!

File: app/scripts/lib/channels/receivers/web-channel.js (hunk 2 above)
Comment (vladikoff) [inline app/scripts/lib/channels/receivers/web-channel.js]: >It looks like it's possible for errorStack to be null if the if (message.error && _.isString(message.error)) is taken, will that cause any issues on Raven?

Checked that one, just reports `null`, which is fine 👍

Comment (vladikoff) [inline app/scripts/lib/channels/receivers/web-channel.js]: > Reporting the error is a pretty big side effect when the function name implies the function only checks whether the message contains an error. Can the reporting logic be moved out of here into receiveMessage or the function renamed?

renamed to `_reportCaughtErrors`
