### PR TITLE
fix(metrics): Scrub PII from CSP reports

### LINKED ISSUE #3689: Ensure PII is not logged from CSP reports.
CSP reports contain a `source` field. `source` comes from [`source-file`](https://github.com/mozilla/fxa-content-server/blob/d9ab90c1e29854a30c3464a97154094bdb51b2de/server/lib/routes/post-csp.js#L34) in the CSP report. Clicking on the "manage account" link from about:preferences#sync open the settings page with the user's email address and uid. Ensure PII is scrubbed on the backend when the CSP report is logged.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
CSP reports contain a `source` field. `source` `source-file` in the CSP report.
Clicking on the "manage account" link from about:preferences#sync open the
settings page with the user's email address and uid.

This strips `email` and `uid` from `source` and `referrer` in the report.

fixes #3689

@vladikoff - r?

### CODE REVIEW

File: server/lib/routes/post-csp.js [hunk 1]
```diff
@@ -29,15 +31,35 @@ module.exports = function (options) {
...
       return true;
     }
   };
 };
+
+function stripPIIFromUrl(urlToScrub) {
+  if (! urlToScrub) {
+    return '';
+  }
+  var parsedUrl = url.parse(urlToScrub, true);
```
Comment (vladikoff) [inline server/lib/routes/post-csp.js]: parse might fail here? (because report data is very inconsistent)

File: server/lib/routes.js [hunk 2]
```diff
@@ -30,7 +30,10 @@ module.exports = function (config, i18n) {
     require('./routes/get-client.json')(i18n),
     require('./routes/post-metrics')(),
     require('./routes/post-csp')({
-      path: config.get('csp.reportUri')
+      path: config.get('csp.reportUri'),
+      write: function (entry) {
```
Comment (vladikoff) [inline server/lib/routes.js]: @shane-tomlinson this looks a bit strange here, maybe process.write is default and there is an option to pass your own `.write` instead?

**Comment by vladikoff** [comment]
@shane-tomlinson 2 comments, otherwise looks good 👍

File: server/lib/routes.js (hunk 2 above)
Comment (shane-tomlinson) [inline server/lib/routes.js]: That's a good approach, updating.

**Comment by shane-tomlinson** [comment]
@vladikoff - I made several changes based on your feedback. They ended up being larger than "change a couple lines and merge", mine a re-review?

If r+, I'll squash and merge.

File: server/lib/routes/post-csp.js [hunk 3]
```diff
@@ -29,15 +36,49 @@ module.exports = function (options) {
...
+  if (! urlToScrub || ! _.isString(urlToScrub)) {
+    return '';
+  }
+
+  var parsedUrl;
+
+  try {
+    parsedUrl = url.parse(urlToScrub, true);
+  } catch(e) {
+    //
```
Comment (vladikoff) [inline server/lib/routes/post-csp.js]: empty comment?
