### PR TITLE
fix(metrics): measure when users add or modify their profile picture.

### LINKED ISSUE #2294: Measure when users add or modify their profile picture or display name
Because we want those who manage their passwords more be more engaged in other aspects of the browser, we should measure:
* Which users add or modify their profile picture and display name and how often

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2294.

- [x] Need to add tests for 'change' events.

### CODE REVIEW

File: app/tests/spec/views/settings/avatar_camera.js [hunk 1]
```diff
@@ -197,27 +206,26 @@ function (chai, _, $, sinon, View, RouterMock, WindowMock, CanvasMock,
               view.stream.stop = function () {
                 stopped = true;
               };
-
               view.submit()
-                .then(function (result) {
+                .done(function (result) {
```
Comment (vladikoff) [inline app/tests/spec/views/settings/avatar_camera.js]: the assertions below were not being called in my testing, refactored this a bit.

File: app/scripts/views/settings/avatar_camera.js [hunk 2]
```diff
@@ -148,10 +148,17 @@ function (_, Cocktail, canvasToBlob, FormView, ProgressIndicator,
 
     submit: function () {
       var self = this;
+      var account = self.getSignedInAccount();
+      // if the user already has an image set, then report a change event
+      if (self._hasPreviousProfileImage(account)) {
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/avatar_camera.js]: Since this is repeated 3x, you could just extract the entire thing into avatar-mixin.js `logAvatarChange` or something similar?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 3]
```diff
@@ -67,6 +67,15 @@ define([
       return ! account.has('profileImageUrl');
     },
 
+    _metricsImageChange: function (account) {
+      // if the user already has an image set, then report a change event
+      if (account.has('profileImageId')) {
+        this.logScreenEvent('submit.change');
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: Can you add these new events to [client-metrics.md](https://github.com/mozilla/fxa-content-server/blob/master/docs/client-metrics.md) under the appropriate screens?

File: app/scripts/views/mixins/avatar-mixin.js [hunk 4]
```diff
@@ -67,6 +67,15 @@ define([
       return ! account.has('profileImageUrl');
     },
 
+    _metricsImageChange: function (account) {
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: Maybe just call this `logAccountImageChange`.

**Comment by shane-tomlinson** [comment]
@vladikoff - you mention `Need to add tests for 'change' events.` in the description. I see a [change event test](https://github.com/mozilla/fxa-content-server/pull/2430/files#diff-c749473dd00e0f37191b19d91f4c76faR194). Anything else needed?

File: app/scripts/views/mixins/avatar-mixin.js (hunk 3 above)
Comment (shane-tomlinson) [inline app/scripts/views/mixins/avatar-mixin.js]: If the image change/set fails, is that already logged?

**Comment by vladikoff** [comment]
@shane-tomlinson not ready yet, sorry.

**Comment by vladikoff** [comment]
@shane-tomlinson @zaach r? this should be ready now

File: app/scripts/views/mixins/avatar-mixin.js [hunk 5]
```diff
@@ -67,6 +67,15 @@ define([
       return ! account.has('profileImageUrl');
     },
 
+    logAccountImageChange: function (account) {
+      // if the user already has an image set, then report a change event
+      if (account.has('profileImageId')) {
```
Comment (zaach) [inline app/scripts/views/mixins/avatar-mixin.js]: Let's use `profileImageUrl` instead since there's precedent for using that attribute.

File: app/scripts/views/settings/avatar_change.js [hunk 6]
```diff
@@ -87,6 +87,8 @@ function ($, Cocktail, FormView, AvatarMixin, SettingsMixin, Template,
       var self = this;
       var defer = p.defer();
       var file = e.target.files[0];
+      var account = self.getSignedInAccount();
+      self.logAccountImageChange(account);
```
Comment (zaach) [inline app/scripts/views/settings/avatar_change.js]: If the user cancels out of the file picker, will this still record a change event? Should it?

Comment (vladikoff) [inline app/scripts/views/settings/avatar_change.js]: I'm thinking no. cc @ryanfeeley

File: app/tests/spec/views/settings/avatar_gravatar.js [hunk 7]
```diff
@@ -165,6 +173,29 @@ function (chai, $, sinon, View, RouterMock, ProfileMock, User,
               assert.isTrue(profileClientMock.postAvatar.called);
             });
         });
+
+        it('properly tracks avatar change events', function () {
+          // set the account to have an existing profile image id
+          account.set('profileImageId', 'foo');
```
Comment (zaach) [inline app/tests/spec/views/settings/avatar_gravatar.js]: Same as before, let's use `profileImageUrl` as the heuristic for it being set.

File: app/scripts/views/settings/avatar_change.js (hunk 6 above)
Comment (zaach) [inline app/scripts/views/settings/avatar_change.js]: :+1:  This code only executes if they do select a file, although it could be incompatible. There's also the chance they will bail during the cropper step. Are these concerns?

Tangential, but it would be neat to record how the cropper is used, e.g. rotates, zooms, etc.

Comment (vladikoff) [inline app/scripts/views/settings/avatar_change.js]: Will file an issue for that so we can discuss...

Comment (zaach) [inline app/scripts/views/settings/avatar_change.js]: FIled https://github.com/mozilla/fxa-content-server/issues/2533
