### PR TITLE
fix(tests): adjust code to support IE10

### LINKED ISSUE #2378: Mocha tests fail in IE10
STR

1. Load up IE10
1. Run the mocha tests
1. Wah wah.

It's at least blowing up here:
https://github.com/mozilla/fxa-content-server/blob/99ba218873bcffb6441bba398f5baeb6300f62f2/app/tests/mocks/window.js#L67

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2378 

@shane-tomlinson r?

### CODE REVIEW

File: app/scripts/lib/url.js [hunk 1]
```diff
@@ -76,7 +76,12 @@ function (_) {
         return null;
       }
 
-      var origin = anchor.protocol + '//' + anchor.host;
+      // IE10 always returns port, Firefox and Chrome hide the port if it is the default port e.g 443, 80
+      // We normalize IE10 output, use the hostname if it is a default port to match Firefox and Chrome.
+      // Also IE10 returns anchor.port as String, Firefox and Chrome use Number.
+      var host = Number(anchor.port) === 443 || Number(anchor.port) === 80 ? anchor.hostname : anchor.host;
```
Comment (shane-tomlinson) [inline app/scripts/lib/url.js]: YES! I did almost this exact fix before, how did it not make it into the repo?
