### PR TITLE
fix(metrics): Ensure emailFirst experiment metrics are reported.

### LINKED ISSUE #5397: emailFirst experiment not being reported to DataDog
Now that train-94 is out the door, I went to look at the emailFirst metrics on DataDog. The experiment metrics aren't being reported! The "email_first" screen metrics are though, so far they look pretty decent!

### PR DESCRIPTION
**Pull request by shane-tomlinson**
The problem is `createExperiment` was called without a groupType.

fixes #5397 

@mozilla/fxa-devs - r?

This too is opened against train-94 because I'd like to be able to measure the emailFirst flow.

### CODE REVIEW

File: app/scripts/views/mixins/email-first-experiment-mixin.js [hunk 1]
```diff
@@ -28,14 +28,24 @@ define(function (require, exports, module) {
 
       beforeRender () {
         if (this.isInEmailFirstExperiment()) {
-          this.createExperiment(EXPERIMENT_NAME);
-          if (this.isInEmailFirstExperimentGroup('treatment') && options.treatmentPathname) {
+          const experimentGroup = this.getEmailFirstExperimentGroup();
+          this.createExperiment(EXPERIMENT_NAME, experimentGroup);
```
Comment (vladikoff) [inline app/scripts/views/mixins/email-first-experiment-mixin.js]: 👍
