### PR TITLE
fix(metrics): Fix the "refreshes_metrics" test.

### LINKED ISSUE #4844: failing test: refreshing a screen logs a refresh event - Cannot read property 'reduce' of null
Test name: `refreshing a screen logs a refresh event`
Failing on latest TeamCity

Stack:

> TypeError: Cannot read property 'reduce' of null
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1229:29>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1228:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.refreshing the signup screen [as test]  <tests/functional/refreshes_metrics.js:35:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>

# Code 

```js
return this.parent
      .then(fetchAllMetrics())
      .then(function (metrics) {
        var events = metrics.reduce(function (evts, metrics) {
          var evtsNames = metrics.events.map(function (evt) {
            return evt.type;
```

Ref: https://github.com/mozilla/fxa-content-server/commit/d97948384ff7d0a26bd418cf314b79fa5023e82f

@shane-tomlinson any ideas?

### PR DESCRIPTION
**Pull request by shane-tomlinson**
### What is the problem?
The `_send` function on Metrics.prototype was always being called instead of
the variant on StorageMetrics.prototype.

This happened because `Metrics.initialize` was called during the setup of StorageMetrics' 
prototype chain. `Metrics.initialize` creates `this._flush` by binding `this.flush`
to the current context, which is a Metrics instance at this time. When `this._flush` 
was called, the context was the original Metrics object. `this._flush` would call 
`this._send` on the original object too, because of the context.

### How does this fix it?
Instead of calling `new Metrics()` to set up the prototype chain, copy
over the functions from Metrics' prototype to StorageMetrics' prototype,
then from the StorageMetrics constructor, call the Metrics constructor. It
sets up the prototype chain correctly, and allows functions to bind correctly.

### Why remove the Notifier mock?
App-start passes StorageMetrics a notifier instance, which is then passed
to the Metrics constructor, no need for a mock.

fixes #4844

@vladikoff, @philbooth - r?

### CODE REVIEW

**Comment by philbooth** [comment]
LGTM! 👍

File: tests/intern_functional_circle.js [hunk 1]
```diff
@@ -33,6 +33,7 @@ define([
     'tests/functional/delete_account',
     'tests/functional/reset_password',
     'tests/functional/sync_reset_password',
+    'tests/functional/refreshes_metrics',
```
Comment (vladikoff) [inline tests/intern_functional_circle.js]: 🍰

**Comment by vladikoff** [comment]
Thank you!!
