### PR TITLE
fix(client): Allow the firstrun flow to halt after signin.

### LINKED ISSUE #2945: clicking on 'email prefs' results in blank iframe in firstRun page
1. (i'm on dev edition) goto:  https://www.mozilla.org/en-US/firefox/40.0/firstrun/
2. click on 'communication preferences'
3. click on 'Email preferences'

actual: iframe is blank and i see this:
09:24:32.474 Load denied by X-Frame-Options: https://www.mozilla.org/en-US/newsletter/existing/69d4b10e-8e5e-4f8d-8a38-7b87e4d1b449 does not permit framing.1 <unknown>

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Some settings do not work in an iframe due to x-frame and
same-origin policies. Allow the firstrun flow to decide whether
they want to display the settings page after the `login` message
is sent. If the `haltAfterSignIn` query parameter is set to true,
the flow halts after signin and the firstrun page takes care of
displaying an update to the user.

fixes #2945

@vladikoff, @jpetto and @habber?

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson how do we deploy this without service interruption? 

If firstrun site goes first then it will error with unexpected error?
If content server goes first then users will hang on signin?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson how do we deploy this without service interruption? 

We could create a new broker that uses `context=fx_firstrun_v2`, deploy it, and when that's deployed, have the firstrun team update to the new context.

**Comment by vladikoff** [comment]
> We could create a new broker that uses context=fx_firstrun_v2, deploy it, and when that's deployed, have the firstrun team update to the new context.

:+1:

File: tests/functional/firstrun_sign_in.js [hunk 1]
```diff
@@ -54,11 +54,10 @@ define([
         .then(FunctionalHelpers.testIsBrowserNotified(self, 'fxaccounts:can_link_account'))
         .then(FunctionalHelpers.testIsBrowserNotified(self, 'fxaccounts:login'))
 
-        .findByCssSelector('#fxa-settings-header')
-        .end()
-
-        // user should be unable to sign out.
-        .then(FunctionalHelpers.noSuchElement(self, '#signout'))
+        // A lot of settings do not work in an iframe due to CSP. Do not
```
Comment (shane-tomlinson) [inline tests/functional/firstrun_sign_in.js]: `CSP` and `iframe restrictions`

Comment (vladikoff) [inline tests/functional/firstrun_sign_in.js]: Hm does CSP have to do anything with this though?
Are you thinking `X-Frame-Options`? 

AFAIK CSP is not enabled in any way

Comment (vladikoff) [inline tests/functional/firstrun_sign_in.js]: or `Same-origin policy`? `SOP`?

File: app/scripts/models/auth_brokers/first-run.js [hunk 2]
```diff
@@ -23,7 +23,10 @@ define([
     },
 
     haltAfterResetPasswordConfirmationPoll: false,
-    haltAfterSignIn: false,
+    // A lot of settings do not work in an iframe due to CSP. Do not allow
```
Comment (vladikoff) [inline app/scripts/models/auth_brokers/first-run.js]: also see https://github.com/mozilla/fxa-content-server/pull/3021/files#r38536985

File: app/scripts/models/auth_brokers/first-run.js [hunk 3]
```diff
@@ -23,7 +23,10 @@ define([
...
+    // users to go to the settings page after sign in, let the firstrun flow
+    // take care of displaying some update to the user.
+    haltAfterSignIn: true,
```
Comment (vladikoff) [inline app/scripts/models/auth_brokers/first-run.js]: So as discussed this should be part of first-run-2.js or something (part of v2)

**Comment by jpetto** [comment]
My only concern here is that our long-term desire is likely to be showing the user's avatar and some sort of confirmation message after a successful login, just without any links for them to follow. This post-login redirect was meant to be a short-term fix, and will most likely *not* be our ideal UX on future implementations.

I have no problems with this change for now, as long as it doesn't make the future long-term solution more difficult.

File: tests/functional/firstrun_sign_in.js (hunk 1 above)
Comment (shane-tomlinson) [inline tests/functional/firstrun_sign_in.js]: `csp`=>`x-frame-options`

**Comment by vladikoff** [comment]
> My only concern here is that our long-term desire is likely to be showing the user's avatar and some sort of confirmation message after a successful login, just without any links for them to follow. This post-login redirect was meant to be a short-term fix, and will most likely not be our ideal UX on future implementations.

> I have no problems with this change for now, as long as it doesn't make the future long-term solution more difficult.

Right. In the future versions of this flow we would be using `context=fx_firstrun_v3` or something, I don't see fx_firstrun_v2 making long-term solutions difficult.

**Comment by shane-tomlinson** [comment]
> My only concern here is that our long-term desire is likely to be showing the user's avatar and some sort of confirmation message after a successful login, just without any links for them to follow. 

We could always jump to v3 at that point.

**Comment by shane-tomlinson** [comment]
@vladikoff, @jpetto - an alternative is to continue to use `context=iframe&service=sync`, and add a "short lived" query parameter that indicates the flow should halt after signin. We tell the flow to halt if the query parameter is available. I'd see it working like this:

1. In train N, The content server adds support for the query paramter `haltAfterSignIn=true`. The FirstRunAuthenticationBroker sets [haltAfterSignIn to true]() if the query parameter is available.
1. When train N is released, the firstrun flow adds `haltAfterSignIn=true` to the URL used to open FxA.
1. In train N+1, hard code `haltAfterSignIn: true` in FirstRunAuthenticationBroker, remove support for the `haltAfterSignIn` query parameter.
1. When train N+1 is released, the firstrun flow removes `haltAfterSignIn=true` from the URL used to open FxA.

This is more or less the approach we are taking [with exclude_signup](https://github.com/mozilla/fxa-content-server/issues/2950).

pros:
* no new auth brokers for such a small change.
* context remains the same.
* URL eventually ends up the the same as it is today.

cons:
* Change is universal, anybody in an old browser that creates a new profile will sign in and no transition will happen.
* It's a slow process.

@jpetto, @vladikoff, @rfk - thoughts?

**Comment by jpetto** [comment]
Assuming with `haltAfterSignIn` set to `true` the iframe is blank, I'm not sure we'd want `haltAfterSignIn` hard coded to `true`, as most discussions around a future, long-term solution include showing the user's avatar and some kind of "sign in successful!" message. (Which sounds like a customized/contextual `/settings` page.)

Would it be feasible to keep the `haltAfterSignIn` query parameter until a long-term solution is decided upon? This would keep the change from being universal, and would leave us flexible while larger decisions are made.

**Comment by rfk** [comment]
Longer-term we might consider letting the iframe flow do a device handshake similar to what's described in https://github.com/mozilla/fxa-content-server/issues/2917#issuecomment-137590716, to specify this sort of behaviour dynamically.

**Comment by rfk** [comment]
I'm OK with a context-specific `haltAfterSignIn` query parameter, even if it lives for a few trains while we find a longer-term path forward.  But I think I'm missing some context here, I don't really understand what steps (3) and (4) gain us in https://github.com/mozilla/fxa-content-server/pull/3021#issuecomment-137414483.  What scenario do we avoid by doing it in two phases like that?

**Comment by shane-tomlinson** [comment]
>  What scenario do we avoid by doing it in two phases like that?

The idea is original behavior is completely removed and no longer supported, so ditch it as well as the query parameter.

I now favor either a new auth broker & context or a query parameter that's supported forever. I'm leaning towards the context & auth broker since that is one fewer query parameters to worry about.

**Comment by shane-tomlinson** [comment]
@rfk - could I get an f? or r? I went with `haltAfterSignIn` after our IRC discussion.

File: tests/functional/firstrun_sign_in.js [hunk 4]
```diff
@@ -66,6 +67,31 @@ define([
...
+        })
+
+        .then(FunctionalHelpers.testIsBrowserNotified(self, 'fxaccounts:can_link_account'))
+        .then(FunctionalHelpers.testIsBrowserNotified(self, 'fxaccounts:login'))
+
+        // Some settings do not work in an iframe due to x-frame and
+        // same-origin policies. Allow the firstrun flow to decide whether
+        // they want to display the settings page after the `login` message
+        // is sent. If `haltAfterSignIn` is set to true, the firstrun page
+        // will take care of displaying an update to the user.
```
Comment (rfk) [inline tests/functional/firstrun_sign_in.js]: This comment seems very elaborate and beyond the scope of the test; since this reasoning is already outlined in the code itself, perhaps the corresponding test comment can be a shorter summary like "don't go to settings page if haltAfterSignIn=true".

**Comment by rfk** [comment]
@shane-tomlinson r+ with one comment-related nit.  The other options are not compellingly better, and this seems nicely self-contained.  We can iterate further once it becomes clearer what the long-term requirements will be.

**Comment by vladikoff** [comment]
Rebased against `master`
