### PR TITLE
fix(experiment): fix the token code experiment

### LINKED ISSUE #5912: Token code experiment for Sync throws 'not a function' error
Locally:

http://127.0.0.1:3030/oauth/signin?response_type=code&redirect_uri=https%3A%2F%2Fauth-dev.mozilla.auth0.com%2Flogin%2Fcallback&scope=openid%20profile&state=nqdRw0qba0kJiPYfJDU6XYESgIc2WUKF&client_id=38a6b9b3a65a1871

image

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #5912

### CODE REVIEW

File: app/scripts/lib/experiments/grouping-rules/token-code.js [hunk 1]
```diff
@@ -34,13 +34,21 @@ define(function (require, exports, module) {
...
+
+        // If a clientId was specified but not defined in the rollout configuration, the default
+        // is to disable the experiment for them.
+        return false;
       }
-      const isSync = false; // Issue: https://github.com/mozilla/fxa-content-server/issues/5912
-      if (isSync && this.bernoulliTrial(this.SYNC_ROLLOUT_RATE, subject.uniqueUserId)) {
-        return this.uniformChoice(GROUPS, subject.uniqueUserId);
+
+      if (this.get && this.get('service') === 'Sync') {
```
Comment (vbudhram) [inline app/scripts/lib/experiments/grouping-rules/token-code.js]: I was under the impression that  `this.get` was always available in the model. Added a little extra protection when it is not and defaults the experiment to `false`.

File: app/tests/spec/lib/experiments/grouping-rules/token-code.js [hunk 2]
```diff
@@ -31,10 +31,6 @@ define(function (require, exports, module) {
       });
```
Comment (vladikoff) [inline app/tests/spec/lib/experiments/grouping-rules/token-code.js]: Also need to bring back this test https://github.com/mozilla/fxa-content-server/pull/5913/files#diff-b41a82ac6da6d2b1fad23eefe3f6acd2  right?

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?
