### PR TITLE
fix(oauth): make Chrome for Android able to sign up and sign in via button confirmation

### LINKED ISSUE #6089: Make Chrome for Android work with OAuth and Notes
## Chrome refuses to authenticate Sign up OR Sign in if there is any email polling involved. 

> The policy on the Chrome side for triggering redirects to an app, whether through a custom scheme or an https App Link, is that this action must be triggered by the user, not Javascript.

ref: https://stackoverflow.com/a/41882732

Rough demo of a fix:

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #6089

### CODE REVIEW

File: app/scripts/models/auth_brokers/oauth-redirect.js [hunk 1]
```diff
@@ -68,7 +69,19 @@ define(function (require, exports, module) {
...
+
+          const redirect = Url.updateSearchString(result.redirect, extraParams);
+          const uap = new UserAgent(win.navigator.userAgent);
+
+          const isChromeAndroid = uap.isChromeAndroid();
+          if (isChromeAndroid) {
+            // For OAuth Applications redirection using Chrome Android,
+            // the action must be triggered by the user, not Javascript.
+            // See #6089
+            return redirect;
```
Comment (vladikoff) [inline app/scripts/models/auth_brokers/oauth-redirect.js]: somehow this needs to detect a `afterSignInConfirmationPoll` or `afterSignUpConfirmationPoll` or other polls

Comment (vladikoff) [reply app/scripts/models/auth_brokers/oauth-redirect.js]: if it's not a poll we can just do the old redirect and not show the button

**Comment by vladikoff** [comment]
@shane-tomlinson any better ideas on how to fix this? 

Feel free to add commits if you want

File: app/scripts/models/auth_brokers/oauth-redirect.js (hunk 1 above)
Comment (rfk) [reply app/scripts/models/auth_brokers/oauth-redirect.js]: I wonder if it would be useful to factor this out into a "oauth-redirect-android.js" auth_broker, which might give you a bit of leeway with detecting `afterSignInConfirmationPoll` etc.

File: app/scripts/views/ready.js [hunk 2]
```diff
@@ -82,10 +87,15 @@ define(function (require, exports, module) {
...
         isSync: this.relier.isSync(),
         redirectUri: this.relier.get('redirectUri'),
-        secondaryEmailVerified: this.getSearchParam('secondary_email_verified') || null
+        secondaryEmailVerified: this.getSearchParam('secondary_email_verified') || null,
+        serviceRedirect: this.model.get('serviceRedirect')
       });
     },
 
+    redirectToRelier () {
+      this._window.location.href = this.model.get('serviceRedirect');
```
Comment (shane-tomlinson) [inline app/scripts/views/ready.js]: To ensure the metrics are flushed, you should call `this.navigateAway(this.model.get('serviceRedirect');`. Hopefully Chrome won't block if the location.href happens in a promise, if it does then maybe trigger a `this.metrics.flush()` then update the href.

File: app/scripts/models/auth_brokers/oauth.js [hunk 3]
```diff
@@ -207,7 +210,14 @@ define(function (require, exports, module) {
 
     afterSignInConfirmationPoll (account) {
       return this.finishOAuthSignInFlow(account)
-        .then(() => proto.afterSignInConfirmationPoll.call(this, account));
+        .then((serviceRedirect) => {
+          if (this._isChromeAndroid) {
+            return new NavigateBehavior('signin_confirmed', {serviceRedirect});
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/oauth.js]: The base `oauth` broker is supposed to be generic, I think this logic should probably be moved into `oauth-redirect` or as @rfk suggests, into its own broker.

File: app/scripts/models/auth_brokers/oauth-redirect.js [hunk 4]
```diff
@@ -68,7 +69,19 @@ define(function (require, exports, module) {
           if (result.action) {
             extraParams['action'] = result.action;
           }
-          win.location.href = Url.updateSearchString(result.redirect, extraParams);
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/oauth-redirect.js]: I'm surprised we did this `win.location.href =` here, we should have been delegating to the router, the router would have flushed the metrics and then redirected.

File: tests/functional/oauth_sign_up.js [hunk 5]
```diff
@@ -88,6 +90,58 @@ registerSuite('oauth signup', {
...
+        .then(testElementTextInclude(selectors.SIGNUP.SUB_HEADER, '123done'))
+        .then(testUrlInclude('client_id='))
+        .then(testUrlInclude('state='))
+
+        .then(fillOutSignUp(email, PASSWORD))
+
+        .then(testElementExists(selectors.CONFIRM_SIGNUP.HEADER))
+        .then(openVerificationLinkInSameTab(email, 0))
+
+        // user is immediately redirected
```
Comment (shane-tomlinson) [inline tests/functional/oauth_sign_up.js]: @vladikoff - What does Chrome for Android do here if the user verifies in the same tab and tries to redirect to a special URL? If they ignore the redirect, we'll have to fix this behavior too. 

Chrome for Android redirects when verifying the email address in the same tab using 123done-dev.lcip.org as the relier.

File: tests/functional/oauth_sign_up.js [hunk 6]
```diff
@@ -88,6 +90,58 @@ registerSuite('oauth signup', {
         .then(noEmailExpected(email, 1));
     },
 
+    'signup in Chrome for Android, verify same browser': function () {
```
Comment (shane-tomlinson) [inline tests/functional/oauth_sign_up.js]: I tried adding the same tests in the signin flow, but forget how to force a verification loop.

File: app/scripts/models/auth_brokers/oauth-redirect-chrome-android.js [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+/**
+ * Chrome for Android will not allow the page to redirect
+ * unless its the result of a user action such as a click.
+ *
+ * Instead of redirecting automatically after confirmation
+ * poll, force the user to the /sign(in|up)_complete page
+ * where they can click a "continue" button.
+ */
+
+class OAuthRedirectChromeAndroidBroker extends OAuthRedirectBroker {
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/oauth-redirect-chrome-android.js]: Using a distinct broker made the broker based logic much more self-contained.

File: app/scripts/lib/app-start.js [hunk 8]
```diff
@@ -70,7 +71,7 @@ function Start(options = {}) {
   this._storage = options.storage || Storage;
   this._translator = options.translator;
   this._user = options.user;
-  this._window = options.window || window;
+  this._window = this.window = options.window || window;
```
Comment (shane-tomlinson) [inline app/scripts/lib/app-start.js]: UserAgentMixin is used to read the `forceUA` query param for functional tests, it requires `this.window` rather than `this._window`. To avoid blowing the PR up too much I didn't update `this._window` to `this.window`, that can be a follow on.

**Comment by shane-tomlinson** [comment]
> Feel free to add commits if you want

Added one commit to contain the OAuth broker logic within one module.

**Comment by shane-tomlinson** [comment]
@vladikoff - should this PR be against `train-109` or against `master`? Right now it's against `master`.

File: app/scripts/lib/app-start.js [hunk 9]
```diff
@@ -304,7 +305,11 @@ Start.prototype = {
           context = Constants.FX_DESKTOP_V2_CONTEXT;
         }
       } else if (this._isOAuth()) {
-        context = Constants.OAUTH_CONTEXT;
+        if (this.getUserAgent().isChromeAndroid()) {
```
Comment (vladikoff) [inline app/scripts/lib/app-start.js]: ah yes i spaced out and failed to write this bit.  👍

File: tests/functional/oauth_sign_up.js (hunk 6 above)
Comment (vladikoff) [reply tests/functional/oauth_sign_up.js]: `but forget how to force a verification loop.`

 "SIGNIN_CONFIRMATION_SKIP_FOR_NEW_ACCOUNTS": "false" in auth-server config

File: tests/functional/oauth_sign_in.js [hunk 10]
```diff
@@ -229,7 +235,49 @@ registerSuite('oauth signin', {
...
+    },
+
+    'signin in Chrome for Android, verify same browser': function () {
+      // The `sync` prefix is needed to force signin confirmation.
+      email = TestHelpers.createEmail('sync{id}');
+      return this.remote
+        .then(createUser(email, PASSWORD, {preVerified: true}))
+        .then(openFxaFromRp('signin', {
+          query: {
+            client_id: 'd5d74070a481bc10', // eslint-disable-line camelcase
```
Comment (vladikoff) [inline tests/functional/oauth_sign_in.js]: Update this to match prod client_id

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 100b10e592a26c28d541bd01787b4f26288ce090
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d64d9313da8e2310474bbdb850f240d9c7afcf4c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
@vladikoff - have you merged train-109 back to master?
