### PR TITLE
fix(devices): Add the 1800 ms artificial delay when clicking `Refresh`

### LINKED ISSUE #4570: Add artificial delay to the "Refresh" button in the devices view
@ryanfeeley said that we need to keep the button spinning for a bit - 1800ms

### LINKED ISSUE #5071: flaky functional test on circle - settings clients - device and apps panel works with query param, same device
I've seen this several times today: https://circleci.com/gh/mozilla/fxa-content-server/6961#tests/containers/1

> × firefox on any platform - settings clients - device and apps panel works with query param, same device (3.232s)
StaleElementReference: [GET http://localhost:4444/wd/hub/session/7547b96e-2dff-4312-a540-9952964e0105/element/649/text] The element reference of <div class="client-name"> stale: either the element is no longer attached to the DOM or the page has been refreshed
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-117-generic', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.ub55h506yT02, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=3.13.0-117-generic, moz:processID=22306.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
Session ID: afffbddf-3157-4a61-a2b9-b15eaacd65c4
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._get  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at Element._get  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.getVisibleText  <node_modules/intern/node_modules/leadfoot/Element.js:233:21>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as getVisibleText]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1459:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:489:9>
  at process._tickCallback  <node.js:418:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.device and apps panel works with query param, same device [as test]  <tests/functional/settings_clients.js:127:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:489:9>
  at process._tickCallback  <node.js:418:13>

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Done by having the progress indicator decorator look on the target element
for a `data-min-progress-indicator-ms` attribute. If it exists, wait for
the time to elapse before completing the submit action.

Use this in the "settings clients" functional tests to ensure the refresh
has completed to continue with the tests.

fixes #4570
fixes #5071 

@vbudhram, @philbooth - mind an r?

### CODE REVIEW

File: app/scripts/views/settings/clients.js [hunk 1]
```diff
@@ -46,7 +47,6 @@ define(function (require, exports, module) {
         });
       }
 
-      this.listenTo(this._attachedClients, 'add', this._onItemAdded);
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/clients.js]: We always call `render` when refreshing the attachedClients list anyways, no need to re-render because of this. re-rendering every time an item was added also caused the `submit` button to be redrawn w/o the progress indicator. Bad jiji.

File: app/scripts/views/settings/clients.js [hunk 2]
```diff
@@ -202,17 +200,28 @@ define(function (require, exports, module) {
       });
     },
 
+    logRefresh () {
+      this.logViewEvent('refresh');
+    },
+
     submit () {
       if (this.isPanelOpen()) {
-        this.logViewEvent('refresh');
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/clients.js]: This was a bug before because `refresh` would be logged any time the view was rendered instead of on a refresh click.

File: app/scripts/views/settings/clients.js [hunk 3]
```diff
@@ -178,7 +176,7 @@ define(function (require, exports, module) {
     openPanel () {
       this.logViewEvent('open');
       // manually submit using an element to trigger the progress indicator mixin
-      this.$el.find('.clients-refresh').trigger('submit');
+      return this.validateAndSubmit();
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/clients.js]: Instead of involving the DOM, we can just call `validateAndSubmit` which does the exact same thing and makes testing a heck of a lot easier.

**Comment by shane-tomlinson** [comment]
I'd like to show the behavior to @ryanfeeley before merge, just to make sure.

**Comment by ryanfeeley** [comment]
@shane-tomlinson How does it *feel*?

File: app/scripts/views/decorators/progress_indicator.js [hunk 4]
```diff
@@ -25,26 +25,32 @@ define(function (require, exports, module) {
     return deferred.promise;
   }
 
-  function showProgressIndicator(handler, _el, delayMills) {
-    var el = _el || 'button[type=submit]';
-    const delayHandlerByMills = delayMills || 0;
+  function showProgressIndicator(handler, el = 'button[type=submit]', delayHandlerByMills = 0) {
+    return function (...args) {
+      const target = this.$(el);
+      const minProgressIndicatorMs = parseInt(target.data('minProgressIndicatorMs') || 0, 10);
```
Comment (vbudhram) [inline app/scripts/views/decorators/progress_indicator.js]: nit: I figured it was the radix but had to look it up to be sure. Maybe make a constant to save future self the lookup? Possibly `RADIX`?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - here's what it looks like:

refresh-devices-button

File: app/scripts/views/settings/clients.js [hunk 5]
```diff
@@ -98,9 +98,11 @@ define(function (require, exports, module) {
 
     events: {
       'click .client-disconnect': preventDefaultThen('_onDisconnectClient'),
+      'click .clients-refresh': 'logRefresh',
       'click [data-get-app]': '_onGetApp'
     },
 
+
```
Comment (vbudhram) [inline app/scripts/views/settings/clients.js]: nit: Extra space

File: app/scripts/templates/settings/clients.mustache [hunk 6]
```diff
@@ -75,7 +75,7 @@
       </ul>
 
       <div class="button-row">
-        <button type="submit" class="settings-button primary clients-refresh">{{#t}}Refresh{{/t}}</button>
+        <button type="submit" class="settings-button primary clients-refresh" data-min-progress-indicator-ms="1800">{{#t}}Refresh{{/t}}</button>
```
Comment (vbudhram) [inline app/scripts/templates/settings/clients.mustache]: Original issue mentioned matching hamburger sync spinner delay which is 1600ms. @ryanfeeley should this be 1600 or 1800ms?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Looks great! I'd like to keep the section closed and puts the loading spinner on the **Show** button until the content is ready, but that's another issue.

File: app/scripts/templates/settings/clients.mustache (hunk 6 above)
Comment (shane-tomlinson) [inline app/scripts/templates/settings/clients.mustache]: I changed it to 1600 since that's what @ryanfeeley specified in that original bug. Thanks for catching this!

**Comment by philbooth** [comment]
Late to the party sorry, but fwiw I am also r+.
