### PR TITLE
fix(validation): Add validation to optional params in models and reliers

### LINKED ISSUE #2025: OAuth parameters should all be validated
#1982 starts by validating the scope and client_id. @ckarlof points out in https://github.com/mozilla/fxa-content-server/issues/1950#issuecomment-66709177 that we should validate the `email` parameter as well. #2019 adds `forceEmail`. #1950 is going to add some other (name t.b.d.) field.

We should validate all RP provided input, whether displayed to the user or not.

### LINKED ISSUE #3452: Guard against empty redirectURI in oauth client config
Over in https://github.com/mozilla/fxa-oauth-server/issues/384 we saw an OAuth relier whose redirectURI was the empty string, and it caused us to get into a weird state trying to redirect to ourselves.  While this *should* never happen, it seems worth putting in a bit of defensive programming around the oauth client config to ensure we can give good error messages if it does.

### LINKED ISSUE #3490: 500 error if `keys` is not true or false - different to other invalid query params
STR

1. Load up the local dev OAuth app 123done
1. Click "sign in"
1. Edit the URL to add a `&keys=asdf`
1. Hit enter
1. Watch the page 500.

An error in the console is printed `keys must be true or false`.

Other invalid OAuth parameters send the user to the [`BAD_REQUEST_PAGE` and show the error which item was invalid](https://github.com/mozilla/fxa-content-server/blob/cc21d5464a30f19fc0c288b7de94fa803f450bbb/app/scripts/lib/app-start.js#L637:L653).

We should go for consistency.

### PR DESCRIPTION
**Pull request by vbudhram**
This PR adds extra validation to oauth and relier models. It guards against invalid emails and urls used in parameters.

Fixes #3452, Fixes #2025, Fixes #3490  

@vladikoff @shane-tomlinson r?

### CODE REVIEW

File: app/scripts/lib/validate.js [hunk 1]
```diff
@@ -13,6 +13,11 @@ define(function (require, exports, module) {
   // taken from the fxa-auth-server
   var HEX_STRING = /^(?:[a-fA-F0-9]{2})+$/;
 
+  // URL RegEx taken from http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without
```
Comment (vladikoff) [inline app/scripts/lib/validate.js]: should this be moved into https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/url.js

File: app/scripts/lib/validate.js [hunk 2]
```diff
@@ -146,6 +151,15 @@ define(function (require, exports, module) {
...
       });
+    },
+
+    /**
+     * Check whether string is a url. Validates url with or without http(s) and trailing slash.
+     *
+     * http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without
+     */
+    isUrlValid: function isUrlValid (url){
+      return urlRegEx.test(url);
```
Comment (vladikoff) [inline app/scripts/lib/validate.js]: will this work for `urn` redirect uris https://github.com/mozilla/fxa-content-server/blob/7d8c2c0661c4492895d39cc10ebcbd602f4bf596/app/tests/spec/views/ready.js#L178 ?

File: app/tests/spec/lib/validate.js [hunk 3]
```diff
@@ -241,5 +241,25 @@ define(function (require, exports, module) {
...
     });
+
+    describe('isUrlValid', function () {
+      it('is defined', function () {
+        assert.isFunction(Validate.isUrlValid);
+      });
+
+      var invalidURLs = ['', {}, true, 1, 'asdf', 'http:://invalid.url'];
+      invalidURLs.forEach( function (item) {
+        it('returns false for ' + item, function () {
```
Comment (vbudhram) [inline app/tests/spec/lib/validate.js]: How do you guys feel about dynamic tests? Grep still works with these.

File: app/scripts/lib/validate.js (hunk 1 above)
Comment (vbudhram) [inline app/scripts/lib/validate.js]: will do!

File: app/scripts/lib/validate.js (hunk 2 above)
Comment (vbudhram) [inline app/scripts/lib/validate.js]: It would fail for the `urn`, will update to validate this. When does the `redirectUri` get set in the Sync Relier? Am I looking in right spot?

https://github.com/mozilla/fxa-content-server/blob/7d8c2c0661c4492895d39cc10ebcbd602f4bf596/app/scripts/models/reliers/sync.js#L38

Comment (rfk) [inline app/scripts/lib/validate.js]: Sync doesn't use OAuth, I don't think it should have a `redirectUri`

File: app/scripts/models/reliers/relier.js [hunk 4]
```diff
@@ -96,11 +97,15 @@ define(function (require, exports, module) {
...
           // A relier can indicate they do not want to allow
           // cached credentials if they set email === 'blank'
-          if (self.getSearchParam('email') ===
-              Constants.DISALLOW_CACHED_CREDENTIALS) {
+          var email = self.getSearchParam('email');
+          if (email === Constants.DISALLOW_CACHED_CREDENTIALS) {
             self.set('allowCachedCredentials', false);
-          } else {
-            self.importSearchParam('email');
+          } else if (email){
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: nit: space between `)` and `{`

File: app/scripts/lib/validate.js (hunk 2 above)
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: Do we already have URL parsing magic somewhere?

Comment (vbudhram) [inline app/scripts/lib/validate.js]: @rfk the relier in vlad's link is created [here](https://github.com/mozilla/fxa-content-server/blob/7d8c2c0661c4492895d39cc10ebcbd602f4bf596/app/tests/spec/views/ready.js#L32), appears to be Sync based and uses redirectUri. Is this correct? Should it be using an `urn` as the `redirectUri`

@shane-tomlinson I looked but couldn't find in project.

Comment (rfk) [inline app/scripts/lib/validate.js]: Incidentally, you can find some more real-life `urn` values here: https://github.com/mozilla/fxa-oauth-server/blob/master/config/dev.json#L44

I'm no expert in this part of the code, but I suspect those tests are using instances of `SyncRelier` out of convenience, and some of them could be refactored to use `OAuthRelier`.  Certainly `OAuthRelier` is the only relier subclass that explicitly lists `redirectUri` among its default fields.

File: app/scripts/lib/validate.js [hunk 5]
```diff
@@ -13,6 +13,38 @@ define(function (require, exports, module) {
...
+  var urnRegEx = /^urn:[a-zA-Z0-9][a-zA-Z0-9-]{1,31}:([a-zA-Z0-9()+,.:=@;$_!*'-]|%[0-9A-Fa-f]{2})+$/;
+
+  /**
+   * Check whether string is a url. Validates url with or
+   * without http(s) and trailing slash.
+   *
+   * http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without
+   */
+  function isUrlValid (url) {
+    return urlRegEx.test(url);
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: You might be able to use [Window.URL](https://developer.mozilla.org/en-US/docs/Web/API/Window/URL). If the URL is not valid, the [constructor throws a TypeError](https://url.spec.whatwg.org/#constructors).

File: app/scripts/lib/validate.js [hunk 6]
```diff
@@ -13,6 +13,38 @@ define(function (require, exports, module) {
   // taken from the fxa-auth-server
   var HEX_STRING = /^(?:[a-fA-F0-9]{2})+$/;
 
+  // URL RegEx taken from http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without
+  // jscs:disable maximumLineLength
+  var urlRegEx = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)/;
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: I feel like for the redirect_uri, we should be as strict as possible w.r.t. the protocol. The redirect_uri should be restricted to `http`, `https` and of course, urns are valid too.

@vladikoff - does the OAuth server accept redirect_uri's w/o a protocol?

File: app/scripts/models/reliers/oauth.js [hunk 7]
```diff
@@ -140,10 +146,10 @@ define(function (require, exports, module) {
       self._importRequiredSearchParam('client_id', 'clientId');
       self._importRequiredSearchParam('scope', 'scope');
       self.importSearchParam('state');
-      self.importSearchParam('redirect_uri', 'redirectUri');
+      self._importValidateOptionalSearchParam('redirect_uri', 'redirectUri', Validate.isUriValid);
       self.importSearchParam('access_type', 'accessType');
-      self.importSearchParam('redirectTo');
-      self.importSearchParam('verification_redirect', 'verificationRedirect');
+      self._importValidateOptionalSearchParam('redirectTo', 'redirectTo', Validate.isUriValid);
+      self._importValidateOptionalSearchParam('verification_redirect', 'verificationRedirect', Validate.isUriValid);
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: Not for this PR, but it's really beginning to seem like this could be done in a declarative fashion:

```js
importSearchParams: {
   client_id: 'clientId',
   scope: 'scope',
   state: {
     dest: 'state',
     optional: true
   },
   redirect_uri: {
     dest: 'redirectUri',
     validation: Validate.isUriValid
   },
   ....
}
```

File: app/scripts/models/reliers/oauth.js [hunk 8]
```diff
@@ -157,6 +163,21 @@ define(function (require, exports, module) {
...
 
+    _importValidateOptionalSearchParam: function (sourceName, destName, validateFunc){
+      var self = this;
+      var sourceValue = self.getSearchParam(sourceName);
+      // Only validate if param is in window.location
+      if (sourceValue){
+        if (validateFunc(sourceValue)){
+          self.importSearchParam(sourceName, destName);
+        } else {
+          var err = OAuthErrors.toError('INVALID_PARAMETER');
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: Other than the OAuth specific error code, this function makes sense on the base relier so it can be used by others.

File: app/tests/spec/lib/validate.js (hunk 3 above)
Comment (shane-tomlinson) [inline app/tests/spec/lib/validate.js]: :+1:

File: app/scripts/lib/validate.js (hunk 5 above)
Comment (vbudhram) [inline app/scripts/lib/validate.js]: Cool, didn't know about the Window.URL class. I tested it and it fails for `www.firefox.com`. Should we support this type of url?

File: app/scripts/lib/validate.js (hunk 6 above)
Comment (vladikoff) [inline app/scripts/lib/validate.js]: @shane-tomlinson it accepts any string at the moment, length of 256: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/authorization.js#L104

**Comment by vbudhram** [comment]
@shane-tomlinson moved validation function to base relier. Could review again at your convenience?

File: app/scripts/lib/validate.js [hunk 9]
```diff
@@ -13,6 +13,38 @@ define(function (require, exports, module) {
...
+   * http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without
+   */
+  function isUrlValid (url) {
+    return urlRegEx.test(url);
+  }
+
+  /**
+   * Check if string is valid urn per RFC 2141.
+   */
+  function isUrnValid (urn) {
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: Super nit, all the other exported functions live on module.exports. Can you move these there for consistency?

File: app/scripts/models/reliers/relier.js [hunk 10]
```diff
@@ -106,6 +106,33 @@ define(function (require, exports, module) {
     },
 
     /**
+     * Set a value based on a value in window.location.search. Only updates
+     * model if parameter exists in window.location.search and passes validation.
+     *
+     * Throws Error mapped to `INVALID_PARAMETER` in Errors object.
+     *
+     * @param {String} sourceName - name of the search parameter
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: You found an inconsistent convention - Can you lowercase the type in the jsdoc unless it's things like `Errors` where it's an internal type?

**Comment by shane-tomlinson** [comment]
With manual testing, I see unexpected behavior. With most validation errors we send users to the 400 page and display which parameter was invalid. Errors here cause a 500 page to be displayed. It looks like [scripts/lib/app-start.js->_getErrorPage](https://github.com/mozilla/fxa-content-server/blob/3fdef3feb9403585011ef633ad2cbb81859dc01b/app/scripts/lib/app-start.js#L637) must be updated to handle the [INVALID_PARAMETER](https://github.com/mozilla/fxa-content-server/pull/3469/files#diff-dd944e370ae0feb16340264c6c0f14acR128) error. I'm surprised we never threw this before!

The OAuth functional are not passing locally, starting with the below error:

> × firefox on any platform - oauth sign up verification_redirect - signup, same browser same window, verification_redirect=always (30.01s)
CancelError: Timeout reached on firefox on any platform - oauth sign up verification_redirect - signup, same browser same window, verification_redirect=always
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout  <timers.js:92:15>

The OAuth tests are not run in CI. The tests may very well need to be updated to pass the expected parameters, or to pass valid data.

File: app/scripts/models/reliers/relier.js [hunk 11]
```diff
@@ -106,6 +106,33 @@ define(function (require, exports, module) {
...
+     * @param {String} destName - name to set in model
+     * @param {Function} validateFunc - validation function, returns `true` or `false`
+     * @param {Errors} Errors - corresponding Errors object
+     * @throws {Error}
+     */
+    _importValidateOptionalSearchParam: function (sourceName, destName, validateFunc, Errors) {
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: Since this is used by subclasses, can you remove the `_` prefix?

Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: As an aside, this is probably an opportune moment to push down [_importRequiredSearchParam](https://github.com/mozilla/fxa-content-server/blob/0c84ed2695abf0411c875aa499f61be38e191464/app/scripts/models/reliers/oauth.js#L150) from oauth.js to relier.js (removing the `_` prefix too!)

File: app/scripts/models/reliers/oauth.js [hunk 12]
```diff
@@ -140,10 +146,10 @@ define(function (require, exports, module) {
       self._importRequiredSearchParam('client_id', 'clientId');
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: What do you think about validating `client_id`, `access_type`, and possibly `scope` as part of this work?

`state` is supposed to be opaque to us, so ignore that. If we whitelist what is allowed in `scope`, then we'll have to change that validation logic every time a new scope is possible. I'm not sure if we want to deal with that. @rfk?

`access_type` can only be `online` and `offline`.

`client_id` - if the format is a constant, we should validate it.

File: app/scripts/models/reliers/oauth.js [hunk 13]
```diff
@@ -140,10 +146,10 @@ define(function (require, exports, module) {
...
       self._importRequiredSearchParam('scope', 'scope');
       self.importSearchParam('state');
-      self.importSearchParam('redirect_uri', 'redirectUri');
+      self._importValidateOptionalSearchParam('redirect_uri', 'redirectUri', Validate.isUriValid, OAuthErrors);
       self.importSearchParam('access_type', 'accessType');
-      self.importSearchParam('redirectTo');
-      self.importSearchParam('verification_redirect', 'verificationRedirect');
+      self._importValidateOptionalSearchParam('redirectTo', 'redirectTo', Validate.isUriValid, OAuthErrors);
+      self._importValidateOptionalSearchParam('verification_redirect', 'verificationRedirect', Validate.isUriValid, OAuthErrors);
       self.importBooleanSearchParam('keys');
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: Huh, if `keys` is not `true` or `false`, then a 500 will occur. That doesn't seem right. We cause the same 400 behavior.

File: app/scripts/models/reliers/oauth.js [hunk 14]
```diff
@@ -140,10 +146,10 @@ define(function (require, exports, module) {
       self._importRequiredSearchParam('client_id', 'clientId');
       self._importRequiredSearchParam('scope', 'scope');
       self.importSearchParam('state');
-      self.importSearchParam('redirect_uri', 'redirectUri');
+      self._importValidateOptionalSearchParam('redirect_uri', 'redirectUri', Validate.isUriValid, OAuthErrors);
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: We also need to validate `redirectUri` on line 174, that's what caused #3452.

File: app/scripts/lib/validate.js (hunk 5 above)
Comment (vbudhram) [inline app/scripts/lib/validate.js]: mtg: keep for now

File: app/scripts/lib/validate.js (hunk 9 above)
Comment (vbudhram) [inline app/scripts/lib/validate.js]: Yea, I originally did that because I wanted to be able to reference other functions within the `module.exports` but couldn't unless the function was outside exports. What are your thoughts on me exporting a variable that contains all the functions, that way it could self reference?

File: app/scripts/models/reliers/relier.js (hunk 10 above)
Comment (vbudhram) [inline app/scripts/models/reliers/relier.js]: Fixed

File: app/scripts/models/reliers/relier.js (hunk 11 above)
Comment (vbudhram) [inline app/scripts/models/reliers/relier.js]: Fixed and Fixed :)

File: app/scripts/models/reliers/oauth.js (hunk 14 above)
Comment (vbudhram) [inline app/scripts/models/reliers/oauth.js]: It seems like I need to make the validation functionality a little bit more flexible so that it can be used for more than just search params. Something like [Joi](https://github.com/hapijs/joi) but maybe more compact. Or it might be possible to extend [isDataValid](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/validate.js#L125) to support testing for values?

File: app/scripts/lib/validate.js (hunk 5 above)
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: Yup, there is a reason I haven't used window.URL before, I just can't remember what it is.

File: app/scripts/lib/validate.js (hunk 6 above)
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: Thanks @vladikoff - @rfk and I had a chat today about tightening up the requirements for a `redirect_uri` until specifically requested. A reasonable base level restriction is to require either `https://` and `urn:` unless running locally. We can loosen the restriction if required. This would require updates to the oauth server and possibly oauth console.

@vbudhram - keep what you have now, I opened https://github.com/mozilla/fxa-oauth-server/issues/388 and we can update the content server when that issue is handled.

File: app/scripts/lib/validate.js (hunk 9 above)
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: That's what I thought. What you suggest works, so does this:

```diff
diff --git a/app/scripts/lib/validate.js b/app/scripts/lib/validate.js
index 9ed9fe8..9da17f6 100644
--- a/app/scripts/lib/validate.js
+++ b/app/scripts/lib/validate.js
@@ -21,30 +21,6 @@ define(function (require, exports, module) {
   // URN Regex
   var urnRegEx = /^urn:[a-zA-Z0-9][a-zA-Z0-9-]{1,31}:([a-zA-Z0-9()+,.:=@;$_!*'-]|%[0-9A-Fa-f]{2})+$/;
 
-  /**
-   * Check whether string is a url. Validates url with or
-   * without http(s) and trailing slash.
-   *
-   * http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without
-   */
-  function isUrlValid (url) {
-    return urlRegEx.test(url);
-  }
-
-  /**
-   * Check if string is valid urn per RFC 2141.
-   */
-  function isUrnValid (urn) {
-    return urnRegEx.test(urn);
-  }
-
-  /**
-   * Check if string is valid uri.
-   */
-  function isUriValid (uri) {
-    return isUrlValid(uri) || isUrnValid(uri);
-  }
-
   module.exports = {
     /**
      * Check if an email address is valid
@@ -180,9 +156,30 @@ define(function (require, exports, module) {
       });
     },
 
-    isUrlValid: isUrlValid,
-    isUrnValid: isUrnValid,
-    isUriValid: isUriValid
+    /**
+     * Check whether string is a url. Validates url with or
+     * without http(s) and trailing slash.
+     *
+     * http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without
+     */
+    isUrlValid: function (url) {
+      return urlRegEx.test(url);
+    },
+
+    /**
+     * Check if string is valid urn per RFC 2141.
+     */
+    isUrnValid: function (urn) {
+      return urnRegEx.test(urn);
+    },
+
+    /**
+     * Check if string is valid uri.
+     */
+    isUriValid: function (uri) {
+      var self = module.exports;
+      return self.isUrlValid(uri) || self.isUrnValid(uri);
+    }
   };
 });
```

File: app/scripts/models/reliers/oauth.js (hunk 13 above)
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: Opened #3490 about inalid `keys` being handled differently to other OAuth params.

File: app/scripts/models/reliers/oauth.js (hunk 14 above)
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: > It seems like I need to make the validation functionality a little bit more flexible so that it can be used for more than just search params. Something like Joi but maybe more compact. Or it might be possible to extend isDataValid to support testing for values?

This is almost the exact conversation @philbooth and I had, which is where `isDataValid` came from. We even looked at using joi in the browser (it seems possible, though we didn't try it). 

I want to move in that direction, though not in this PR. Let's keep this in mind and figure out a good declarative way of importing, renaming and validating.

File: app/scripts/lib/validate.js (hunk 9 above)
Comment (vbudhram) [inline app/scripts/lib/validate.js]: I like your way better lol, fixed.

File: app/scripts/models/reliers/oauth.js (hunk 12 above)
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: > client_id - if the format is a constant, we should validate it.

According to @rfk, the format is constant. We should validate it.

File: app/scripts/models/reliers/oauth.js (hunk 14 above)
Comment (vbudhram) [inline app/scripts/models/reliers/oauth.js]: Agreed, I will add validation for line 174 for now. Apparently Joi for browser could be between [32KB - 128KB](https://github.com/hapijs/joi/issues/528) gzipped. Not sure if that is a deal breaker.

**Comment by vbudhram** [comment]
@shane-tomlinson when you get a chance can you r? Thanks!

File: app/scripts/lib/app-start.js [hunk 15]
```diff
@@ -636,6 +636,7 @@ define(function (require, exports, module) {
 
     _getErrorPage: function (err) {
       if (OAuthErrors.is(err, 'MISSING_PARAMETER') ||
+          OAuthErrors.is(err, 'INVALID_PARAMETER') ||
```
Comment (shane-tomlinson) [inline app/scripts/lib/app-start.js]: @vbudhram - I added this line. We didn't throw any INVALID_PARAMETER errors previously, so this needed to be added.

Comment (vbudhram) [inline app/scripts/lib/app-start.js]: Good catch!

File: app/scripts/models/reliers/relier.js [hunk 16]
```diff
@@ -109,6 +109,54 @@ define(function (require, exports, module) {
...
+     *
+     * Throws Error mapped to `INVALID_PARAMETER` in Errors object.
+     *
+     * @param {string} sourceName - name of the search parameter
+     * @param {String} destName - name to set in model
+     * @param {function} validateFunc - validation function, returns `true` or `false`
+     * @param {Errors} Errors - corresponding Errors object
+     * @throws {error}
+     */
+    importValidateOptionalSearchParam: function (sourceName, destName, validateFunc, Errors) {
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: It doesn't look like this is used anymore, might as well take it out.

```bash
➜  scripts git:(issue-3452-validate-oauth-params) rgrep "importValidateOptionalSearchParam" .
./models/reliers/relier.js:    importValidateOptionalSearchParam: function (sourceName, destName, validateFunc, Errors) {
```

File: app/scripts/models/reliers/relier.js [hunk 17]
```diff
@@ -109,6 +109,54 @@ define(function (require, exports, module) {
...
+     *
+     * @param {string} sourceName - name of the search parameter
+     * @param {string} destName - name to set in model
+     * @param {Errors} Errors - corresponding Errors object
+     * @throws {error}
+     */
+    importRequiredSearchParam: function (sourceName, destName, Errors) {
+      var self = this;
+      self.importSearchParam(sourceName, destName);
+      if (! self.has(destName)) {
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: If `self.has` is changed to `self.get`, then this is pretty much identical to the version in [reliers/oauth.js](https://github.com/mozilla/fxa-content-server/pull/3469/files#diff-ca4d7096469c2a76694bb8214760cbaaR187). We should update the `has` to `get` here and use this version everywhere.

File: app/scripts/models/reliers/relier.js (hunk 16 above)
Comment (vbudhram) [inline app/scripts/models/reliers/relier.js]: Yup you are correct, will remove.

File: app/scripts/models/reliers/oauth.js [hunk 18]
```diff
@@ -208,5 +285,19 @@ define(function (require, exports, module) {
...
 
+  function toInvalidParameterError(param) {
+    return toOAuthParameterError('INVALID_PARAMETER', param);
+  }
+
+  function toMissingParameterError(param) {
+    return toOAuthParameterError('MISSING_PARAMETER', param);
+  }
+
+  function toOAuthParameterError(type, param) {
```
Comment (vbudhram) [inline app/scripts/models/reliers/oauth.js]: :+1:

**Comment by vbudhram** [comment]
@shane-tomlinson Took a shot at resolving this merge conflict, but I think I might need some help. Maybe tomorrow?

**Comment by rfk** [comment]
A meta note: I changed the issue description from "Fixes #3452, #2025" to "Fixes #3452, Fixes #2025" and it made waffle link the PR properly to both issue cards.

File: app/scripts/lib/oauth-errors.js [hunk 19]
```diff
@@ -47,7 +47,7 @@ define(function (require, exports, module) {
       errno: 108,
       message: t('Invalid token')
     },
-    INVALID_REQUEST_PARAMETER: {
+    INVALID_PARAMETER: {
```
Comment (shane-tomlinson) [inline app/scripts/lib/oauth-errors.js]: All the other error modules use `INVALID_PARAMETER`, so this was made consistent.

File: app/scripts/models/mixins/search-param.js [hunk 20]
```diff
@@ -45,9 +45,10 @@ define(function (require, exports, module) {
      * @param {String} paramName - name of the search parameter
      * @param {String} [modelName] - name to set in model. If not specified,
      *      use the same value as `paramName`
-     * @throws {TypeError} if paramName is neither `true` nor `false`
+     * @param {Errors} Errors - corresponding Errors object
+     * @throws {error}
      */
-    importBooleanSearchParam: function (paramName, modelName) {
+    importBooleanSearchParam: function (paramName, modelName, Errors) {
```
Comment (shane-tomlinson) [inline app/scripts/models/mixins/search-param.js]: I updated this function signature to match `importRequiredSearchParam`

File: app/scripts/models/reliers/oauth.js [hunk 21]
```diff
@@ -260,12 +311,39 @@ define(function (require, exports, module) {
   }
 
   function scopeStrToArray(scopes) {
-    return typeof scopes === 'string' ? _.uniq(scopes.split(/\s+/g)) : scopes;
+    if (! _.isString) {
+      return [];
+    }
+
+    var trimmedScopes = scopes.trim();
```
Comment (shane-tomlinson) [inline app/scripts/models/reliers/oauth.js]: a scope of `''` would create an array with a single scope, ``. That's not what we wanted.

**Comment by vbudhram** [comment]
LGTM, I think its ready barring travis.
