### PR TITLE
fix(styles): add position fixed to success messages if user scrolls t…

### LINKED ISSUE #5552: Ensure that temporary settings messages are always visible
If you perform an action in Settings, like adding a secondary email, often the message is out of view.

We should keep the message where it is when the user is scrolled to the top, but fix the messages to the top of the window when they are not.

Like this:
omnipresent

### PR DESCRIPTION
**Pull request by vladikoff**
…oo far

Fixes #5552 

@vbudhram r?

### CODE REVIEW

File: app/scripts/views/base.js [hunk 1]
```diff
@@ -49,6 +50,14 @@ define(function (require, exports, module) {
       .slideDown(STATUS_MESSAGE_ANIMATION_MS)
       .attr('data-shown', 'true');
 
+    if (this.window.pageYOffset >= DEFAULT_HEADER_HEIGHT){
+      $success.css({
+        position: 'fixed',
+        top: 0,
+        width: 500 // required to force the width
```
Comment (vbudhram) [inline app/scripts/views/base.js]: When testing on small screens, this causes it to be offset to the right. I tried `'100%'` and it seemed to work well?

Comment (vladikoff) [reply app/scripts/views/base.js]: hmmm small screens should just do width 100% already anyway, let me check

**Comment by vladikoff** [comment]
@vbudhram ok pushed a fix to make the notification to be consistent to what is on mobile
