### PR TITLE
fix(build): Ensure revs/filenames are correctly created.

### LINKED ISSUE #4189: Fix checksum-ed naming of css files
Ref: #4187 

`
But this points out that the checksum of all the css files is not a checksum (correct md5 or not) of the final css file content, but a checksum of presumably some earlier form of the css content.
`

In #4187, the `.css` deadbeef names did not change, yet actual content was different.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Also contains #4186.

The main CSS and JS bundle reference URLs to other static resources that
are themselves revved. We erroneously revved the main CSS and JS bundle
before updating the referenced URLs with the revved variants and
updating the JS bundle with SRI hashes. This led to files across two
trains having different content but the same filename.

Instead, we do a two phase approach to revving/SRI hash generation:

1) rev all the leaf node resources. Update references in the main JS and
   CSS bundle. Generate SRI hashes for revved JS. Insert SRI values into
   main JS bundle.
2) rev the resources with dependencies. Generate SRI hash for the main
   JS bundle. Update URL references in the HTML. Update SRI values in
   the HTML.

fixes #4189

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@jrgm, @jbuck - I think this'll make you both happy:

```bash
➜  scripts git:(issue-4189-fix-the-md5s) md5 4367e7e8.main.js
MD5 (4367e7e8.main.js) = 4367e7e80eb4ac144f82ed9dda86312f
➜  scripts git:(issue-4189-fix-the-md5s) md5 bb8c4e04.head.js
MD5 (bb8c4e04.head.js) = bb8c4e04a4d7bd12925aad4f21624cea
➜  scripts git:(issue-4189-fix-the-md5s) cd ../styles
➜  styles git:(issue-4189-fix-the-md5s) md5 8ed64f83.ar.css
MD5 (8ed64f83.ar.css) = 8ed64f83cfda717bf93cc4368d1cac63
➜  styles git:(issue-4189-fix-the-md5s) md5 abdc5d6d.de.css
MD5 (abdc5d6d.de.css) = abdc5d6d63149a9d4a6f000613897ed9
➜  styles git:(issue-4189-fix-the-md5s) md5 b74c6b69.az.css
MD5 (b74c6b69.az.css) = b74c6b69bd2d38e6b81cdaf7a1d59bb2
```

**Comment by shane-tomlinson** [comment]
@jrgm, @jbuck, @vladikoff - r?

File: grunttasks/rev.js [hunk 1]
```diff
@@ -4,19 +4,36 @@
...
           '<%= yeoman.dist %>/fonts/{,*/}*.{woff,woff2,svg,ofl,eot,ttf}'
         ]
       }
+    },
+    // These files contain references to other files and must be
+    // revved after internal URLs have been updated or else
+    // different revs of the file with different contents
+    // can have the same name because the rev was created before
+    // internal URLs were updated.
+    with_children: { //eslint-disable-line camelcase
```
Comment (vladikoff) [inline grunttasks/rev.js]: 👍
