### PR TITLE
fix(devices): format connected date

### LINKED ISSUE #3377: Format last connected date in Devices View
Hey @philbooth I got the view above ^, do we still need to format that number or is this my local setup?

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3377

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson @philbooth r?

**Comment by vladikoff** [comment]
I see one functional test is failing with `expected '46 years ago' to equal 'less than a minute ago'` I'll fix it up tomorrow

File: app/scripts/views/settings/devices.js [hunk 1]
```diff
@@ -20,6 +24,29 @@ define(function (require, exports, module) {
...
 
+  function formatConnectedTimestamp (timestamp) {
+    return $.timeago(timestamp, {
+      settings: {
+        strings: {
+          day: t('a day'),
+          days: t('%d days'),
+          hour: t('about an hour'),
+          hours: t('about %d hours'),
+          inPast: t('any moment now'),
```
Comment (philbooth) [inline app/scripts/views/settings/devices.js]: I wasn't sure what this string signified so went to look at the docs and it seems like it will be ignored in our case, because we don't set `allowPast` to false. If that is the case, maybe delete it to prevent any confusion?

File: app/scripts/views/settings/devices.js [hunk 2]
```diff
@@ -20,6 +24,29 @@ define(function (require, exports, module) {
...
   var FORCE_DEVICE_LIST_VIEW = 'forceDeviceList';
 
+  function formatConnectedTimestamp (timestamp) {
+    return $.timeago(timestamp, {
+      settings: {
+        strings: {
+          day: t('a day'),
+          days: t('%d days'),
+          hour: t('about an hour'),
+          hours: t('about %d hours'),
```
Comment (philbooth) [inline app/scripts/views/settings/devices.js]: There is some inconsistency here, the other `%d` strings do not have the `about` prefix.

File: app/scripts/views/settings/devices.js [hunk 3]
```diff
@@ -42,9 +69,15 @@ define(function (require, exports, module) {
       devices.on('remove', this._onDeviceRemoved.bind(this));
     },
 
+    _formatDevicesList: function (devices) {
+      return _.each(devices, function (device) {
+        device.lastAccessTime = formatConnectedTimestamp(Number(device.lastAccessTime));
```
Comment (philbooth) [inline app/scripts/views/settings/devices.js]: Where do we stand on referential transparency? Just wondering whether this function would be preferable if it returned `_.map` and we ditched the internal assignment.

File: app/scripts/views/settings/devices.js [hunk 4]
```diff
@@ -20,6 +24,29 @@ define(function (require, exports, module) {
...
+          day: t('a day'),
+          days: t('%d days'),
+          hour: t('about an hour'),
+          hours: t('about %d hours'),
+          inPast: t('any moment now'),
+          minute: t('about a minute'),
+          minutes: t('%d minutes'),
+          month: t('about a month'),
+          months: t('%d months'),
+          seconds: t('less than a minute'),
```
Comment (philbooth) [inline app/scripts/views/settings/devices.js]: This one feels a bit cumbersome to me. Would something like `just now` be better?

**Comment by philbooth** [comment]
Other than my inline comments and that failing test, this looks good to me. :+1:

File: app/scripts/views/settings/devices.js (hunk 4 above)
Comment (philbooth) [inline app/scripts/views/settings/devices.js]: Oh wait, that won't work because of the `ago` suffix right? In that case how about `a few seconds` instead?

File: app/scripts/views/settings/devices.js (hunk 1 above)
Comment (vladikoff) [inline app/scripts/views/settings/devices.js]: :+1:

File: app/scripts/views/settings/devices.js (hunk 3 above)
Comment (vladikoff) [inline app/scripts/views/settings/devices.js]: yeap, sorry I had `map` in there before, will update. I think for now we shall keep it simple and if we have to reuse this we can modify this a bit in the future.

File: app/scripts/views/settings/devices.js (hunk 4 above)
Comment (vladikoff) [inline app/scripts/views/settings/devices.js]: :+1: to `a few seconds`
