### PR TITLE
fix(client): No more redirect to `signin_complete` w/ fx_desktop_v2

### LINKED ISSUE #3330: Email verification poll and flash of verification success w/ context=fx_desktop_v2
A Firefox patch recently landed that changes the default context from `fx_desktop_v1` to `fx_desktop_v2`. With `fx_desktop_v1` the content server [does not do an email verification verification poll](https://github.com/mozilla/fxa-content-server/issues/2038) because the browser is already doing its own. `fx_desktop_v2` *does* do a verification poll. 

Problem 1: Double the verification polls is less than double the fun. In fact, it's half the strain as far as the servers are concerned.

Next, when the user verifies, the signup page briefly shows the "signup complete" screen before the browser takes over and re-displays "about:preferences#sync"

Problem 2: The "signup complete" screen is briefly displayed.

Sorry for the long pause in the middle, I am verifying in a second browser so this window was not obscured.

flash-of-success-post-verification

Ref #3329

### LINKED ISSUE #3353: Signing in to Sync on desktop briefly shows unexpected error message
Signing in to Sync on desktop briefly shows unexpected error message.
fest

### PR DESCRIPTION
**Pull request by shane-tomlinson**
To fix #3330, a new base authentication broker was created
for all WebChannel based brokers. The new broker did not
define any behaviors.

FxDesktopV2AuthenticationBroker is based off of this
new broker, wheras it used to be based off of
FxDesktopV1AuthenticationBroker. DesktopV1 had all
the correct behaviors defined. DesktopV2 did not
define behaviors for afterForceAuth, afterSignIn
and afterResetPasswordConfirmationPoll

This PR defines those behaviors, and adds functional tests
to ensure we do not regress.

fixes #3353

### CODE REVIEW

File: app/tests/spec/models/auth_brokers/fx-desktop-v2.js [hunk 1]
```diff
@@ -73,12 +73,22 @@ define(function (require, exports, module) {
       });
     });
 
+    describe('afterForceAuth', function () {
+      it('notifies the channel with `fxaccounts:login`, halts', function () {
```
Comment (vbudhram) [inline app/tests/spec/models/auth_brokers/fx-desktop-v2.js]: Minor nit, other tests have `halts by default` instead of halt

File: app/tests/spec/models/auth_brokers/fx-desktop-v2.js [hunk 2]
```diff
@@ -73,12 +73,22 @@ define(function (require, exports, module) {
...
+          .then(function (result) {
+            assert.isTrue(channelMock.send.calledWith('fxaccounts:login'));
+            assert.isTrue(result.halt);
+          });
+      });
+    });
+
     describe('afterSignIn', function () {
-      it('notifies the channel with `fxaccounts:login`, does not halt', function () {
+      it('notifies the channel with `fxaccounts:login`, halts', function () {
```
Comment (vbudhram) [inline app/tests/spec/models/auth_brokers/fx-desktop-v2.js]: Same as above, `halts by default`

File: app/tests/spec/models/auth_brokers/fx-desktop-v2.js (hunk 1 above)
Comment (shane-tomlinson) [inline app/tests/spec/models/auth_brokers/fx-desktop-v2.js]: `by default` didn't add any value to any of those messages, so I removed them all.

**Comment by vladikoff** [comment]
Tested via fxa-local-dev, works well here :+1:
