### PR TITLE
fix(client): Fix status message on /connect_another_device

### LINKED ISSUE #4634: Confirm that connect another device shows the right message
Just a quick one for @shane-tomlinson…

I noticed that when I copied and pasted the confirmation URL into different browsers, I would get "This device is connected" even though I would be in Chrome or signed in to Firefox with a different user.

Will what ships to production be smarter and show the right thing?

* Say "Email verified" in all browsers except the originating Firefox.
* Show original "Account confirmed" screen for Firefoxes already occupied by other users.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Users who verify on a non-Firefox browser see a "Email verified" success message. If the user re-loaded the page, they'd see "This device is connected." This wasn't right.

The problem was with the user model's isSignedInAccount function, it didn't check to ensure both the "signed in account" and the "account to check" had UID's before comparing them. If both UIDs were undefined, the function returned true.

fixes #4634

@mozilla/fxa-devs - r?

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3d4abfa1c23013d5bbfb2024b7b0326ef975776d
  * Your commit message body contains a line that is longer than 100 characters

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d505f0ee27fbe1123b0a4d4aae2842f265748c77
  * Your commit message body contains a line that is longer than 100 characters

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

File: app/scripts/models/user.js [hunk 1]
```diff
@@ -175,8 +175,19 @@ define(function (require, exports, module) {
...
+     * Check if the current account is the signed in account
+     *
+     * @param {Object} account
+     * @returns {Boolean}
+     */
     isSignedInAccount (account) {
-      return account.get('uid') === this.getSignedInAccount().get('uid');
+      const signedInAccount = this.getSignedInAccount();
+      // both accounts must have a UID to be able to compare.
+      if (! signedInAccount.get('uid') || ! account.get('uid')) {
```
Comment (philbooth) [inline app/scripts/models/user.js]: Is it worth caching these results locally to eliminate the dupe calls below?

Comment (shane-tomlinson) [inline app/scripts/models/user.js]: 👍

**Comment by philbooth** [comment]
Looks good, r+.

**Comment by vladikoff** [comment]
updated the branch to rerun the tests

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 054b4a730b6f04a19cae888e5c1be3ce8c29ae12
  * Your commit message body contains a line that is longer than 100 characters

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 054b4a730b6f04a19cae888e5c1be3ce8c29ae12
  * Your commit message body contains a line that is longer than 100 characters

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Tests exploded : o
