### PR TITLE
fix(metrics): limit Sentry stack frames

### LINKED ISSUE #3167: 414 Request-URI Too Large when reporting an error
@rnewman noticed this while debugging the ios client.  A traceback caused us to attempt to report an error to sentry, but that error out because the URL was too long:

```
      {
        "pageref": "page_1",
        "startedDateTime": "2015-10-12T18:25:19.281-07:00",
        "time": 108,
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "https://accounts.firefox.com/metrics-errors?sentry_version=4&sentry_client=raven-js/1.1.18&sentry_key=__API_KEY__&sentry_data=%7B%22project%22%3A%22metrics-errors%22%2C%22logger%22%3A%22javascript%22%2C%22platform%22%3A%22javascript%22%2C%22request%22%3A%7B%22url%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fforce_auth%3Fservice%3Dsync%26context%3Dfx_desktop_v1%26email%3DVALUE%26entrypoint%3Dmenupanel%22%2C%22headers%22%3A%7B%22User-Agent%22%3A%22Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010.10%3B%20rv%3A44.0)%20Gecko%2F20100101%20Firefox%2F44.0%22%7D%7D%2C%22exception%22%3A%7B%22type%22%3A%22Error%22%2C%22value%22%3A%22Working%E2%80%A6%22%7D%2C%22stacktrace%22%3A%7B%22frames%22%3A%5B%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A11%2C%22colno%22%3A1628%2C%22function%22%3A%22%3F%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A29%2C%22colno%22%3A4542%2C%22function%22%3A%22%3F%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A14169%2C%22function%22%3A%22requirejs%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A10745%2C%22function%22%3A%22f%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A14281%2C%22function%22%3A%22setTimeout%20handler*req.nextTick%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A10806%2C%22function%22%3A%22f%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A5618%2C%22function%22%3A%22newContext%2Ft.prototype.init%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A9055%2C%22function%22%3A%22newContext%2Ft.prototype.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A6516%2C%22function%22%3A%22newContext%2Ft.prototype.check%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A12385%2C%22function%22%3A%22newContext%2Fu.execCb%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A29%2C%22colno%22%3A4595%2C%22function%22%3A%22%3F%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A14169%2C%22function%22%3A%22requirejs%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A10745%2C%22function%22%3A%22f%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A14281%2C%22function%22%3A%22setTimeout%20handler*req.nextTick%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A10806%2C%22function%22%3A%22f%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A5618%2C%22function%22%3A%22newContext%2Ft.prototype.init%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A8509%2C%22function%22%3A%22newContext%2Ft.prototype.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A236%2C%22function%22%3A%22each%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A761%2C%22function%22%3A%22bind%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A8915%2C%22function%22%3A%22newContext%2Ft.prototype.enable%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A11457%2C%22function%22%3A%22newContext%2Fu.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A8509%2C%22function%22%3A%22newContext%2Ft.prototype.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A236%2C%22function%22%3A%22each%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A761%2C%22function%22%3A%22bind%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A8915%2C%22function%22%3A%22newContext%2Ft.prototype.enable%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A11457%2C%22function%22%3A%22newContext%2Fu.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A8509%2C%22function%22%3A%22newContext%2Ft.prototype.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A236%2C%22function%22%3A%22each%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A761%2C%22function%22%3A%22bind%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A8915%2C%22function%22%3A%22newContext%2Ft.prototype.enable%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A11457%2C%22function%22%3A%22newContext%2Fu.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A9055%2C%22function%22%3A%22newContext%2Ft.prototype.enable%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A6516%2C%22function%22%3A%22newContext%2Ft.prototype.check%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A12385%2C%22function%22%3A%22newContext%2Fu.execCb%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A15%2C%22colno%22%3A14579%2C%22function%22%3A%22%3F%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A15%2C%22colno%22%3A11028%2C%22function%22%3A%22MutationCallback*o%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A17%2C%22colno%22%3A8624%2C%22function%22%3A%22l%3C.validateAndSubmit%3C%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A17%2C%22colno%22%3A6174%2C%22function%22%3A%22c%2F%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A16%2C%22colno%22%3A19238%2C%22function%22%3A%22setTimeout%20handler*c.setTimeout%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A16%2C%22colno%22%3A19280%2C%22function%22%3A%22c.setTimeout%2Ff%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A17%2C%22colno%22%3A6204%2C%22function%22%3A%22c%2F%3C%2Fe._workingTimeout%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22lineno%22%3A16%2C%22colno%22%3A4655%2C%22function%22%3A%22.toError%22%2C%22in_app%22%3Atrue%7D%5D%7D%2C%22culprit%22%3A%22https%3A%2F%2Faccounts.firefox.com%2Fscripts%2F94010e37.main.js%22%2C%22message%22%3A%22Working%E2%80%A6%22%2C%22tags%22%3A%7B%22errno%22%3A1005%2C%22namespace%22%3A%22auth%22%7D%2C%22extra%22%3A%7B%22session%3Aduration%22%3A30817%7D%2C%22event_id%22%3A%22fe920976627c410c820c13657f6f3a18%22%7D",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "accounts.firefox.com"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
            },
            {
              "name": "Accept",
              "value": "image/png,image/*;q=0.8,*/*;q=0.5"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Referer",
              "value": "https://accounts.firefox.com/force_auth?service=sync&context=fx_desktop_v1&email=holygoat%2Bfxateststage%40gmail.com&entrypoint=menupanel"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "queryString": [
            {
              "name": "sentry_version",
              "value": "4"
            },
            {
              "name": "sentry_client",
              "value": "raven-js/1.1.18"
            },
            {
              "name": "sentry_key",
              "value": "__API_KEY__"
            },
            {
              "name": "sentry_data",
              "value": "{\"project\":\"metrics-errors\",\"logger\":\"javascript\",\"platform\":\"javascript\",\"request\":{\"url\":\"https://accounts.firefox.com/force_auth?service=sync&context=fx_desktop_v1&email=VALUE&entrypoint=menupanel\",\"headers\":{\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0\"}},\"exception\":{\"type\":\"Error\",\"value\":\"Working…\"},\"stacktrace\":{\"frames\":[{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":11,\"colno\":1628,\"function\":\"?\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":29,\"colno\":4542,\"function\":\"?\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":14169,\"function\":\"requirejs\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":10745,\"function\":\"f\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":14281,\"function\":\"setTimeout handler*req.nextTick<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":10806,\"function\":\"f/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":5618,\"function\":\"newContext/t.prototype.init\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":9055,\"function\":\"newContext/t.prototype.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":6516,\"function\":\"newContext/t.prototype.check\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":12385,\"function\":\"newContext/u.execCb\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":29,\"colno\":4595,\"function\":\"?\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":14169,\"function\":\"requirejs\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":10745,\"function\":\"f\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":14281,\"function\":\"setTimeout handler*req.nextTick<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":10806,\"function\":\"f/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":5618,\"function\":\"newContext/t.prototype.init\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":8509,\"function\":\"newContext/t.prototype.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":236,\"function\":\"each\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":761,\"function\":\"bind/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":8915,\"function\":\"newContext/t.prototype.enable/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":11457,\"function\":\"newContext/u.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":8509,\"function\":\"newContext/t.prototype.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":236,\"function\":\"each\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":761,\"function\":\"bind/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":8915,\"function\":\"newContext/t.prototype.enable/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":11457,\"function\":\"newContext/u.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":8509,\"function\":\"newContext/t.prototype.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":236,\"function\":\"each\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":761,\"function\":\"bind/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":8915,\"function\":\"newContext/t.prototype.enable/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":11457,\"function\":\"newContext/u.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":9055,\"function\":\"newContext/t.prototype.enable\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":6516,\"function\":\"newContext/t.prototype.check\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":10,\"colno\":12385,\"function\":\"newContext/u.execCb\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":15,\"colno\":14579,\"function\":\"?\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":15,\"colno\":11028,\"function\":\"MutationCallback*o\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":17,\"colno\":8624,\"function\":\"l<.validateAndSubmit</<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":17,\"colno\":6174,\"function\":\"c/<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":16,\"colno\":19238,\"function\":\"setTimeout handler*c.setTimeout\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":16,\"colno\":19280,\"function\":\"c.setTimeout/f<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":17,\"colno\":6204,\"function\":\"c/</e._workingTimeout<\",\"in_app\":true},{\"filename\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"lineno\":16,\"colno\":4655,\"function\":\".toError\",\"in_app\":true}]},\"culprit\":\"https://accounts.firefox.com/scripts/94010e37.main.js\",\"message\":\"Working…\",\"tags\":{\"errno\":1005,\"namespace\":\"auth\"},\"extra\":{\"session:duration\":30817},\"event_id\":\"fe920976627c410c820c13657f6f3a18\"}"
            }
          ],
          "postData": {
            "mimeType": "",
            "params": [],
            "text": ""
          },
          "headersSize": 9954
        },
        "response": {
          "status": 414,
          "statusText": "Request-URI Too Large",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "199"
            },
            {
              "name": "Content-Type",
              "value": "text/html"
            },
            {
              "name": "Date",
              "value": "Tue, 13 Oct 2015 01:25:20 GMT"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html",
            "size": 0,
            "text": ""
          },
          "redirectURL": "",
          "headersSize": 145,
          "bodySize": 199
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 6,
          "send": 0,
          "wait": 102,
          "receive": 0
        },
        "serverIPAddress": "52.10.102.145",
        "connection": "443"
      },
```

I don't know much about sentry, but can we change this to use a POST?  It seems a shame to be missing out on reports like this in the wild.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3167

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson @vbudhram r?

**Comment by vladikoff** [comment]
The limit of 20 frames trims the request, shows up like this in Sentry:

File: server/lib/routes/get-metrics-errors.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ var config = require('../configuration');
 var sentryConfig = config.get('sentry');
 
 var API_KEY = sentryConfig.api_key;
+var STACK_TRACE_LENGTH = 20;
```
Comment (vbudhram) [inline server/lib/routes/get-metrics-errors.js]: Should this be a config value?

Comment (vladikoff) [inline server/lib/routes/get-metrics-errors.js]: I don't think so, no need to dynamically change it based on environments.

File: server/lib/routes/get-metrics-errors.js [hunk 2]
```diff
@@ -29,6 +30,15 @@ function setExtraSentryData(data) {
   if (sentryData) {
     sentryData.release = CONTENT_SERVER_VERSION;
 
+    if (sentryData.stacktrace && sentryData.stacktrace.frames) {
```
Comment (vbudhram) [inline server/lib/routes/get-metrics-errors.js]: I am unable to hit this path in the debugger. This [line](https://github.com/mozilla/fxa-content-server/blob/i3167/server/lib/routes/get-metrics-errors.js#L59) always resolves to false when running test. Might have to mock sentry config?

Comment (vladikoff) [inline server/lib/routes/get-metrics-errors.js]: There is a test below that should hit it, otherwise you need to add to `local.json`:

  "sentry": {
    "endpoint": "https://sentry.prod.mozaws.net/api/31/store/",
    "api_key": "8e7aaaa38fdb46e58ec0b3de61373492"
  }

and look at Sentry Content Dev. If you don't have the above in the config then it will skip it.

Comment (vbudhram) [inline server/lib/routes/get-metrics-errors.js]: That was it!

**Comment by vbudhram** [comment]
LGTM :+1:

**Comment by vladikoff** [comment]
Thanks!
