### PR TITLE
fix(auth_broker): fx-desktop-v1 merged into fx-ios-v1

### LINKED ISSUE #7033: Merge fx-desktop-v1 auth broker into fx-ios-v1
## Description

Support for context=fx_desktop_v1 was removed in #6895, but we still have the [fx-desktop-v1](https://github.com/mozilla/fxa-content-server/blob/8adcfd3173857e45f1798dd6dacdfa1ce04c342d/app/scripts/models/auth_brokers/fx-desktop-v1.js#L1) auth broker. Since fx_desktop_v1 can no longer be used, let's merge fx-desktop-v1.js into [fx-ios-v1.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/fx-ios-v1.js#L1) ensuring any properties/behaviors overridden by fx-ios-v1 remain the same. Any tests that exist only for [fx-desktop-v1.js](https://github.com/shane-tomlinson/fxa-content-server/blob/88de680d56263fc647dfe21954b62f26ff90ce0e/app/tests/spec/models/auth_brokers/fx-desktop-v1.js#L1) should also be migrated to [fx-ios-v1](https://github.com/shane-tomlinson/fxa-content-server/blob/88de680d56263fc647dfe21954b62f26ff90ce0e/app/tests/spec/models/auth_brokers/fx-ios-v1.js#L1)

### PR DESCRIPTION
**Pull request by farhan787**
fixes #7033 
@shane-tomlinson please review it!

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@farhan787 sorry for the review delay, I had a quick look and at a high level is just what I hoped for. I will have a look in more detail tomorrow.

**Comment by farhan787** [comment]
> @farhan787 sorry for the review delay, I had a quick look and at a high level is just what I hoped for. I will have a look in more detail tomorrow.

no problem @shane-tomlinson

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 1]
```diff
@@ -11,13 +11,88 @@ define(function (require, exports, module) {
...
+      var channel = new FxDesktopChannel();
+
+      channel.initialize({
+        // Fx Desktop browser will send messages with an origin of the string
+        // `null`. These messages are trusted by the channel by default.
+        //
+        // 1) Fx on iOS and functional tests will send messages from the
+        // content server itself. Accept messages from the content
+        // server to handle these cases.
+        // 2) Fx 18 (& FxOS 1.*) do not support location.origin. Build the origin from location.href
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-ios-v1.js]: We no longer support either of these environments, it's a good opportunity to remove outdated logic (and comment!).

On line 63, can you remove from `||` to the end of the line?

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 2]
```diff
@@ -11,13 +11,88 @@ define(function (require, exports, module) {
...
+      // We wouldn't expect `customizeSync` to be set when completing
+      // a password reset, but the field must be present for the login
+      // message to be sent. false is the default value set in
+      // lib/fxa-client.js if the value is not present.
+      // See #5528
+      if (! account.has('customizeSync')) {
+        account.set('customizeSync', false);
+      }
+
+      // Only fx-desktop-v1 based integrations send a login message
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-ios-v1.js]: Can you change `Only fx-desktop-v1 based integrations` to `fx-ios-v1`

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 3]
```diff
@@ -11,13 +11,88 @@ define(function (require, exports, module) {
...
+      // after reset password complete, assuming the user verifies
+      // in the same browser. fx-desktop-v1 based integrations
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-ios-v1.js]: Can you change `Only fx-desktop-v1 based integrations` to `fx-ios-v1`

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 4]
```diff
@@ -11,13 +11,88 @@ define(function (require, exports, module) {
...
+      // about:accounts displays its own screen after sign in, no need
+      // to show anything.
+      afterForceAuth: new HaltBehavior(),
+      // about:accounts displays its own screen after password reset, no
+      // need to show anything.
+      afterResetPasswordConfirmationPoll: new HaltBehavior(),
+      // about:accounts displays its own screen after sign in, no need
+      // to show anything.
+      afterSignIn: new HaltBehavior(),
+      // about:accounts displays its own screen after sign in, no need
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-ios-v1.js]: In the [initialize method](https://github.com/mozilla/fxa-content-server/pull/7037/files#diff-110efcbbe9c2689e314cc3faa97baf8bL40) we override both `afterSignInConfirmationPoll` and `afterSignUpConfirmationPoll`. Since we no longer support fx-desktop-v1, we might as well make those the defaultBehaviors. Can you remove the overrides in `initialize` and instead set those as the default behaviors up here? The comments will need to be updated too.

File: app/tests/spec/models/auth_brokers/fx-ios-v1.js [hunk 5]
```diff
@@ -126,23 +130,135 @@ define(function (require, exports, module) {
...
 
         it('broker calls correct methods', () => {
-          assert.isTrue(FxDesktopV1AuthenticationBroker.prototype.afterCompleteSignInWithCode.called);
+          assert.isTrue(broker.afterCompleteSignInWithCode.called);
           assert.isTrue(broker._notifyRelierOfLogin.called);
         });
       });
     });
+
+    describe('createChannel', function () {
```
Comment (shane-tomlinson) [inline app/tests/spec/models/auth_brokers/fx-ios-v1.js]: I know the old tests used `function () {`, can you change all of those in these new tests to be `() => {`?

File: app/tests/spec/models/auth_brokers/fx-ios-v1.js [hunk 6]
```diff
@@ -126,23 +130,135 @@ define(function (require, exports, module) {
...
+            assert.isTrue(result.halt);
+          });
+      });
+    });
+
+    describe('afterSignInConfirmationPoll', () => {
+      it('halts by default', () => {
+        return broker.afterSignInConfirmationPoll(account)
+          .then((result) => {
+            assert.isTrue(result.halt);
```
Comment (shane-tomlinson) [inline app/tests/spec/models/auth_brokers/fx-ios-v1.js]: With the changes to the defaultBehavior for `afterSignInConfirmationPoll`, this will start failing. The test will need to be updated accordingly.

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 7]
```diff
@@ -11,13 +11,88 @@ define(function (require, exports, module) {
...
+  const HaltBehavior = require('../../views/behaviors/halt');
   const NavigateBehavior = require('../../views/behaviors/navigate');
+  const Url = require('../../lib/url');
   const UserAgent = require('../../lib/user-agent');
 
-  const proto = FxDesktopV1AuthenticationBroker.prototype;
+  const proto = FxSyncChannelAuthenticationBroker.prototype;
+
+  const FxiOSV1AuthenticationBroker = FxSyncChannelAuthenticationBroker.extend({
+    type: 'fx-desktop-v1',
```
[the remark this answers is not in the document]
Comment (farhan787) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: I should have done this on my own, really sorry for this @shane-tomlinson

[the remark this answers is not in the document]
Comment (farhan787) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: just a moment, I'm doing all the changes.

File: app/scripts/models/auth_brokers/fx-ios-v1.js (hunk 4 above)
Comment (farhan787) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]:
```js
// about:accounts display the "Sign in" screen after the users sign in
afterSignInConfirmationPoll: new NavigateBehavior('signin_confirmed'),
// about:accounts display the "Signup complete!" screen after the users verify their email
afterSignUpConfirmationPoll: new NavigateBehavior('signup_confirmed')
```
@shane-tomlinson are these comments fine ?

Comment (shane-tomlinson) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: Those comments should be fine.

**Comment by farhan787** [comment]
@shane-tomlinson I think it's ready to be merged now.

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 8]
```diff
@@ -11,19 +11,89 @@ define(function (require, exports, module) {
...
+      // about:accounts displays its own screen after sign in, no need
+      // to show anything.
+      afterForceAuth: new HaltBehavior(),
+      // about:accounts displays its own screen after password reset, no
+      // need to show anything.
+      afterResetPasswordConfirmationPoll: new HaltBehavior(),
+      // about:accounts displays its own screen after sign in, no need
+      // to show anything.
+      afterSignIn: new HaltBehavior(),
+      // about:accounts displays its own screen after sign in, no need
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-ios-v1.js]: I was wrong, this comment does need to be updated. A similar comment to lines 46-47 should be put here. Or remove the comment all together

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 9]
```diff
@@ -11,19 +11,89 @@ define(function (require, exports, module) {
...
     }),
 
+    createChannel () {
+      var channel = new FxDesktopChannel();
+
+      channel.initialize({
+        // 1) Fx on iOS and functional tests will send messages from the
+        // content server itself. Accept messages from the content
+        // server to handle these cases.
+        // 2) Fx 18 (& FxOS 1.*) do not support location.origin. Build the origin from location.href
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-ios-v1.js]: This line of the comment can be removed.

File: app/scripts/models/auth_brokers/fx-ios-v1.js [hunk 10]
```diff
@@ -11,19 +11,89 @@ define(function (require, exports, module) {
...
       chooseWhatToSyncCheckbox: false,
       chooseWhatToSyncWebV1: true,
       convertExternalLinksToText: true
     }),
 
+    createChannel () {
+      var channel = new FxDesktopChannel();
+
+      channel.initialize({
+        // 1) Fx on iOS and functional tests will send messages from the
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-ios-v1.js]: Since line 64 can be removed, can you remove the `1)` prefix here?

File: app/scripts/models/auth_brokers/fx-ios-v1.js (hunk 8 above)
Comment (farhan787) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: > A similar comment to lines 46-47 should be put here.

@shane-tomlinson should they be same or it should it contain the sign in message, like this,

```js
// about:accounts display the "Signin" screen after
// the users verify their email
afterSignInConfirmationPoll: new NavigateBehavior('signin_confirmed'),
```

Comment (shane-tomlinson) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: > // about:accounts display the "Signin" screen after
> // the user sign in is successful

How about changing "Signin" to "Signin confirmed", and removing the last "l" in "successfull"

Comment (farhan787) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: > and removing the last "l" in "successfull"

@shane-tomlinson  that was a typo, I think you're talking about adding last 'l' in "sucessfull", am I right ?

Comment (shane-tomlinson) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: "successfull" => "successful". I accidentally deleted the last "l" from "full" in the above comment.

Comment (farhan787) [reply app/scripts/models/auth_brokers/fx-ios-v1.js]: @shane-tomlinson it happened because first I commented that "users sign in successfully" and then I changed it to this but forgot to correct the spelling of successful.

**Comment by farhan787** [comment]
@shane-tomlinson it's my pleasure and thank you too for giving me these opportunities :-)
