### PR TITLE
fix(tests): adjust checkbox test to click on labels properly

### LINKED ISSUE #3618: Tests: Element is not clickable at point. Other element would receive the click
This is a new error that I never seen before:

```
 Element is not clickable at point (494.6000061035156, 375). Other element would receive the click: <span class="fxa-checkbox__label"></span>
```

Seems like we need to tweak our test a bit

http://tests.dev.lcip.org:8111/viewLog.html?buildId=9888&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_focus=430

```
[Step 1/1]  [31mUnknownError: [POST http://localhost:4444/wd/hub/session/394d93ce-9703-4649-948f-ac63f6512c05/element/452/click] Element is not clickable at point (494.6000061035156, 375). Other element would receive the click: <span class="fxa-checkbox__label"></span>
[06:25:51][Step 1/1] Command duration or timeout: 145 milliseconds
[06:25:51][Step 1/1] Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
[06:25:51][Step 1/1] System info: host: 'ip-172-31-11-113', ip: '172.31.11.113', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-51-generic', java.version: '1.7.0_80'
[06:25:51][Step 1/1] Session ID: 4d60758f-7855-4ea8-ad97-c4ab1ecab841
[06:25:51][Step 1/1] Driver info: org.openqa.selenium.firefox.FirefoxDriver
[06:25:51][Step 1/1] Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=45.0.1}]
[06:25:51][Step 1/1]   at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
[06:25:51][Step 1/1]   at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
[06:25:51][Step 1/1]   at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
[06:25:51][Step 1/1]   at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
[06:25:51][Step 1/1]   at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
[06:25:51][Step 1/1]   at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
[06:25:51][Step 1/1]   at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
[06:25:51][Step 1/1]   at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
[06:25:51][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
[06:25:51][Step 1/1]   at processImmediate [as _immediateCallback]  <timers.js:363:15>
[06:25:51][Step 1/1]   at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
[06:25:51][Step 1/1]   at Test.registerSuite.sign up, verify same browser [as test]  <tests/functional/sync_v2_sign_up.js:87:12>
[06:25:51][Step 1/1]   at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
[06:25:51][Step 1/1]   at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
[06:25:51][Step 1/1]   at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
[06:25:51][Step 1/1]   at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
[06:25:51][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
[06:25:51][Step 1/1]   at processImmediate [as _immediateCallback]  <timers.js:363:15> [0m
```

Another case:

```
[06:27:28][Step 1/1]  [31mUnknownError: [POST http://localhost:4444/wd/hub/session/394d93ce-9703-4649-948f-ac63f6512c05/element/570/click] Element is not clickable at point (494.6000061035156, 375). Other element would receive the click: <span class="fxa-checkbox__label"></span>
[06:27:28][Step 1/1] Command duration or timeout: 102 milliseconds
[06:27:28][Step 1/1] Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
[06:27:28][Step 1/1] System info: host: 'ip-172-31-11-113', ip: '172.31.11.113', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-51-generic', java.version: '1.7.0_80'
[06:27:28][Step 1/1] Session ID: 4d60758f-7855-4ea8-ad97-c4ab1ecab841
[06:27:28][Step 1/1] Driver info: org.openqa.selenium.firefox.FirefoxDriver
[06:27:28][Step 1/1] Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=45.0.1}]
[06:27:28][Step 1/1]   at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
[06:27:28][Step 1/1]   at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
[06:27:28][Step 1/1]   at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
[06:27:28][Step 1/1]   at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
[06:27:28][Step 1/1]   at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
[06:27:28][Step 1/1]   at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
[06:27:28][Step 1/1]   at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
[06:27:28][Step 1/1]   at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
[06:27:28][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
[06:27:28][Step 1/1]   at processImmediate [as _immediateCallback]  <timers.js:363:15>
[06:27:28][Step 1/1]   at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
[06:27:28][Step 1/1]   at Test.registerSuite.sign up, verify same browser [as test]  <tests/functional/fx_firstrun_v2_sign_up.js:68:12>
[06:27:28][Step 1/1]   at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
[06:27:28][Step 1/1]   at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
[06:27:28][Step 1/1]   at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
[06:27:28][Step 1/1]   at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
[06:27:28][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
[06:27:28][Step 1/1]   at processImmediate [as _immediateCallback]  <timers.js:363:15> [0m
```

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3618

### CODE REVIEW

File: tests/functional/fx_fennec_v1_sign_up.js [hunk 1]
```diff
@@ -64,11 +64,11 @@ define([
         .end()
 
         // uncheck the passwords and history engines
-        .findByCssSelector('input[value="passwords"]')
+        .findByCssSelector('div.two-col-block:nth-child(2) > div:nth-child(1) > label:nth-child(1)')
           .click()
         .end()
 
-        .findByCssSelector('input[value="history"]')
+        .findByCssSelector('div.two-col-block:nth-child(2) > div:nth-child(2) > label:nth-child(1)')
```
Comment (pdehaan) [inline tests/functional/fx_fennec_v1_sign_up.js]: Would it be easier to give the `<label>` tags a unique id or classname to help with the [arguably complex] `:nth-child(x)` logic?

Comment (vladikoff) [inline tests/functional/fx_fennec_v1_sign_up.js]: Didn't want to add extras to the template if they are only used for tests

**Comment by vladikoff** [comment]
Merging to unblock TeamCity, let me know if needs to be tweaked.
