### PR TITLE
fix(server): Allow the /signin, /signup, /reset_pasword to be framed

### LINKED ISSUE #3518: mozilla.org/en-US/firefox/accounts iframe loading is not consistent
## STR

Open https://www.mozilla.org/en-US/firefox/accounts/
iframe shows up
resize the browser
CMD+R to refresh
iframe does not load 

ref

Details: if devtools is open the iframe always loads.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #3518

@rfk - r?

### CODE REVIEW

File: tests/server/routes.js [hunk 1]
```diff
@@ -103,6 +103,10 @@ define([
     '/oauth/signin',
     '/oauth/signup',
     '/oauth/force_auth',
+    '/reset_password',
+    '/v1/reset_password',
```
Comment (shane-tomlinson) [inline tests/server/routes.js]: reset_password is one of those routes that are allowed to have a `/v1` in front of it.

File: server/lib/routes.js [hunk 2]
```diff
@@ -129,7 +129,10 @@ module.exports = function (config, i18n) {
       '/oauth/': true,
       '/oauth/force_auth': true,
       '/oauth/signin': true,
-      '/oauth/signup': true
+      '/oauth/signup': true,
+      '/reset_password': true,
```
Comment (shane-tomlinson) [inline server/lib/routes.js]: I added reset_password as well because it's easy to get to from the signin page.

**Comment by rfk** [comment]
LGTM
