### PR TITLE
fix(csp): update helmet to version 3

### LINKED ISSUE #4369: Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.
Message in Fx console.

Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4369 

@vbudhram please r?

### CODE REVIEW

File: server/lib/hpkp.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ var helmet = require('helmet');
 module.exports = function (config) {
   var hpkpMiddleware = helmet.hpkp({
     includeSubdomains: config.get('hpkp.includeSubDomains'),
-    maxAge: config.get('hpkp.maxAge') * 1000, // Convert to milli-seconds
+    maxAge: config.get('hpkp.maxAge'), // param is now seconds since Helmet 3
```
Comment (vladikoff) [inline server/lib/hpkp.js]: https://github.com/helmetjs/helmet/blob/master/HISTORY.md#300--2016-10-28
