### PR TITLE
fix(client): enforce validation of notifier event data

### LINKED ISSUE #3354: Validate all messages and payloads before they cross a security boundary
Ref https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/user.js#L308

### PR DESCRIPTION
**Pull request by philbooth**
This is my first attempt to fix #3354, validation of notification payloads.

Note that this change doesn't cover the elimination of particular fields, it is purely to implement safeguards for ensuring we don't expose anything unintentionally.

The 3rd-party validation libraries I found were all pretty heavyweight and, as our requirements are simple, I added a new function to `app/scripts/lib/validate.js` to handle the checking.

@shane-tomlinson & @vladikoff, feedback wanted. :grin:

### CODE REVIEW

File: app/scripts/lib/channels/notifier.js [hunk 1]
```diff
@@ -11,20 +11,56 @@ define(function (require, exports, module) {
...
+    },
+    SIGNED_IN: {
+      name: 'internal:signed_in',
+      schema: {
+        // TODO: Eliminate sensitive fields from this data
+        email: '?String',
+        keyFetchToken: '?String',
+        lastLogin: '?Number',
+        needsOptedInToMarketingEmail: '?Boolean',
+        password: '?String',
```
Comment (philbooth) [inline app/scripts/lib/channels/notifier.js]: @shane-tomlinson, I thought #3390 would have eliminated the need for this but it hasn't yet. Were you expecting that, or do we need to investigate some more?

File: app/scripts/lib/channels/notifier.js [hunk 2]
```diff
@@ -11,20 +11,56 @@ define(function (require, exports, module) {
...
+        sessionToken: '?String',
+        uid: 'String',
+        unwrapBKey: '?String',
+        verified: '?Boolean',
+      }
+    },
+    SIGNED_OUT: {
+      name: 'fxaccounts:logout',
+      schema: { uid: '?String' }
```
Comment (philbooth) [inline app/scripts/lib/channels/notifier.js]: I noticed that this wasn't always set in the context of unit tests, so I made it optional for fear of breaking a real-world case. Drawing attention to it here as I wasn't sure whether I should instead have fixed the tests to ensure `uid` is always set.

Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: I think forcing the unit tests to mimic real world behavior is the appropriate behavior.

File: app/scripts/lib/channels/notifier.js [hunk 3]
```diff
@@ -57,6 +93,13 @@ define(function (require, exports, module) {
     },
 
     triggerRemote: function (event, data) {
+      if (SCHEMATA[event]) {
+        if (! Validate.isDataValid(data, SCHEMATA[event])) {
+          throw new Error('Invalid data for event ' + event);
+        }
+      } else if (data !== null && data !== undefined) {
```
Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: So, we are saying, if there is data, there had better be a schema defined.

Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: Can you use the underscore `_.isNull` and `_.isUndefined` here? @vladikoff keeps hitting me over the head for not using them, and I'm passing on the knocks to keep consistency.

File: app/scripts/lib/validate.js [hunk 4]
```diff
@@ -103,6 +103,47 @@ define(function (require, exports, module) {
...
+
+      return Object.keys(data).reduce(function (isValid, key) {
+        if (! isValid) {
+          return isValid;
+        }
+
+        var datum = data[key];
+        var type = schema[key];
+
+        if (datum === undefined && type === undefined) {
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: Should use `_.isUndefined` here too.

File: app/scripts/lib/validate.js [hunk 5]
```diff
@@ -103,6 +103,47 @@ define(function (require, exports, module) {
...
+     * Compares using Object.prototype.toString.
+     */
+    isDataValid: function isDataValid (data, schema) {
+      if (! schema) {
+        return false;
+      }
+
+      if (typeof schema === 'string') {
+        if (schema[0] === '?') {
+          if (data === null || data === undefined) {
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: I'll bet you know what comment I have for here.

File: app/scripts/lib/validate.js [hunk 6]
```diff
@@ -103,6 +103,47 @@ define(function (require, exports, module) {
...
+        }
+
+        return Object.prototype.toString.call(data) === '[object ' + schema + ']';
+      }
+
+      if (! data) {
+        return false;
+      }
+
+      return Object.keys(data).reduce(function (isValid, key) {
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: You might be able to use underscore's [some](http://underscorejs.org/#some) function here, it short circuits as soon as a match is found, and would eliminate the next few lines.

File: app/scripts/lib/channels/notifier.js (hunk 1 above)
Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: Copy from IRC:

I don't see any problems if I only allow `keyFetchToken`, `uid`, and `unwrapBKey`, the functional tests all seem to pass too, the only failures are the unit tests attached to the PR.

File: app/scripts/lib/channels/notifier.js [hunk 7]
```diff
@@ -11,20 +11,56 @@ define(function (require, exports, module) {
...
+    },
+    PROFILE_CHANGE: {
+      name: 'profile:change',
+      schema: { uid: 'String' }
+    },
+    SIGNED_IN: {
+      name: 'internal:signed_in',
+      schema: {
+        // TODO: Eliminate sensitive fields from this data
+        email: '?String',
```
Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: I like the `?` prefix, it's very clear.

File: app/scripts/lib/channels/notifier.js [hunk 8]
```diff
@@ -11,20 +11,56 @@ define(function (require, exports, module) {
...
+    DELETE: {
+      name: 'fxaccounts:delete',
+      schema: { uid: 'String' }
+    },
+    PROFILE_CHANGE: {
+      name: 'profile:change',
+      schema: { uid: 'String' }
+    },
+    SIGNED_IN: {
+      name: 'internal:signed_in',
```
Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: maybe instead of `name`, it's `message`?

File: app/scripts/lib/validate.js [hunk 9]
```diff
@@ -103,6 +103,47 @@ define(function (require, exports, module) {
...
+      if (typeof schema === 'string') {
+        if (schema[0] === '?') {
+          if (data === null || data === undefined) {
+            return true;
+          }
+
+          schema = schema.substr(1);
+        }
+
+        return Object.prototype.toString.call(data) === '[object ' + schema + ']';
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: Should we check to ensure the schema is correct? There should be a type defined, and it should be one of `Object`, `String`, `Number`, etc?

File: app/scripts/lib/channels/notifier.js (hunk 1 above)
Comment (philbooth) [inline app/scripts/lib/channels/notifier.js]: I'm attributing this to temporary insanity, the Bermuda triangle and dark energy. Works fine on my machine too now. :confused:

File: app/tests/spec/lib/validate.js [hunk 10]
```diff
@@ -134,5 +134,112 @@ define(function (require, exports, module) {
...
+        assert.isTrue(Validate.isDataValid(
+          [ 'foo', 3.14159265359, {} ],
+          [ 'String', 'Number', 'Object' ]
+        ));
+      });
+
+      it('returns false when complex type does not match the schema', function () {
+        assert.isFalse(Validate.isDataValid(
+          [ 'foo', 3.14159265359, [] ],
+          [ 'String', 'Number', 'Object' ]
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/validate.js]: Have you handled the case of an unknown array length, all of the same type? Specifically for use with [declinedSyncEngines](https://github.com/mozilla/fxa-content-server/blob/afe52ee1a64b979a54e74422163e99a1d60aabe4/app/scripts/models/account.js#L53)?

File: app/tests/spec/lib/validate.js [hunk 11]
```diff
@@ -134,5 +134,112 @@ define(function (require, exports, module) {
...
+        ));
+        assert.isFalse(Validate.isDataValid(
+          { foo: { bar: [ 'baz', 'qux' ] } },
+          { foo: { bar: [ 'String', 'Number' ] } }
+        ));
+      });
+
+      it('ignores undefined properties if schema property is undefined', function () {
+        assert.isTrue(Validate.isDataValid(
+          { foo: 'bar', baz: undefined },
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/validate.js]: I'm confused, I thought this test should fail since `baz` isn't defined in the schema.

File: app/scripts/lib/channels/notifier.js (hunk 8 above)
Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: In the senders, we call this field [command](https://github.com/mozilla/fxa-content-server/blob/2d7c9e2afe7ad9df0f721ba527615f5b420521ea/app/scripts/lib/channels/duplex.js#L105), let's go with that.

Comment (philbooth) [inline app/scripts/lib/channels/notifier.js]: I may be splitting hairs here, but I disagree. The term `command` there seems synonymous with the term `event` from this module, not `name`.

I only introduced `name` here so that I could distinguish between the two objects `EVENTS` and `EVENT_NAMES`. The second of those concerns itself with the strings that identify the events, not with the events themselves. Calling that object `EVENT_COMMANDS` instead would seem less clear to me, especially as some of them aren't commands in the semantic sense.

Am I making sense?

File: app/tests/spec/lib/validate.js (hunk 10 above)
Comment (philbooth) [inline app/tests/spec/lib/validate.js]: Nope.

In IRC you mentioned that perhaps we'd choose to handle that by padding the schema array instead. I figured it made sense to make until we are validating that property before making the decision.

File: app/tests/spec/lib/validate.js (hunk 11 above)
Comment (philbooth) [inline app/tests/spec/lib/validate.js]: On a philosophical level, that would mean we are behaving differently to JavaScript itself by distinguishing between unset properties and properties which are set to `undefined`. That seems like unexpected behaviour to me.

On a practical level, I found cases during testing where some objects had lots of properties set to `undefined`. Without treating them this way it puts extra burden on the schema author to add a load of `'Undefined'` rules to their schema. Or, even worse, `'?Undefined'` rules.

Against those, I couldn't think of any benefits to being strict about this.

File: app/scripts/lib/validate.js (hunk 9 above)
Comment (philbooth) [inline app/scripts/lib/validate.js]: Imho no, but perhaps there is a benefit to doing so that I'm missing?

The way I see it, this function exists to validate dynamically-produced data, at runtime. The schemata are defined statically so we can validate them much earlier, when we run the tests. Validating them again on execution doesn't seem to buy us anything.

File: app/scripts/lib/validate.js [hunk 12]
```diff
@@ -103,6 +104,43 @@ define(function (require, exports, module) {
...
+    /**
+     * Check whether data matches schema, depth-first.
+     * Compares using Object.prototype.toString.
+     */
+    isDataValid: function isDataValid (data, schema) {
+      if (! schema) {
+        return false;
+      }
+
+      if (typeof schema === 'string') {
```
Comment (vladikoff) [inline app/scripts/lib/validate.js]: http://underscorejs.org/#isString ?

File: app/tests/spec/lib/validate.js (hunk 10 above)
Comment (philbooth) [inline app/tests/spec/lib/validate.js]: Just remembered, the other approach I had in mind for this was a separate function, `isArrayValid`, which does the padding and then calls `isDataValid` to perform the actual validation. Mentioning it here in case it is of interest later.

**Comment by philbooth** [comment]
Thanks for the feedback @shane-tomlinson! Have implemented some and responded to the other bits in-line.

File: app/tests/spec/lib/validate.js (hunk 10 above)
Comment (shane-tomlinson) [inline app/tests/spec/lib/validate.js]: > In IRC you mentioned that perhaps we'd choose to handle that by padding the schema array instead. I figured it made sense to make wait until we are validating that property before making the decision.

Without a wrapper, padding won't work very well in practice, because we'd have to analyze the possible input, then create a schema at runtime based on the input, which is backwards to how it's supposed to work. Which makes the second comment (below) seem like a winner.

> Just remembered, the other approach I had in mind for this was a separate function, isArrayValid, which does the padding and then calls isDataValid to perform the actual validation. Mentioning it here in case it is of interest later.

 Can you make a proposal how we'd handle [sending sync data](https://github.com/mozilla/fxa-content-server/blob/2d7c9e2afe7ad9df0f721ba527615f5b420521ea/app/scripts/models/auth_brokers/fx-sync.js#L207-L221) because that's going to be the next message that's validated.

File: app/scripts/lib/channels/notifier.js (hunk 8 above)
Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: > I may be splitting hairs here, but I disagree. The term command there seems synonymous with the term event from this module, not name.

I didn't realize before this we use two different names in different locations for the same concept... That's a problem.

`command` came about because that's what the browser uses for both the [original FirefoxAccountsCommand message](https://dxr.mozilla.org/mozilla-central/rev/8cb42e7a16b42162c9930f37b9e1f820c2eb126b/browser/base/content/aboutaccounts/aboutaccounts.js#277) and now the [WebChannel message](https://dxr.mozilla.org/mozilla-central/rev/8cb42e7a16b42162c9930f37b9e1f820c2eb126b/services/fxaccounts/FxAccountsWebChannel.jsm#145). `event.name` mirrors the DOM approach so there is precedent there too.

You are correct that `command` is only semantically correct some of the time. Some messages are commands, others are requests and still others are simply informative. Still, I find grep-driven development easiest if the same ill-fitting name is used everywhere.

Comment (philbooth) [inline app/scripts/lib/channels/notifier.js]: So, just making sure I understand correctly before changing it, I'll rename `Notifier.EVENTS` to `Notifier.COMMANDS` and then whatever else to match. Yep?

Comment (philbooth) [inline app/scripts/lib/channels/notifier.js]: (fwiw, I've pushed that)

File: app/tests/spec/lib/validate.js (hunk 10 above)
Comment (philbooth) [inline app/tests/spec/lib/validate.js]: > Can you make a proposal how we'd handle [sending sync data](https://github.com/mozilla/fxa-content-server/blob/2d7c9e2afe7ad9df0f721ba527615f5b420521ea/app/scripts/models/auth_brokers/fx-sync.js#L207-L221)...

I can think of a few:

1. Validate `declinedSyncEngines` as `'Array'` and be content with rudimentary validation for that field. Mentioning this one explicitly as I don't know what the risks/rewards are around validating more strictly (or not) here.

   ```js
   if (isDataValid(loginData, { ..., declinedSyncEngines: 'Array' }) {
   ```

2. Add a separate validation step for that field then implement `isArrayValid` to iterate through the array and apply the supplied schema on each value.

   ```js
   if (isDataValid(loginData, { ..., declinedSyncEngines: 'Array' }) &&
     isArrayValid(loginData.declinedSyncEngines, 'String')) {
   ```

3. Encode the item type in the schema syntax then separate array and object processing inside `isDataValid`. This is a more limited solution than `2` because it doesn't permit the validation of complex array items.

   ```js
   if (isDataValid(loginData, { ..., declinedSyncEngines: 'Array-String' }) {
   ```

4. A variation on `3`:

   ```js
   if (isDataValid(loginData, { ..., declinedSyncEngines: [ 'String' ] }) {
   ```

Option `1` or `2` seems best to me. Have you got any other suggestions that I've not considered?

Comment (philbooth) [inline app/tests/spec/lib/validate.js]: All of those options assume a uniform array of course. If you want to validate a non-uniform array with any of the above, you'd need to know the length and respective indices for each item.

File: app/scripts/lib/validate.js (hunk 9 above)
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: I can deal with that. The end result should be the same, one would have thrown an exception, this variant should return false if the schema is incorrect.

File: app/tests/spec/lib/validate.js (hunk 11 above)
Comment (shane-tomlinson) [inline app/tests/spec/lib/validate.js]: > On a philosophical level, that would mean we are behaving differently to JavaScript itself by distinguishing between unset properties and properties which are set to undefined. That seems like unexpected behaviour to me.

I accept your argument for internal data structures, the constraint is contrary to the spirit/philosophy of JS. We are handling a slightly different use case, at the perimeter, ensuring no data leaves that is unexpected, including unexpected keys. I want to minimize WTF moments by Fx developers when they consume the messages.

The mechanisms used to send the commands and payloads vary depending on the method of transport. When sending via postMessage, the data is serialized using JSON.stringify, at which point keys with `undefined` values will be stripped (hoooray!). Commands/payloads sent using WebChannels and FirefoxAccountsCommand are passed without serialization, and `undefined` values are seen by the consumer (BOO!). A [request has been made to serialize data before sending over WebChannels](https://bugzilla.mozilla.org/show_bug.cgi?id=1238128). Fx developers that receive payloads with `undefined` values have good reason to question, "is everything legit here?"

Comment (shane-tomlinson) [inline app/tests/spec/lib/validate.js]: > Fx developers that receive payloads with undefined values have good reason to question, "is everything legit here?"

So maybe the resolution is to strip those before validation and leave the schema as is? I'm torn.

Comment (philbooth) [inline app/tests/spec/lib/validate.js]: Not sure if I'm missing your point, but it's worth bearing in mind there is no `undefined` in JSON. Those keys won't be serialized, right?

Comment (shane-tomlinson) [inline app/tests/spec/lib/validate.js]: > Not sure if I'm missing your point, but it's worth bearing in mind there is no undefined in JSON. Those keys won't be serialized, right?

`undefined` values are not serialized w/ JSON.serialize. The problem is objects sent over WebChannels and FirefoxAccountsCommands are not serialized.

Comment (philbooth) [inline app/tests/spec/lib/validate.js]: Understood. In that case, given that this condition is already detected by `isDataValid`, is it acceptable to add an explicit `delete data[key]` before returning at line 139 of `app/scripts/lib/validate.js`?

File: app/scripts/lib/channels/notifier.js (hunk 2 above)
Comment (philbooth) [inline app/scripts/lib/channels/notifier.js]: Fwiw, I fixed the unit tests but it turns out it's needed for the functional tests too.

**Comment by philbooth** [comment]
@shane-tomlinson, `isDataValid` now distinguishes between undefined properties and properties that are set to `undefined`, as per your request. Let me know if I need to make other changes.

File: app/scripts/lib/channels/notifier.js [hunk 13]
```diff
@@ -51,22 +80,31 @@ define(function (require, exports, module) {
...
-      this.triggerRemote(event, data);
-      this.trigger(event, data, context);
+    triggerAll: function (command, data, context) {
+      this.triggerRemote(command, data);
+      this.trigger(command, data, context);
     },
 
-    triggerRemote: function (event, data) {
+    triggerRemote: function (command, data) {
+      data = eliminateUndefinedProperties(data);
```
Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier.js]: I can deal with this. Can you add a note about why? The reason I noted is because not all payloads are actually serialized, in those cases the keys with undefined values are sent to the receiver.

File: app/tests/spec/lib/channels/notifier.js [hunk 14]
```diff
@@ -112,17 +111,120 @@ define(function (require, exports, module) {
...
 
           assert.isFalse(webChannelMock.send.called);
           assert.isFalse(iframeChannelMock.send.called);
           assert.isFalse(notifierSpy.called);
         });
       });
+
+      describe('with undefined properties', function () {
+        var data = { a: undefined, uid: 'foo', z: undefined };
+        var expectedData = { uid: 'foo' };
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/channels/notifier.js]: :+1:

File: app/scripts/lib/validate.js [hunk 15]
```diff
@@ -103,6 +104,36 @@ define(function (require, exports, module) {
       }
 
       return password.length >= Constants.PASSWORD_MIN_LENGTH;
+    },
+
+    /**
+     * Check whether data matches schema, depth-first.
+     * Compares using Object.prototype.toString.
+     */
```
Comment (shane-tomlinson) [inline app/scripts/lib/validate.js]: An example schema would be very useful here.

**Comment by shane-tomlinson** [comment]
Unit and functional tests all pass. Local Sync sign up still works. Local firstrun flow still works. 

I like it. Thanks @philbooth! Can you add the two requested bits of documentation and merge away?

r=@shane-tomlinson
