### PR TITLE
fix(experiment): Add the `treatment-link` to token code experiment

### LINKED ISSUE #5843: Add sign-in link treatment to tokenCode experiment
In my haste, I didn't realize that there were two treatment groups in this experiment per https://docs.google.com/document/d/1xQtCGBJ9XZuF1q9faZV3YIiOnxomQMHKiTP62YSf3v8/edit.

We should add the `treatment1` (sign-in link treatment) and corresponding tests. Ideally, would like to target a 104 point release for this.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #5843

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

File: app/scripts/views/mixins/signin-mixin.js [hunk 1]
```diff
@@ -47,12 +47,17 @@ define(function (require, exports, module) {
...
-          // if so, override the verification method to use email-2fa
+          // if so, override to use the correct verification method. `email-2fa` sends
+          // an email with the verification code and `email` sends a confirmation link.
           let verificationMethod;
-          if (this.getTokenCodeExperimentGroup && this.getTokenCodeExperimentGroup() === 'treatment') {
+          if (this.getTokenCodeExperimentGroup && this.getTokenCodeExperimentGroup() === 'treatment-code') {
             verificationMethod = VerificationMethods.EMAIL_2FA;
           }
 
+          if (this.getTokenCodeExperimentGroup && this.getTokenCodeExperimentGroup() === 'treatment-link') {
```
Comment (philbooth) [inline app/scripts/views/mixins/signin-mixin.js]: As these two conditions compare the same string, is it worth bringing them together as a `switch` statement inside a single `if (this.getTokenCodeExperimentGroup) ...` condition?
