### PR TITLE
fix(client): propagate flow data to confirm signin view

### LINKED ISSUE #3984: signin verification link different if the user clicks "resend"
If the user clicks "resend" on the "confirm this sign-in" screen, the verification link is different in both emails. Here are the links as reported by `./pm2 logs 0`

The `code` and `uid` are the same, the resume token is different.

screen shot 2016-07-26 at 16 48 25

The first decodes to:

```json
{
  "entrypoint": "menupanel",
  "flowBegin": 1469547963708,
  "flowId": "69b77443d51a8f05aff8614f19b8776d247ba6d7a6d650f9c611b564762445b9",
  "resetPasswordConfirm": true,
  "uniqueUserId": "44fc34df-4af5-4270-b143-f3b5e84d44ca",
  "utmCampaign": null,
  "utmContent": null,
  "utmMedium": null,
  "utmSource": null,
  "utmTerm": null
}
```

The second to:

```json
{
  "entrypoint": "menupanel",
  "resetPasswordConfirm": true,
  "uniqueUserId": "44fc34df-4af5-4270-b143-f3b5e84d44ca",
  "utmCampaign": null,
  "utmContent": null,
  "utmMedium": null,
  "utmSource": null,
  "utmTerm": null
}
```

The first contains `flowBegin` and `flowId`, the 2nd doesn't.

cc @philbooth - is this problematic for your metrics?

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #3984.

The resume token mixin depends on `this.flow` in order to serialise flow data into the resume token. Prior to this change, only the signin and signup views had a model available as `this.flow`. With this change, it means the confirm views also have that model.

@shane-tomlinson, low-priority r?

### CODE REVIEW

**Comment by philbooth** [comment]
Pushed a second commit to apply the same fix to signup.

File: app/scripts/views/mixins/signup-mixin.js [hunk 1]
```diff
@@ -82,7 +82,8 @@ define(function (require, exports, module) {
       return this.invokeBrokerMethod('afterSignUp', account)
         .then(function () {
           self.navigate('confirm', {
```
Comment (vladikoff) [inline app/scripts/views/mixins/signup-mixin.js]: nit: convert to `() =>` and get rid of `self` to match the signin-mixin?

**Comment by shane-tomlinson** [comment]
LGTM @philbooth - the "resend" links for both signin and signup are the same as the original. I'll leave it up to you whether you think password reset should contain the flow information.

**Comment by philbooth** [comment]
@shane-tomlinson, updated to include password reset. Could I get one (hopefully) last r?

File: app/scripts/views/mixins/password-reset-mixin.js [hunk 2]
```diff
@@ -24,18 +24,17 @@ define(function (require, exports, module) {
...
      */
     resetPassword: function (email) {
-      var self = this;
-
       var account = this.user.initAccount({ email: email });
       return account.resetPassword(
-        self.relier,
+        this.relier,
         {
-          resume: self.getStringifiedResumeToken()
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/password-reset-mixin.js]: Whenever I run this manually and step into `getStringifiedResumeToken`, `this.flow` is always `undefined`. I think you either need to use the `flow` model passed from the signin view (if passed) or create one locally?

**Comment by philbooth** [comment]
Removed the password reset stuff.

After digging into it some more, I realise that to work sanely we'd need to treat `/reset_password` as the start of a new flow, which is not specced behaviour. It seems preferable for this PR to focus on fixing the known problem of the resume token not containing flow metadata when you resend the confirmation emails.

I've opened a separate issue to tackle the `/reset_password` stuff. It's mission creep from the original issue description anyway.

@shane-tomlinson r?
