### PR TITLE
fix(tests): Fix the communication preferences tests.

### LINKED ISSUE #3357: communication preferences functional tests frequently fail locally.
```
× firefox on any platform - communication preferences - opt in to the marketing email (30.011s)
CancelError: Timeout reached on firefox on any platform - communication preferences - opt in to the marketing email
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.target.(anonymous function) [as click]  <node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.opt in to the marketing email [as test]  <tests/functional/email_opt_in.js:96:12>
  at <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout  <timers.js:92:15>
× firefox on any platform - communication preferences - opt-in with a plus sign in the email address (30.017s)
CancelError: Timeout reached on firefox on any platform - communication preferences - opt-in with a plus sign in the email address
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.target.(anonymous function) [as click]  <node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.opt-in with a plus sign in the email address [as test]  <tests/functional/email_opt_in.js:128:12>
  at <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout  <timers.js:92:15>
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
PR #3088 sped up the rendering of the settings page but introduced
a regression in the communication preferences tests. Communication
preferences are re-rendered after an XHR request to Basket is made
to check whether the user has opted in to email communcations. The
Selenium tests moved to quickly and clicked the "open panel" button
using an element that was sometimes no longer in the DOM (sometimes meaning
sometimes the response to basket took a while and the prefs opened,
other times basket finished early and Selenium's reference was stale).

This PR fixes this by adding a `basket-ready` class to the
`#communication-preferences` element when rendering is complete.
Selenium looks for this class name, and then continues.

fixes #3357

@philbooth or @vladikoff - r?

### CODE REVIEW

File: app/scripts/views/settings/communication_preferences.js [hunk 1]
```diff
@@ -39,6 +39,14 @@ define(function (require, exports, module) {
       return self._marketingEmailPrefs;
     },
 
+    // The view is rendered twice to avoid delaying the settings page load.
+    // The first render is done without querying Basket for the user's emai
```
Comment (vladikoff) [inline app/scripts/views/settings/communication_preferences.js]: `emai` -> `email`

**Comment by vladikoff** [comment]
Looks good to me :+1:
