### PR TITLE
fix(tests): Fix functional tests when run against a remote server.

### LINKED ISSUE #3174: `latest` functional test failures - many searches for `.success` fail
STR

1. npm run test-latest
1. Watch the failures.
1. Look for the source of the failure.
1. For me, the primary culprit is the search for `.success`

### LINKED ISSUE #3182: `latest` functional test failures - checking for `#legal-copy` text
```
× firefox on any platform - legal - start at privacy page (0.764s)
AssertionError: expected 0 to be truthy
  at Assertion.<anonymous>  <node_modules/intern/node_modules/chai/chai.js:532:10>
  at Assertion.Object.defineProperty.get  <node_modules/intern/node_modules/chai/chai.js:3515:29>
  at Function.assert.ok  <node_modules/intern/node_modules/chai/chai.js:1990:31>
  at Command.<anonymous>  <tests/functional/legal.js:81:20>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.start at privacy page [as test]  <tests/functional/legal.js:79:12>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
* The `.success` and `.error` messages on the `/settings` page are hidden after
  a short period. This caused the functional tests to frequently fail when
  looking for the .success message. Instead of checking whether the .success
  and `.error` messages are still visible, check if they *were visible*. The
  client code will add a `[data-shown]` attribute to the elements. This
  attribute is searched for by the functional tests, and then removed, so
  subsequent messages can be displayed and checked for in the same test.
* The legal pages load their content using XHR requests, which can take time.
  The tests were sometimes failing because the `#legal-copy` contents were
  empty. The new sequence is add a `[data-shown]` attribute to `#legal-copy`
  after the contents are written, and search for the `data-shown` attribute in
  the functional tests.

fixes #3174
fixes #3182

### CODE REVIEW

File: app/scripts/views/base.js [hunk 1]
```diff
@@ -58,11 +67,20 @@ function (Cocktail, _, Backbone, Raven, $, p, AuthErrors,
...
 
-    this.$('.error').slideDown(EPHEMERAL_MESSAGE_ANIMATION_MS);
+    // the 'data-was-shown' attribute value is added so the functional tests
+    // can find out if the error message was successfully shown, even
+    // if the element is then hidden. In the functional tests,
+    // testErrorWasShown removes the attribute so multiple checks for the
+    // element can take place in the same test.
+    $error
+      .slideDown(EPHEMERAL_MESSAGE_ANIMATION_MS)
+      .attr('data-was-shown', 'true');
```
Comment (shane-tomlinson) [inline app/scripts/views/base.js]: Maybe instead of `data-was-shown` here and `data-ready` in `legal_copy.js`, use `data-visible` in both to stay consistent.

Comment (shane-tomlinson) [inline app/scripts/views/base.js]: or `data-shown`

**Comment by shane-tomlinson** [comment]
@vladikoff - r?
