### PR TITLE
fix(form): Catch the form validation errors, no more console message.

### LINKED ISSUE #6025: Form input validation throws `Uncaught (in promise) undefined`
Noticed this while testing https://github.com/mozilla/fxa-content-server/pull/5992. Any input field will throw `Uncaught (in promise) undefined`, if `validateAndSubmit` is fails.

screen shot 2018-04-05 at 4 38 24 pm

Not sure if this is expected behavior, but seemed odd.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Create an `onFormSubmit` function that catches and swallows the error.
The error will already have been logged, no need to do anything else.

fixes #6025 

@mozilla/fxa-devs - r? I reformatted the modules, easiest to review with ?w=1

### CODE REVIEW

File: app/scripts/views/form.js [hunk 1]
```diff
@@ -17,138 +17,140 @@
...
-      return ! $submitEl.hasClass('disabled') && ! $submitEl.attr('disabled');
-    },
+  isFormEnabled () {
+    const $submitEl = this.$('button[type=submit]');
+    return ! $submitEl.hasClass('disabled') && ! $submitEl.attr('disabled');
+  },
+
+  onFormSubmit () {
+    return this.validateAndSubmit()
+      // drop the error on the ground, it'll alredy be logged.
```
Comment (philbooth) [inline app/scripts/views/form.js]: Typo: `already`
