### PR TITLE
fix(test): Fix the "delete oauth sessions" test.

### LINKED ISSUE #4968: functional test failure - oauth settings clients - rp listed in apps, can be deleted
> StaleElementReference: [POST http://localhost:4444/wd/hub/session/78e04e71-beb7-4b37-b570-135dc9f0165c/element/3066/click / {}] The element reference is stale. Either the element is no longer attached to the DOM or the page has been refreshed.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: '2c2ab056496c', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, firefox_binary=/home/teamcity/firefox-channels/latest/en-US/firefox/firefox-bin, acceptSslCerts=false, processId=10254, browserVersion=50.1.0, platformVersion=4.4.41-36.55.amzn1.x86_64, name=tests/intern_functional_full, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux, firefox_profile=UEsDBBQACAgIAHyak0oAAAAAAAAAA...}]
Session ID: e4013df7-9ca3-4c75-8695-c319b844bfee
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:191:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:148:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.rp listed in apps, can be deleted [as test]  <tests/functional/oauth_settings_clients.js:90:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>

### PR DESCRIPTION
**Pull request by shane-tomlinson**
With the introduction of web sessions in the UI, the OAuth session
selectors were no longer valid. This fixes that.

fixes #4968

Are web sessions enabled in stage and prod for these tests to pass there?

@vladikoff - r?

### CODE REVIEW

File: tests/functional/oauth_settings_clients.js [hunk 1]
```diff
@@ -84,12 +84,18 @@ define([
         // second app should show up using 'refresh'
         .then(click('.clients-refresh'))
 
-        .then(testElementExists('li.client-oAuthApp:nth-child(2)'))
+        // NOTE - these selectors are brittle to updates in the DOM location.
+        // I haven't been able to figure out a better way of targeting the
+        // elements. I tried using [data-name], but 123done's name locally
+        // is 123Done, and on latest is 123done.
```
Comment (vladikoff) [inline tests/functional/oauth_settings_clients.js]: `locally is 123Done, and on latest is 123done.` wat

Comment (shane-tomlinson) [inline tests/functional/oauth_settings_clients.js]: > wat

Yeah. That's what I said.

**Comment by vladikoff** [comment]
1 2 3 Done!
