### PR TITLE
fix(sms): Fix the "send_sms - learn more" functional test.

### LINKED ISSUE #4891: Failing functional test -  send_sms - learn more
The `#tabzilla` ID is no longer there.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
The `#tabzilla` ID is no longer available, use `#websites-notice` instead.

fixes #4891

@mozilla/fxa-devs - r?

### CODE REVIEW

File: tests/functional/send_sms.js [hunk 1]
```diff
@@ -22,7 +22,7 @@
    const SELECTOR_400_HEADER = '#fxa-400-header';
    const SELECTOR_400_ERROR = '.error';
    const SELECTOR_LEARN_MORE = 'a#learn-more';
-   const SELECTOR_LEARN_MORE_HEADER = '#tabzilla';
+   const SELECTOR_LEARN_MORE_HEADER = '#websites-notice';
```
Comment (philbooth) [inline tests/functional/send_sms.js]: The link itself navigates to a `#campaigns` fragment identifier. Would it make more sense to look for that one than this one from the body element?

**Comment by philbooth** [comment]
@shane-tomlinson looks good, r+. I wonder if we should check for the fragment identifier that is actually part of `LEARN_MORE_LINK` instead, i.e. `#campaigns`. It seems like a more meaningful test then?

**Comment by vladikoff** [comment]
Merging this because it is blocking PRs
