### PR TITLE
fix(client): Fix incorrect OAuth errors in error table.

### LINKED ISSUE #2830: oauth server errors errno 108 & 109 are incorrect and do not match spec
Found in https://github.com/mozilla/fxa-oauth-server/issues/314.
Ref https://github.com/mozilla/fxa-oauth-server/issues/315.

OAuth server errors w/ [errno 108 & 109](https://github.com/mozilla/fxa-content-server/blob/9ec6b1812e76fa9576462bd9c4cebf4544698f9f/app/scripts/lib/oauth-errors.js#L46-L53) do not match the [API spec](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors). Whenever a relier requests a scope they do not have access to, the user sees an unhelpful `Invalid request signature` error.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Errors 108 and 109 were incorrect in the OAuth error table
according to the spec at
https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors.

This fixes those errors and ensure invalid request parameters
are correctly interpolated.

fixes #2830

### CODE REVIEW

File: app/tests/spec/lib/oauth-errors.js [hunk 1]
```diff
@@ -60,19 +60,30 @@ function (chai, OAuthErrors) {
...
 
-      it('context returns param', function () {
+      it('`MISSING_PARAMETER` returns object w/ `param`', function () {
         var err = OAuthErrors.toError('MISSING_PARAMETER');
         err.param = 'param';
         assert.equal(OAuthErrors.toInterpolationContext(err).param, 'param');
       });
 
-      it('context catches data exception', function () {
-        assert.equal(Object.keys(OAuthErrors.toInterpolationContext(undefined)).length, 0);
```
Comment (rfk) [inline app/tests/spec/lib/oauth-errors.js]: Does `toInterpolationContext(undefined)` no longer need to be tested?

**Comment by rfk** [comment]
Otherwise :+1:

File: app/tests/spec/lib/oauth-errors.js (hunk 1 above)
Comment (shane-tomlinson) [inline app/tests/spec/lib/oauth-errors.js]: Not really, the test's intent was to catch malformed server responses and ensure exceptions decoding server responses aren't propagated. I renamed the test to `malformatted server responses are handled gracefully`, which should be `malformed`. I can add an `undefined` input test if you think it's worthwhile.

Comment (rfk) [inline app/tests/spec/lib/oauth-errors.js]: Sounds fine, just making sure it wasn't accidentally lost :-)

Comment (shane-tomlinson) [inline app/tests/spec/lib/oauth-errors.js]: test for `undefined` re-added.
