### PR TITLE
fix(client): Suppress spurious `login` messages to the browser.

### LINKED ISSUE #3078: Spurious 'login' message when navigating to /settings with an unverified account
I see a spurious WebChannel 'login' message when I load `accounts.firefox.com/settings?context=fx_fennec_v1&service=sync&entrypoint=preferences`.  The 'login' message is malformed; it doesn't include keys.  Is this intended?  Do clients just need to ignore it?

I witnessed this while developing Firefox for iOS as well.

@shane-tomlinson can you comment or re-direct?

The log below also shows the 'login' message appearing before 'loaded', which is counter-intuitive.  (Of course, there's no spec, per se.)

D GeckoFxAccounts(26989)      FxAccountsWebChannel message received, command: fxaccounts:login
W GeckoAccounts(26989)        Got exception updating Firefox Account from JSON; ignoring.
W GeckoAccounts(26989)        org.mozilla.gecko.util.NativeJSObject$InvalidPropertyException: Property does not exist
W GeckoAccounts(26989)        	at org.mozilla.gecko.util.NativeJSObject.getString(Native Method)
W GeckoAccounts(26989)        	at org.mozilla.gecko.AccountsHelper.handleMessage(AccountsHelper.java:150)
W GeckoAccounts(26989)        	at org.mozilla.gecko.EventDispatcher.dispatchEvent(EventDispatcher.java:223)
W GeckoAccounts(26989)        	at org.mozilla.gecko.GeckoAppShell.handleGeckoMessage(GeckoAppShell.java:2275)
W GeckoAccounts(26989)        	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
W GeckoAccounts(26989)        	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:436)
E GeckoFxAccounts(26989)      Could not update Firefox Account from JSON: org.mozilla.gecko.util.NativeJSObject$InvalidPropertyException: Property does not exist
D GeckoFxAccounts(26989)      FxAccountsWebChannel message received, command: fxaccounts:loaded
D GeckoFxAccounts(26989)      Got LOADED message!

### PR DESCRIPTION
**Pull request by shane-tomlinson**
If the user signs up but does not verify their account,
then visit `/` or `/settings`, they are redirected to `/confirm`
which attempts to notify the browser of login.

Neither `unwrapBKey` and `keyFetchToken` are persisted to disk.

If `/confirm` is shown in a tab other than the original tab,
`notifyBrowserOfLogin` is called with an account without these
fields. The browser can't do anything without this information,
so don't actually send the message.

fixes #3078 

@vladikoff or @zaach - r?

### CODE REVIEW

File: tests/functional/settings.js [hunk 1]
```diff
@@ -82,39 +81,26 @@ define([
...
-        .end()
+      return FunctionalHelpers.openPage(self, url, '#fxa-signin-header')
+        .execute(listenForFxaCommands)
 
-        .findByCssSelector('button[type="submit"]')
-          .click()
-        .end()
 
         .then(function () {
-          return testIsBrowserNotifiedOfLogin(self, email);
```
Comment (shane-tomlinson) [inline tests/functional/settings.js]: This PR uncovered the fact that this test was incorrect, and because of lucky timing, not failing. The account used to sign in was verified, yet `testIsBrowserNotifiedOfLogin` should have been failing because by default, it checks if the account is unverified.

**Comment by vladikoff** [comment]
:+1:
