### PR TITLE
fix(client): Mozilla Payments flow is not considered an iframe.

### LINKED ISSUE #2607: Marketplace: Reset PIN option does not work on Android
Pulled over from https://bugzilla.mozilla.org/show_bug.cgi?id=1170574

> Steps to reproduce:
> 1. Load MP-stage on your Android device (https://marketplace.allizom.org/)
> 2. Try to purchase an app (Test App(chocolate))
> 3. Click “Forgot your PIN?” link 
> 4. Click “Reset” blue button
> 
> Expected results
> A  “Sign in to continue” window is displayed and user must sign in with valid credentials to continue to MP - Payments Stage.
> 
> Actual results:
> “500 Error” message is displayed.
> 
> Notes/Issues:
> Issue is not reproducing on Desktop or FF OS.
> Verified on FF41(Android 4.2.1). Issue is reproducing on MP-stage.
> Screenshot for this issue: http://screencast.com/t/Yv1wCrD90C1
> Ashes ID: c3901

ref #2150, #2151, #2364, #2606

### PR DESCRIPTION
**Pull request by shane-tomlinson**
The Mozilla Payments flow on Fennec uses a trusted iframe with
the `mozbrowser` attribute to open FxA. Fennec should report
that window.top === window when the `mozbrowser` attribute is used,
but it does not.

fixes #2607 

@rfk, @andymckay

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
When I open the Reset PIN flow, then use the WebIDE to change the URL of the iframe to my local content-server, I now see this:

screenshot_2015-06-17-14-00-01

Originally I saw the 500 screen mentioned in the bugzilla bug.

@andymckay - is there any way to have Fennec open my local content server instead of the production FxA? I have no idea how to really test this otherwise.

**Comment by shane-tomlinson** [comment]
FWIW, I'm *not* happy with this fix, this is the smallest possible patch I could think of that worked around the problem. I suppose it's no worse than what already existed, but relying on window.name is so unbelievably gross.

**Comment by andymckay** [comment]
I think the only way to get it to connect to a local server is to change this string here:

https://github.com/mozilla/webpay/search?utf8=%E2%9C%93&q=FXA_OAUTH_URL&type=Code

Which I think means running your own Marketplace payments stack.

If its easy to get this onto https://oauth-stable.dev.lcip.org, we can then test this on the Marketplace dev server at marketplace-dev.allizom.org, since that connects to stable. Running Marketplace locally is a bit easier since it's all dockerised, but this might be easiest route right now.

File: app/scripts/lib/environment.js [hunk 1]
```diff
@@ -64,9 +64,16 @@
...
-      // to use the iframe flow. about:accounts sets window.name = 'remote'
-      return !! (win.top && win.top !== win && win.name !== 'remote');
+      return !! (
+                 win.top && win.top !== win &&
+                 // about:accounts places FxA into an iframe, but is not
+                 // considered to use the iframe flow. about:accounts
+                 // sets window.name = 'remote'
+                 win.name !== 'remote' &&
+                 // Mozilla Payments uses a trusted iframe
+                 // with window.name = 'payflow'. See #2607
```
Comment (pdehaan) [inline app/scripts/lib/environment.js]: Yeah, we almost need to add a big `HACK: ` disclaimer to the front of that comment on line 73.

File: app/tests/spec/lib/environment.js [hunk 2]
```diff
@@ -97,6 +97,12 @@ define([
         windowMock.name = 'remote';
         assert.isFalse(environment.isFramed());
       });
+
+      it('returns `false` if the window\'s name is `payflow`', function () {
+        windowMock.top = new WindowMock();
+        windowMock.name = 'payflow';
```
Comment (pdehaan) [inline app/tests/spec/lib/environment.js]: Add a line comment to issue #2607 here (or on line 100) for future versions of ourselves to remember why we're hardcoding a window name in this test?

**Comment by shane-tomlinson** [comment]
> I think the only way to get it to connect to a local server is to change this string here:
>
> https://github.com/mozilla/webpay/search?utf8=%E2%9C%93&q=FXA_OAUTH_URL&type=Code
> 
> Which I think means running your own Marketplace payments stack.
>
> If its easy to get this onto https://oauth-stable.dev.lcip.org, we can then test this on the Marketplace 
> dev server at marketplace-dev.allizom.org, since that connects to stable. Running Marketplace locally 
> is a bit easier since it's all dockerised, but this might be easiest route right now.

Hmm... Probably not pushing to stable.

Is there any way I can force Fennec to use my local fxa-stack when it redirects here: https://dxr.mozilla.org/mozilla-central/source/mobile/android/components/PaymentsUI.js#112?

Is there a config option I can set somewhere that allows me to change the value of `aPaymentFlowInfo.uri`?

File: app/scripts/lib/environment.js [hunk 3]
```diff
@@ -64,9 +64,16 @@
...
+                 win.name !== 'payflow'
```
Comment (rfk) [inline app/scripts/lib/environment.js]: I wonder if we should `console.log` or something when one of these hacky checks triggers, to assist debugging for far-future users who accidentally collide with the window-naming scheme here.

File: app/scripts/lib/environment.js [hunk 4]
```diff
@@ -67,9 +67,29 @@
...
+      //   See #2607
+
+      // use a hash instead of an array and array.indexOf
+      // b/c this module can only use ES3.
+      var nativeNames = {
+        remote: true,
+        payflow: true
+      };
+
+      var isNativelyEmbedded = nativeNames[win.name];
```
Comment (shane-tomlinson) [inline app/scripts/lib/environment.js]: @rfk - w.r.t. logging whether the name is matched. This function can be called multiple times, a log here would end up being pretty chatty. We could do it on startup though, or add a new function to this `isNativelyEmbedded` or something like that which is called from app-start.js and only run once.

File: app/tests/spec/lib/environment.js [hunk 5]
```diff
@@ -94,10 +94,20 @@ define([
...
       it('returns `false` if the window\'s name is `remote`', function () {
+        // `name=remote` is used by `about:accounts` by Fx Desktop. Do not
+        // consider this framed.
         windowMock.top = new WindowMock();
         windowMock.name = 'remote';
         assert.isFalse(environment.isFramed());
       });
+
+      it('returns `false` if the window\'s name is `payflow`', function () {
+        // `name=payflow` is used by Marketplace on Fx for Android during
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/environment.js]: @pdehaan - added the docs.

**Comment by shane-tomlinson** [comment]
@ncalexan, @andymckay - so... This needs to be tested, on device. Any ideas that don't involve pushing to stable or setting up the entire payments flow?

**Comment by vladikoff** [comment]
Moving to Train 41 so we can test spend some time testing this out before merging

**Comment by TDA** [comment]
@shane-tomlinson Looks good to me Shane :) I couldn't find anything wrong at all.

**Comment by rfk** [comment]
Looks like we're blocked on testing here, and I don't want this to become a rabbit-hole for anyone.  @andymckay do you think we could split the duties 50/50 here?  If Shane gets this deployed to a testing server, can your tem deploy a corresponding marketplace stack that points to that deployment, and we can then follow the instructions in the bug to confirm fix on a phone?

**Comment by shane-tomlinson** [comment]
Setting up the server now, it is going to be available at https://mp-android.dev.lcip.org

A user.js file that can be used on FxDesktop is:
```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */



user_pref("services.sync.log.appender.file.logOnSuccess", true);
user_pref("identity.fxaccounts.auth.uri", "https://mp-android.dev.lcip.org/auth/v1");
user_pref("identity.fxaccounts.remote.force_auth.uri", "https://mp-android.dev.lcip.org/force_auth?service=sync&context=fx_desktop_v1");
user_pref("identity.fxaccounts.remote.signin.uri", "https://mp-android.dev.lcip.org/signin?service=sync&context=fx_desktop_v1");
user_pref("identity.fxaccounts.remote.signup.uri", "https://mp-android.dev.lcip.org/signup?service=sync&context=fx_desktop_v1");
user_pref("identity.fxaccounts.settings.uri", "https://mp-android.dev.lcip.org/settings");
user_pref("identity.fxaccounts.remote.webchannel.uri", "https://mp-android.dev.lcip.org/");
user_pref("services.sync.tokenServerURI", "https://mp-android.dev.lcip.org/syncserver/token/1.0/sync/1.5");

user_pref("general.warnOnAboutConfig", false);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
```

I'm not sure what scheme Fennec uses to override prefs.

**Comment by shane-tomlinson** [comment]
so... slow... to set up a server.

**Comment by shane-tomlinson** [comment]
@andymckay - it took 3 days to get the server up and running, but it's up on https://mp-android.dev.lcip.org.

**Comment by andymckay** [comment]
Ok, pinged you in IRC but might have missed you, does it have the same client id, secret as stable? Can I just switch the URL? Or do we need to create those?

**Comment by andymckay** [comment]
This worked for me on marketplace-dev.

**Comment by rfk** [comment]
> This worked for me on marketplace-dev.
:shipit:

**Comment by shane-tomlinson** [comment]
@andymckay is awesome. Thank you!
