### PR TITLE
fix(config): copy 'local.json-dist' to 'local.json' if it don't exists

### LINKED ISSUE #2619: npm start should copy `local.json` from local.json-dist if that does not exist
`npm start` should copy `local.json` from local.json-dist if that does not exist

The goal behind this is to reduce the steps for developers to start the server

### PR DESCRIPTION
**Pull request by npestana**
Create 'scripts/check-config.js' to check if 'local.json' don't exists.
This script will run on 'npm start' before 'grant server'.

Closes #2619

### CODE REVIEW

File: scripts/check-config.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+#!/usr/bin/env node
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+const fs = require('fs');
+const path = require('path');
+
+const RELATIVE_FILE = 'server/config/local.json';
```
Comment (vladikoff) [inline scripts/check-config.js]: Use `path.join` here

https://nodejs.org/docs/v0.10.0/api/path.html#path_path_join_path1_path2

File: package.json [hunk 2]
```diff
@@ -3,7 +3,7 @@
   "version": "0.46.0",
   "description": "Firefox Accounts Content Server",
   "scripts": {
-    "start": "grunt server",
+    "start": "node scripts/check-config && grunt server",
```
Comment (vladikoff) [inline package.json]: rename `check-config` to `check-local-config` so it is more descriptive

File: scripts/check-config.js [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+const CONFIG_FILE = path.resolve(__dirname, '..', RELATIVE_FILE);
+
+if (!fs.existsSync(CONFIG_FILE)) {
```
Comment (vladikoff) [inline scripts/check-config.js]: Here also check if `process.env.CONFIG_FILES` exists. 
  if it exists (defined) then do **not** copy the local.json file. This is an extra precaution, CONFIG_FILES var overrides everything else

See similar example here:
https://github.com/mozilla/fxa-content-server/blob/f75b7165f19055809a4ed28ce0091ebc53575f2b/grunttasks/selectconfig.js#L21

File: scripts/check-local-config.js [hunk 4]
```diff
@@ -0,0 +1,16 @@
+#!/usr/bin/env node
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+var fs = require('fs');
+var path = require('path');
+
+var RELATIVE_FILE = path.join('server', 'config', 'local.json');
+
```
Comment (vladikoff) [inline scripts/check-local-config.js]: Nice! this looks like it ready to go! 

Squash the 2 commits into one and remove this extra line break while you are at it.

R+.

**Comment by npestana** [comment]
@vladikoff line break removed and commits squashed.

**Comment by vladikoff** [comment]
@npestana Excellent, thank you so much! :star:
