### PR TITLE
fix(cookies): redirect to /cookies_disabled if session/local storage is disabled, fixes #2480

### LINKED ISSUE #2480: Blocking all cookies throws 500
image

image

### Expected

Better messaging that cookies are disabled and the user should enable them?

### PR DESCRIPTION
**Pull request by philbooth**
Fix to [the previous PR](https://github.com/mozilla/fxa-content-server/pull/2707), copying the `disable_local_storage` query parameter hack so that the functional tests can simulate disabled local storage.

### CODE REVIEW

File: app/scripts/lib/app-start.js [hunk 1]
```diff
@@ -652,22 +650,12 @@ function (
...
-        }
-
-        return self._configLoader.areCookiesEnabled(false, self._window)
-            .then(function (areCookiesEnabled) {
-              if (! areCookiesEnabled) {
-                return 'cookies_disabled';
-              }
-            });
-      });
+      if (
```
Comment (shane-tomlinson) [inline app/scripts/lib/app-start.js]: nit: formatting. We go somewhere in the middle of verbose and terse, depending on the repo. We are a bit more terse in this repo and often combine lines that other repos do not.

```js
if (this._window.location.pathname !== '/cookies_disabled' &&
   ! this._storage.isLocalStorageEnabled(this._window)) {
```

File: app/scripts/router.js [hunk 2]
```diff
@@ -274,7 +273,7 @@ function (
 
             // back is enabled after the first view is rendered or
             // if the user re-starts the app.
-            self.canGoBack = self.window.sessionStorage.canGoBack = true;
```
Comment (shane-tomlinson) [inline app/scripts/router.js]: I totally dig ditching this variable. One source of truth.

File: app/tests/mocks/storage.js [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+define(function () {
+  'use strict';
+
+  function StorageMock (options) {
+    options = options || {};
+
+    this.isSessionStorageEnabled = function () {
```
Comment (shane-tomlinson) [inline app/tests/mocks/storage.js]: Another possible approach is to create a `Storage` instance and override these functions as needed using sinon.

File: app/tests/spec/lib/app-start.js [hunk 4]
```diff
@@ -82,33 +92,26 @@ function (chai, sinon, Raven, AppStart, Session, Constants, p, Url, OAuthErrors,
...
+      it('does not redirect', function () {
+        sinon.spy(routerMock, 'navigate');
+        return appStart.startApp()
+          .then(function () {
+            assert.isFalse(routerMock.navigate.called);
+          });
+      });
 
+      it('redirects to /cookies_disabled if local storage is disabled', function () {
+        storageAbility.isLocalStorageEnabled = false;
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/app-start.js]: This is where sinon is handy, you could do something like:
```js
sinon.stub(storage, 'isLocalStorageEnabled', function () {
  return false;
});
```

We started moving away from creating new configurable mock objects once we realized we could do that.

File: app/scripts/router.js [hunk 5]
```diff
@@ -137,10 +137,8 @@ function (
       this.formPrefill = options.formPrefill;
       this.notifications = options.notifications;
       this.able = options.able;
+      this.storage = Storage.factory('sessionStorage', this.window);
```
Comment (shane-tomlinson) [inline app/scripts/router.js]: Not for this PR because has been a problem for 2 years - the mixture of private vars with the `_` prefix and those without causes me grief.

File: app/tests/spec/lib/app-start.js [hunk 6]
```diff
@@ -82,33 +92,26 @@ function (chai, sinon, Raven, AppStart, Session, Constants, p, Url, OAuthErrors,
...
-        });
+      it('does not redirect', function () {
+        sinon.spy(routerMock, 'navigate');
+        return appStart.startApp()
+          .then(function () {
+            assert.isFalse(routerMock.navigate.called);
+          });
+      });
 
+      it('redirects to /cookies_disabled if local storage is disabled', function () {
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/app-start.js]: Can you combine `local storage` to `localStorage` for greppability?

File: app/scripts/lib/app-start.js [hunk 7]
```diff
@@ -543,29 +544,26 @@ function (
...
+        // If pushState cannot be used, Backbone falls back to using
+        // the hashchange. Put the initial pathname onto the hash
+        // so the correct page loads.
+        this._window.location.hash = this._window.location.pathname;
+      }
+
+      // If a new start page is specified, do not attempt to render
+      // the route displayed in the URL because the user is
+      // immediately redirected
+      var startPage = this._selectStartPage();
```
Comment (shane-tomlinson) [inline app/scripts/lib/app-start.js]: I like the flattening. A lot. Much easier to read.

**Comment by vladikoff** [comment]
Nit: don't put `fixes #2480` in the title. 

Add a new line blank line after the commit message and then `fixes #2480` or put it the pull request description.

Something like this:
image

File: app/scripts/router.js (hunk 5 above)
Comment (philbooth) [inline app/scripts/router.js]: Probably unhelpful but, imho, using naming conventions to imply privacy rather than enforcing it using closures is the real source of your grief here. :)

**Comment by philbooth** [comment]
@shane-tomlinson && @vladikoff: Thanks for your comments, have fixed and pushed.

File: app/scripts/lib/app-start.js [hunk 8]
```diff
@@ -543,29 +544,26 @@ function (
...
-          });
+      // The IFrame cannot use pushState or else a page transition
+      // would cause the parent frame to redirect.
+      var usePushState = ! this._isInAnIframe();
+
+      if (! usePushState) {
+        // If pushState cannot be used, Backbone falls back to using
+        // the hashchange. Put the initial pathname onto the hash
+        // so the correct page loads.
+        this._window.location.hash = this._window.location.pathname;
```
Comment (shane-tomlinson) [inline app/scripts/lib/app-start.js]: Not for this PR, but history and routing seem intimately related. Setting up history seems like a task for the router to me.
