### PR TITLE
fix(csp): adjust CSP validation for edge cases

### LINKED ISSUE #4886: CSP reports being rejected for not containing `original-policy`
See https://sentry.prod.mozaws.net/operations/content-express-server-prod/issues/382607/

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4886

@shane-tomlinson r?

### CODE REVIEW

File: server/lib/routes/post-csp.js [hunk 1]
```diff
@@ -20,19 +20,20 @@ const BODY_SCHEMA = {
...
+    // Allow 'about:srcdoc', see https://bugzilla.mozilla.org/show_bug.cgi?id=1073952#c22
+    'document-uri': URL_TYPE.required().allow('about:srcdoc'),
      // CSP 2 required, but not always sent
     'effective-directive': STRING_TYPE.optional(),
     // CSP 2 optional
     'line-number': INTEGER_TYPE.min(0).optional(),
-    // CSP 2, 3 required
-    'original-policy': STRING_TYPE.required(),
+    // CSP 2, 3 required. However some reports do not contain it.
+    'original-policy': STRING_TYPE.required().optional(),
```
Comment (shane-tomlinson) [inline server/lib/routes/post-csp.js]: Can you replace the `.required()` with `.optional()`?

File: server/lib/routes/post-csp.js [hunk 2]
```diff
@@ -20,19 +20,20 @@ const BODY_SCHEMA = {
   'csp-report': joi.object().keys({
     // CSP 2, 3 required
     // `eval` and `inline` are specified in CSP 3 and sent by Chrome
-    'blocked-uri': URL_TYPE.allow('eval').allow('inline').allow('self').allow('').optional(),
+    'blocked-uri': URL_TYPE.allow('eval').allow('inline').allow('self').allow('asset').allow('').optional(),
```
Comment (shane-tomlinson) [inline server/lib/routes/post-csp.js]: Can you add `data` too?

I found this one:

```js
{csp-report: {blocked-uri: data, disposition: enforce, document-uri: https://accounts.firefox.com/complete_reset_password, effective-directive: font-src, original-policy: connect-src 'self' https://api.accounts.firefox.com https://oauth.accounts.firefox.com https://profile.accounts.firefox.com https://accounts.firefox.com; font-src 'self' https://accounts.cdn.mozilla.net; img-src 'self' data: https://secure.gravatar.com https://firefoxusercontent.com https://accounts.cdn.mozilla.net; media-src blob:; object-src 'none'; report-uri /_/csp-violation; script-src 'self' https://accounts.cdn.mozilla.net; style-src 'self' 'sha256-9n6ek6ecEYlqel7uDyKLy6fdGNo3vw/uScXSq9ooQlk=' https://accounts.cdn.mozilla.net, referrer: , status-code: 0, violated-directive: font-src}}
```

File: server/lib/routes/post-csp.js (hunk 1 above)
Comment (vladikoff) [inline server/lib/routes/post-csp.js]: woops! good find
