### PR TITLE
fix(metrics): measure how helpful mailcheck is

### LINKED ISSUE #2819: Measure how helpful our suggested email domain advice is
We currently measure when we suggest an email domain to a user, but we don't measure if the email they submit matches the one we suggested. It's therefore difficult to tell how often the advice is helpful, and acted upon.

We should not only measure when the user clicks the suggested email domain, but also if they manual edit their email domain to see if it matched our suggestion.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2819

### CODE REVIEW

File: app/scripts/views/sign_up.js [hunk 1]
```diff
@@ -225,6 +227,17 @@ function (Cocktail, _, p, BaseView, FormView, Template, AuthErrors, mailcheck,
       }
       return this._isMailcheckEnabledValue;
     },
+    _isMailcheckUseful: function () {
```
Comment (rfk) [inline app/scripts/views/sign_up.js]: naming nit: we tend to use "isFoo" for state-checking things like "isMailcheckEnabled" and "isSignUpDisabled"; since this is an after-the-fact check on what happened, perhaps it should be named something like "was" rather than "is".

**Comment by vladikoff** [comment]
updated @shane-tomlinson r?

File: app/scripts/views/sign_up.js [hunk 2]
```diff
@@ -225,6 +227,17 @@ function (Cocktail, _, p, BaseView, FormView, Template, AuthErrors, mailcheck,
       }
       return this._isMailcheckEnabledValue;
     },
+    _wasMailcheckUseful: function () {
+      var email = this.$el.find('.email');
```
Comment (shane-tomlinson) [inline app/scripts/views/sign_up.js]: Is there ever *not* an email address on the signup page? If the email field is always there, you could just do:

```js
var emailValue = this.getElementValue('.email');
if (emailValue) {
  ...

```

Comment (vladikoff) [inline app/scripts/views/sign_up.js]: I'm accessing `.data` below of the email input. 
If I use `getElementValue` then it won't be useful and I have to query for the element twice

Comment (shane-tomlinson) [inline app/scripts/views/sign_up.js]: ok. One thing we should watch out for, I see mailcheck takes [a reference to an element](https://github.com/mozilla/fxa-content-server/blob/908afb88206d7ff8a5497d0b21a829f2cf1eda9e/app/scripts/views/sign_up.js#L231), and then [uses el.val()](https://github.com/mozilla/fxa-content-server/blob/908afb88206d7ff8a5497d0b21a829f2cf1eda9e/app/scripts/lib/mailcheck.js#L40) to get the value. There can be leading whitespace on an email address, `getElementValue` will trim that for email addresses already. Does leading whitespace have any effect on mailcheck?

**Comment by shane-tomlinson** [comment]
@vladikoff - I'll test this today. One thing I was thinking about while doing the review is that `lib/mailcheck` makes use of the Tooltip view, which is a layering violation. Views can depend on libs, but the reverse should not happen. Looking at the mailcheck code embedded in the SignupView, I think we could sidestep the issue and move all Mailcheck related code to a view mixin. Layering violation removed, the bulk of the mailcheck code moved from the signup view into a mixin where it can be thought about independently, and finally, whenever we add the change email feature, we can easily add the mixin to that view too. Obviously, not for this PR if this seems like a good approach.

**Comment by shane-tomlinson** [comment]
Uh oh, merge conflicts. Probably in the docs.

File: app/scripts/views/sign_up.js [hunk 3]
```diff
@@ -225,6 +227,17 @@ function (Cocktail, _, p, BaseView, FormView, Template, AuthErrors, mailcheck,
...
+
+      if (email) {
+        var emailValue = email.val();
+        var mailcheckValue = email.data('mailcheckValue');
+        if (emailValue.length > 0 && mailcheckValue === emailValue) {
+          this.metrics.logEvent('tooltip.mailcheck-useful');
```
Comment (shane-tomlinson) [inline app/scripts/views/sign_up.js]: There is already a `tooltip.mailcheck-used`, how is this different? Does this capture if the user types the email insted of clicks the tooltip?

File: docs/client-metrics.md [hunk 4]
```diff
@@ -196,7 +196,8 @@ The event stream is a log of events and the time they occurred while the user is
 
 #### signup
 * tooltip.mailcheck-suggested - an email address correction was suggested
-* tooltip.mailcheck-used - an email address correction was chosen by the user
+* tooltip.mailcheck-used - an email address correction was chosen by the user in the tooltip
+* tooltip.mailcheck-useful - an email address correction was used by the user during sign up form submit
```
Comment (shane-tomlinson) [inline docs/client-metrics.md]: Can you add a bit of meta info to this event description that it covers both the tooltip and manually changing the address (my guess at what the new event is for).

File: app/scripts/views/sign_up.js (hunk 3 above)
Comment (shane-tomlinson) [inline app/scripts/views/sign_up.js]: Ah yes, from [@ryanfeeley's comment](https://github.com/mozilla/fxa-content-server/issues/2819#issue-96894639):

> We should not only measure when the user clicks the suggested email domain, but also if they manual edit their email domain to see if it matched our suggestion.

**Comment by shane-tomlinson** [comment]
Ah yes, I see the event in the metrics:

screen shot 2015-08-13 at 12 16 03

**Comment by shane-tomlinson** [comment]
My only requests are a rebase and a doc update. Works well, thanks @vladikoff. r=me.

File: app/scripts/views/sign_up.js (hunk 2 above)
Comment (vladikoff) [inline app/scripts/views/sign_up.js]: From my testing it fixes whitespace issues on both sides.

**Comment by vladikoff** [comment]
CircleCI failing, contacted support. Ran the tests locally though! Thanks for the review Shane!
