### PR TITLE
fix(client): Do not sign out of Sync when visiting /force_auth

### LINKED ISSUE #3431: /force_auth signs users out of Sync
#### STR

1. Sign up/in to sync.
1. Open the hamburger menu to ensure you are signed in.
1. Visit https://accounts.firefox.com/force_auth?email=email_from_step_1
1. Open the hamburger again. No longer signed in.

#### Expected

1. I'm still signed in

force-auth-signs-out-of-sync

I don't know if we have real world users of force_auth other than Sync, if there aren't any, the damage is limited.

Caused by [user.js->clearSignedInAccount sending the SIGNED_OUT notification](https://github.com/mozilla/fxa-content-server/blob/cad9b095044a00bc136e1be65da6766153b3d516/app/scripts/models/user.js#L165) over the WebChannel.

Ref #3419

### PR DESCRIPTION
**Pull request by shane-tomlinson**
We were erroneously clearing the signed in user, which sent an
`fxaccounts:logout` message over the WebChannel.

fixes #3431

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@vbudhram, @vladikoff - r?

File: app/scripts/views/force_auth.js [hunk 1]
```diff
@@ -23,20 +23,20 @@ define(function (require, exports, module) {
...
+      proto.initialize.call(this, options);
 
-      this._formPrefill = options.formPrefill;
-
-      // forceAuth means a user must sign in as a specific user.
+      // forceAuth means a user msut sign in as a specific user.
       // kill the user's local session.
+      // TODO - I think this should go too, but am unsure of
+      // the repercussions.
       Session.clear();
```
Comment (shane-tomlinson) [inline app/scripts/views/force_auth.js]: @zaach, @vladikoff - Why do we do `Session.clear` here, is that old legacy code because all the user's session info used to be stored in Session? All Session contains now is OAuth verification info. I believe we *should* be able to ditch this line now. With the line erased, the entire function can be removed.

Comment (vladikoff) [inline app/scripts/views/force_auth.js]: @shane-tomlinson 

> Why do we do Session.clear here, is that old legacy code because all the user's session info used to be stored in Session?

Yeah looks like it, dates back to "first commits", kill it :+1:

File: tests/functional/sync_v2_force_auth.js [hunk 2]
```diff
@@ -21,7 +21,7 @@ define([
   var PASSWORD = '12345678';
   var url;
 
-  var listenForFxaCommands = FunctionalHelpers.listenForWebChannelMessage;
+  var noSuchBrowserNotification = FunctionalHelpers.noSuchBrowserNotification;
```
Comment (vbudhram) [inline tests/functional/sync_v2_force_auth.js]: Noticed that `noSuchBrowserNotification` takes a callback parameter, but never uses it. Could be removed.

https://github.com/mozilla/fxa-content-server/blob/issue-3431-force-auth-signs-out-of-sync/tests/functional/lib/helpers.js#L690

Comment (shane-tomlinson) [inline tests/functional/sync_v2_force_auth.js]: Thanks for pointing that out! Done.

**Comment by shane-tomlinson** [comment]
@vladikoff, @vbudhram - updates made, ready for another round!

**Comment by vbudhram** [comment]
LGTM!
