### PR TITLE
fix(client): Normalize all errors from the Auth Server.

### LINKED ISSUE #2513: metrics: fxa.content.error.signup.unknown_namespace.101
for some reason, error 101 reports with unknown_namespace

image

### LINKED ISSUE #2623: "client has sent too many requests" error is not translated
Oddly enough, the error message is translated in the [l10n repo](https://github.com/mozilla/fxa-content-server-l10n/blob/4a59dadabaa1d3f9dbc3e40626dc9219e275bb2c/locale/es/LC_MESSAGES/client.po#L1079), it's just commented out.

screen shot 2015-06-21 at 14 25 33

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Errors returned from the auth server were not being normalized. This
caused two problems, the first is error messages that were not used
elsewhere in the system were untranslated when displayed. Second,
errors that originated on the auth server were reported to metrics
as having an `unknown namespace`.

fixes #2513
fixes #2623 

@vladikoff, @zaach - what'cha think?

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@TDA, @eoger - you two should get involved in reviewing too.

**Comment by shane-tomlinson** [comment]
#### translated string

screen shot 2015-07-23 at 16 16 04

#### correct namespace in the server logs

screen shot 2015-07-23 at 16 16 17

File: app/scripts/lib/errors.js [hunk 1]
```diff
@@ -100,15 +100,25 @@ define([
...
-      var message = this.toMessage(type);
-      if (! message) {
-        message = this.toMessage('UNEXPECTED_ERROR');
-      }
+      var errno = this.toErrno(type);
+      var message = this.toMessage(errno);
 
       var err = new Error(message);
 
+      if (typeof type === 'object') {
```
Comment (eoger) [inline app/scripts/lib/errors.js]: _.extend would be perfect for this job.

File: app/scripts/lib/fxa-client.js [hunk 2]
```diff
@@ -20,14 +20,45 @@ function (FxaClient, $, p, Session, AuthErrors) {
     return $.trim(str);
   }
 
+  // errors from the FxaJSClient must be normalized so that they
+  // are translated and reported to metrics correctly.
+  function wrapClientToNormalizeErrors(client) {
```
Comment (eoger) [inline app/scripts/lib/fxa-client.js]: Nit pic: wrapClientToNormalizeErrors to wrapClientToNormalizedErrors (normalize to normalizeD)

File: app/scripts/lib/errors.js [hunk 3]
```diff
@@ -100,15 +100,25 @@ define([
      * @param {String} [context]
      */
     toError: function (type, context) {
-      var message = this.toMessage(type);
-      if (! message) {
```
Comment (TDA) [inline app/scripts/lib/errors.js]: Should we still have a check to see if message exists? I think we should. @shane-tomlinson

**Comment by TDA** [comment]
@shane-tomlinson other than that one check and what @eoger said, it LGTM! :)

**Comment by zaach** [comment]
Uh oh
> CancelError: Timeout reached on firefox on any platform - sign_up - signup, verify different browser - from original tab's P.O.V.

**Comment by zaach** [comment]
Tests corrected themselves :+1: . Looks good modulo nits.

File: app/scripts/lib/errors.js (hunk 3 above)
Comment (shane-tomlinson) [inline app/scripts/lib/errors.js]: Thanks @TDA - [toMessage](https://github.com/mozilla/fxa-content-server/blob/9ec6b1812e76fa9576462bd9c4cebf4544698f9f/app/scripts/lib/errors.js#L35) is guaranteed to return a string, even if no type was passed in. Line 105 was the lone line in this file to not be covered by test coverage, and I could find no way to cause it to be covered w/o mocking in `toMessage` to return a falsey value.

File: app/scripts/lib/errors.js (hunk 1 above)
Comment (shane-tomlinson) [inline app/scripts/lib/errors.js]: _.extend will pull in items from `type`s prototype as well, I didn't want that in case `type` was already an `Error` and we start copying over functions on the error's prototype. Maybe what I should do is 

```js
if (typeof type === 'object' && ! (type instanceof Error)) { 
  _.extend(...
```

Comment (shane-tomlinson) [inline app/scripts/lib/errors.js]: Ahha! Underscore has [_.extendOwn](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1033)! Perfect.

File: app/scripts/lib/fxa-client.js (hunk 2 above)
Comment (shane-tomlinson) [inline app/scripts/lib/fxa-client.js]: In this case, we are normalizing the errors, I think sans-D is correct. The function could be renamed to `wrapClientToReturnNormalizedErrors`.

**Comment by shane-tomlinson** [comment]
Thanks for the review @zaach, @eoger & @TDA. I have made the requested updates, with the exception of the name change. We can file a follow on issue for that if you feel strongly.
