### PR TITLE
fix(email): on password reset, hash email with the `emailToHashWith` value

### LINKED ISSUE #6571: "Incorrect password" displayed if we change the password and then switch to primary email again
Environment:
Platform: iOS, Android, Win10
Train 121

Steps to reproduce:
1. Add a secondary email (Manage account- Secondary email);
2. Make primary the secondary email;
3. Change the password;
4. Make secondary the primary email (switch between accounts);
5. Log out and Sign in again with the new password.

Expected results: the user is logged in.
Actual result: "Incorrect password" message is displayed.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #6571 

After some investigating and head scratching, it turns out that the password reset is not using the correct email address to hash the password when the password is reset. I am not sure when this got regressed but suspect it might have been with account recovery.

This PR pdates the `completePasswordReset` and `resetPasswordWithRecoveryKey` functions to correctly pass the email that should be hashed with password (`emailToHashWith`). This value ensures that passwords are always hashed with the original email the account was created with. 

Unfortunately, with this bug, we can't have that guarantee anymore because there might be some users that reset their passwords (after performing a primary email change), so their password would be hashed with the new email.

In practice, I don't believe this is an issue because the auth-server will only compare the `authPW` that the content-server passes to it.

### CODE REVIEW

File: app/scripts/models/account.js [hunk 1]
```diff
@@ -870,17 +870,19 @@ const Account = Backbone.Model.extend({
      * @param {String} token - email verification token
      * @param {String} code - email verification code
      * @param {Object} relier - relier being signed in to.
+     * @param {String} emailToHashWith - use this email to hash password with.
      * @returns {Promise} - resolves when complete
      */
-  completePasswordReset (password, token, code, relier) {
+  completePasswordReset (password, token, code, relier, emailToHashWith) {
```
Comment (vbudhram) [inline app/scripts/models/account.js]: Not a huge fan of this variable name, but I used it in other parts of the code..so I'll be consistent for time being.

File: app/tests/spec/models/user.js [hunk 2]
```diff
@@ -1173,6 +1174,47 @@ define(function (require, exports, module) {
       });
     });
 
+    describe('completeAccountPasswordResetWithRecoveryKey', () => {
```
Comment (vbudhram) [inline app/tests/spec/models/user.js]: Noticed I didn't add a test for this before.

**Comment by vbudhram** [comment]
Looks like email timeout errors, will restart in a bit.

File: app/scripts/models/account.js (hunk 1 above)
Comment (rfk) [reply app/scripts/models/account.js]: +1 for consistency, at least until we get around to a cleanup like https://github.com/mozilla/fxa-auth-server/issues/2344

**Comment by SorinaFlorean** [comment]
Verified as fixed on Train 122.
