### PR TITLE
fix(metrics): add missing reason property to disconnect event

### LINKED ISSUE #5598: Emit appropriate events and data for device disconnection reasons
We're going to use these metrics to measure the outcome of FxA-139, so we need to make sure we have them available in Redshift and/or Amplitude.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #5598. Supercedes #5605.

The taxonomy specifies a `reason` property on the `fxa_pref - disconnect_device` event, which I wasn't emitting. This PR adds it.

Targeted at train 98 so that we can do the other parts of this OKR sooner too (we need this data to measure the outcome).

@mozilla/fxa-devs r?

### CODE REVIEW

File: tests/server/amplitude.js [hunk 1]
```diff
@@ -184,11 +200,31 @@ define([
...
+        deviceId: 'b',
+        flowBeginTime: 'c',
+        flowId: 'd',
+        lang: 'e',
+        uid: 'f'
+      });
+      assert.equal(process.stderr.write.callCount, 1);
+      const arg = JSON.parse(process.stderr.write.args[0]);
+      assert.equal(arg.event_type, 'fxa_pref - disconnect_device');
+      assert.equal(arg.event_properties.reason, 'duplicate');
```
Comment (vbudhram) [inline tests/server/amplitude.js]: @philbooth Running this locally, I don't see the reason property in the console.

```
{"op":"amplitudeEvent","time":1508333300667,"device_id":"a6a2fb4ad984497db4f36428d676ae85","event_type":"fxa_pref - disconnect_device","session_id":1508333205463,"event_properties":{"device_id":"a6a2fb4ad984497db4f36428d676ae85","entrypoint":"menupanel"},"user_properties":{"flow_id":"9aac5b950cf41c3e216796d3fc9664781775eefeda51d8a8b7a33b6ffe68d890","ua_browser":"Firefox","ua_version":"56","experiments":["q3form_changes_cad_on_signin"]},"app_version":"97","language":"en","os_name":"Mac OS X","os_version":"10.12"}
```

I vaguely remember there being some differences when testing locally, would this be related?

**Comment by philbooth** [comment]
Forgot to include a sample log line demonstrating the new property. Here's one:

```
{"op":"amplitudeEvent","time":1508330228197,"user_id":"99c9eba55d7d499eb886911f0ff148be","device_id":"3b8e37bdbc404db5b3d683a994ce7007","event_type":"fxa_pref - disconnect_device","session_id":1508330154346,"event_properties":{"device_id":"3b8e37bdbc404db5b3d683a994ce7007","reason":"suspicious"},"user_properties":{"flow_id":"539962e263e454797450cfd5d3c8605be7548a1a3e2a0a41d012a3e349cb0e48","ua_browser":"Firefox","ua_version":"58","experiments":["q3form_changes_signup_password_confirm","signup_password_confirm_control"]},"app_version":"98","language":"en","os_name":"Mac OS X","os_version":"10.11"}
```

File: tests/server/amplitude.js (hunk 1 above)
Comment (philbooth) [reply tests/server/amplitude.js]: Huh, that's weird, it works for me here. Which reason are you choosing?

Comment (vbudhram) [reply tests/server/amplitude.js]: Forgot to restart server >.< after switching branch...
