### PR TITLE
fix(notifications): Allow a notification handler to be spied upon.

### LINKED ISSUE #4731: Cannot add a sinon spy to notification handlers if declaration uses a string
For example:

```js
const View = BaseView.extend({
  notifications: {
    navigate: '_onNavigate'
  },
  
  _onNavigate () {
    console.log('heyo!');
  }
});
```

Then in the unit tests:

```js
const view = new View();
sinon.spy(view, '_onNavigate');

notifier.trigger('navigate');

assert.isTrue(view._onNavigate.called); // <-- this always fails because the spy is not called.
// BUT!
// heyo! shows up in the console logs.
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
## What's the problem?

While adding handlers for items in `notifications`, if the handler
was declared using a string, the actual handler method reference was
immediately created. This made it impossible to spy upon a method
declared this way.

### What's the fix?

Do "late-binding" where the handler method is looked up
when the notification is triggered. This allows sinon to set up a spy
and then have the spy called whenever the notification is triggered.

fixes #4731

@philbooth - you've been doing a lot with notifications lately, mind an r on this?

### CODE REVIEW

File: app/scripts/lib/channels/notifier-mixin.js [hunk 1]
```diff
@@ -62,13 +62,17 @@ define(function (require, exports, module) {
...
+        if (_.isString(method) && _.isFunction(consumer[method])) {
+          this.on(notificationName, (...args) => {
+            // The level of indirection is used to allow for
+            // late-binding when using sinon spies & stubs.
+            // Without indirection, the original function is
+            // always called.
+            consumer[method](...args);
+          });
+        } else if (_.isFunction(method)) {
           this.on(notificationName, method.bind(consumer));
```
Comment (philbooth) [inline app/scripts/lib/channels/notifier-mixin.js]: @shane-tomlinson am I missing something or does the problem remain for this `else` branch? Should we fix it for both?

Comment (shane-tomlinson) [inline app/scripts/lib/channels/notifier-mixin.js]: @philbooth you are right, but there's no way to do dynamic binding if a function is passed in. All we have is a reference to the function, and a spy replaces the function reference on an object.

Comment (philbooth) [inline app/scripts/lib/channels/notifier-mixin.js]: True-ish, although we have `consumer` and we have `method.name`, so it's possible depending on how `method` was declared. But anyway, it's an imaginary problem I realise. Sorry for the tangent.

**Comment by philbooth** [comment]
r+
