### PR TITLE
﻿fix(test): Fix the "device and apps panel works" functional test. 

### LINKED ISSUE #4397: Common circle failure: "settings clients - device and apps panel works with query param, same device"
Here's a log of it also happening locally:

```
× firefox on any platform - settings clients - device and apps panel works with query param, same device (33.296s)
StaleElementReference: [POST http://localhost:4444/wd/hub/session/d2994d92-6b26-4d77-b8b1-f7f714f5841e/element/1506/click] Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'Shanes-Retina-MBP.local', ip: '10.242.31.41', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_102'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:163:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1373:12>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.device and apps panel works with query param, same device [as test]  <tests/functional/settings_clients.js:210:10>
  at <node_modules/intern/lib/Test.js:181:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
We kept seeing StaleElementReference errors when trying to disconnect
devices. Use the low level primitives to wait for devices to be
removed from the DOM, which in turn helps ensure the Stale Elements
are not referenced.

Lots of general test cleanup too, using helper functions where possible.

fixes #4397 

@vladikoff - r?

### CODE REVIEW

File: tests/functional/settings_clients.js [hunk 1]
```diff
@@ -49,38 +55,24 @@ define([
...
-        .end()
+      return this.remote
+        .then(openPage(this, SIGNIN_URL_DEVICE_LIST, '#fxa-signin-header'))
+        .then(fillOutSignIn(this, email, FIRST_PASSWORD))
 
-        .findByCssSelector('#clients .settings-unit-stub button')
-          .click()
-        .end()
-
-        .findByCssSelector('.clients-refresh')
```
Comment (shane-tomlinson) [inline tests/functional/settings_clients.js]: This clients-refresh click didn't seem to have any tested side effect, so I removed it.

File: tests/functional/settings_clients.js [hunk 2]
```diff
@@ -177,46 +157,31 @@ define([
 
         // test cancel
         .then(click('.cancel-disconnect'))
-
-        .then(pollUntilGoneByQSA('#client-disconnect'))
+        .waitForDeletedByCssSelector('#client-disconnect')
```
Comment (shane-tomlinson) [inline tests/functional/settings_clients.js]: This is the important change, instead of `pollUntilGoneByQSA`, use `waitForDeletedByCssSelector` which seems to cause an update of the element cache.
