### PR TITLE
fix(client): Simplify the message serialization for the iframe channel.

### LINKED ISSUE #2149: simplify iframe command/data serialization
Using `!!!` as a separator is brittle and just plain ugly. Instead create an object with two fields, command and data, then stringify the whole thing.

Link to https://github.com/mozilla/fxa-relier-client/issues/44

### PR DESCRIPTION
**Pull request by shane-tomlinson**
No longer use `!!!` as the separator between the command and data. Instead, just send a serialized object with the `command` and `data` fields.

fixes #2149

goes along with https://github.com/mozilla/fxa-relier-client/pull/45

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
To ensure the functional tests work with this, a new version of the relier client needs to be built and included on 123done.

**Comment by shane-tomlinson** [comment]
Goes along with https://github.com/mozilla/123done/pull/135

File: app/scripts/lib/channels/iframe.js [hunk 1]
```diff
@@ -34,22 +34,29 @@ define([
...
     },
 
     dispatchCommand: function (command, data) {
-      var msg = command + '!!!' + JSON.stringify(data|| {});
+      var msg = IFrameChannel.stringify(command, data);
       this.window.parent.postMessage(msg, '*');
     }
   }, PostMessageReceiverMixin);
 
+  IFrameChannel.stringify = function (command, data) {
```
Comment (vladikoff) [inline app/scripts/lib/channels/iframe.js]: Nit: do we need to validate `command` here or leave it?

File: app/scripts/lib/channels/iframe.js [hunk 2]
```diff
@@ -34,22 +34,29 @@ define([
...
+    return JSON.stringify({
+      command: command,
+      data: data || {}
+    });
+  };
+
+  IFrameChannel.parse = function (msg) {
+    return JSON.parse(msg);
```
Comment (vladikoff) [inline app/scripts/lib/channels/iframe.js]: Nit: do we need to report errors here if something goes wrong?

**Comment by vladikoff** [comment]
Tested with https://github.com/mozilla/fxa-relier-client/pull/45 and 123done. Looks good, r+ with comments addressed if needed.

**Comment by vladikoff** [comment]
https://github.com/mozilla/123done/pull/135 needs to be also merged once this is merged I assume.

**Comment by shane-tomlinson** [comment]
Thanks for the review @vladikoff - your suggestions are valid. I'm wondering whether to make that part of this PR, or as part of the PR for #2151 that I want to work on this/next week. In any case, I can't merge this until I get the all-clear from the first run folks that this will not conflict with their experiments.

**Comment by shane-tomlinson** [comment]
> In any case, I can't merge this until I get the all-clear from the first run folks that this will not conflict with their experiments.

I got the word. Experiments are over.
