### PR TITLE
fix(client): If a relier wants keys, give them keys.

### LINKED ISSUE #2356: Loop: The signin is not properly providing keys for the relier
Possible fix: https://pastebin.mozilla.org/8831763

Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1159520

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@vladikoff and @rfk - r?

* If a relier wants keys, the user must enter their password so that user keys can be fetched from the auth server and then converted to relier usable keys.

fixes #2356

### CODE REVIEW

File: tests/functional/oauth_webchannel.js [hunk 1]
```diff
@@ -27,23 +29,34 @@ define([
...
+
+
   /**
    * This suite tests the WebChannel functionality in the OAuth signin and
    * signup cases. It uses a CustomEvent "WebChannelMessageToChrome" to
    * finish OAuth flows
    */
 
-  function testIsBrowserNotifiedOfLogin(context, shouldCloseTab) {
+  function testIsBrowserNotifiedOfLogin(context, shouldCloseTab, wantKeys) {
```
Comment (shane-tomlinson) [inline tests/functional/oauth_webchannel.js]: I felt gross adding another boolean to the end of this, but didn't want to bloat the PR any more than needed. This can be cleaned up in a follow up.

**Comment by vladikoff** [comment]
Testing this out.....

**Comment by vladikoff** [comment]
Closes https://github.com/mozilla/fxa-content-server/issues/2175#issuecomment-97470975

**Comment by shane-tomlinson** [comment]
Restarting travis, the error is due to bower not being found.

**Comment by vladikoff** [comment]
tested manually with and without latest nightly + ran functional tests.

**Comment by rfk** [comment]
Thanks for diving into this guys.  FWIW, sync reliers always want keys, so I think this check is redundant:
```
if (this.relier.isSync()) {
  return true;
}
 
// If the relier wants keys, then the user must authenticate
// and the password must be requested.
if (this.relier.wantsKeys()) {
  return true;
}
```

The `wantsKeys()` call subsumes the existing call to `isSync()`.

**Comment by shane-tomlinson** [comment]
Filed #2360, #2361
