### PR TITLE
fix(cwts): Handle bounced emails and confirmations while on CWTS.

### LINKED ISSUE #4094: Bounce not triggering from Choose What To Sync screen
STEPS TO REPRODUCE
1. Create a fresh Firefox profile
2. Create a Sync account by any means using an email that will bounce
3. Stay on the Choose What To Sync screen for as long as the email will typically bounce
4. Click **Save settings**

EXPECTED RESULTS
- When the email bounces, the user is returned to registration with the email field outlined and the message “Your verification email was just returned. Mistyped email?”

ACTUAL RESULTS
- The screen stays indefinitely, and when the user clicks **Save settings** they are taken to a message-free registration free.

null

From **accounts.firefox.com**:
stillnull

When the user clicks **Save settings** before the bounce:
nullagain

### LINKED ISSUE #4193: Users who verify their email while at the CWTS screen may never start syncing.
We have known this for a long time, so a bug may already exist.

We know 100-200 users/day [verify their email](https://github.com/mozilla/fxa-content-server/issues/4152) while [at the choose what to sync screen](https://github.com/mozilla/fxa-content-server/issues/4152#issuecomment-247497426). There may be more, this is the number of users that actually pressed "submit" on CWTS after they have verified their email. Users that never press "submit" on the screen never start syncing, and may be under the false impression that they are.

Ref #4094, if we start polling on CWTS, both may be able to be fixed in the same PR.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Use the session-verification-poll-mixin in the CWTS page to
handle both bounces and auto-submit the form if verification completes.

fixes #4094
fixes #4193 

Builds on #5342 and should be reviewed afterwards

bounce-submit-cwts

### CODE REVIEW

File: app/tests/spec/views/choose_what_to_sync.js [hunk 1]
```diff
@@ -121,6 +130,26 @@ define(function (require, exports, module) {
       });
     });
 
+    describe('session verification polling', () => {
```
Comment (philbooth) [inline app/tests/spec/views/choose_what_to_sync.js]: No biggie obviously, but if you're doing all the setup inside the test itself, does the `describe` here have a point?

**Comment by philbooth** [comment]
Looks good, r+
