### PR TITLE
fix(email-first): email-first experiment is isolated from other experiments.

### LINKED ISSUE #5452: Login page fails to load in iOS 9 mobile safari
From https://bugzilla.mozilla.org/show_bug.cgi?id=1397691, tested this in mobile Safari and it fails to load. From console logs, it appears to be a CSP error.

screen shot 2017-09-07 at 9 43 03 am

Tested using the same url as Firefox iOS: https://accounts.firefox.com/signin?service=sync&context=fx_ios_v1

### LINKED ISSUE #5469: email-first experiment is not sufficiently isolated to compare apples to apples
@davismtl and I discussed this on Friday in our 1:1, capturing here some of our thoughts.

* Bucket user into one of "verify password", "email-first" and "disabled button state" and "control".
* Remove the verify-password field until that experiment has proven itself out, because we believe this causes ~ 6% dropoff.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Remove `static get name` from the email-first experiment rule
which blew up Safari 9 on iOS.

When combined with #5478,
fixes #5469
fixes #5452 

@vladikoff - r?

I opened this and #5478 against train-95 hoping we could do a point release to get faster feedback.

### CODE REVIEW

File: app/scripts/views/mixins/email-first-experiment-mixin.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ define(function (require, exports, module) {
   'use strict';
 
   const ExperimentMixin = require('views/mixins/experiment-mixin');
-  const EXPERIMENT_NAME = require('lib/experiments/grouping-rules/email-first').name;
+  const EXPERIMENT_NAME = 'emailFirst';
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/email-first-experiment-mixin.js]: Since the static name getter is removed to fix Safari, I just hard coded the name here.

File: app/scripts/lib/experiments/grouping-rules/email-first.js [hunk 2]
```diff
@@ -75,17 +77,6 @@ define((require, exports, module) => {
...
     }
-
-    /**
-     * The experiment name
-     *
-     * @readonly
-     * @static
-     * @return {String}
-     */
-    static get name () {
```
Comment (vladikoff) [inline app/scripts/lib/experiments/grouping-rules/email-first.js]: 👍

File: app/scripts/lib/experiments/grouping-rules/q3-form-changes.js [hunk 3]
```diff
@@ -20,8 +20,7 @@ define((require, exports, module) => {
      * @returns {Any}
      */
     choose (subject) {
-      const EXPERIMENTS = ['disabledButtonState', 'signupPasswordConfirm'];
-
+      const EXPERIMENTS = ['disabledButtonState', 'signupPasswordConfirm', 'emailFirst'];
```
Comment (vladikoff) [inline app/scripts/lib/experiments/grouping-rules/q3-form-changes.js]: 👍

File: app/scripts/lib/experiments/grouping-rules/email-first.js (hunk 2 above)
Comment (vbudhram) [reply app/scripts/lib/experiments/grouping-rules/email-first.js]: Nice! I'll update iOS bug once this gets tagged.
