### PR TITLE
fix(metrics): Fix the refresh metrics when refreshing a settings subpanel.

### LINKED ISSUE #3172: refreshing a settings subpanel logs the refresh on settings
STR

1. Apply the diff from below
1. Open the dev console
1. Sign in
1. Open any subpanel from settings
1. Refresh the page
1. Look in the dev console for the correct subpanel name
1. Wah wah.

```diff
diff --git a/app/scripts/lib/router.js b/app/scripts/lib/router.js
index ed44797..6b43908 100644
--- a/app/scripts/lib/router.js
+++ b/app/scripts/lib/router.js
@@ -272,6 +272,7 @@ function (
       var screenName = currentView.getScreenName();
 
       if (refreshMetrics && refreshMetrics.view === screenName && this.metrics) {
+        console.log('refresh: ', screenName);
         currentView.logScreenEvent('refresh');
       }
 
```

refresh-a-settings-subpanel

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Create the `PageRefreshWatch` model that listens for `show-view`
and `show-sub-view` messages, where a screen name is passed that
can be used to check for refreshes.

fixes #3172

@philbooth - Furthering the cause to split up the router, plus fixing a bug. Mind an r?

### CODE REVIEW

File: app/scripts/lib/app-start.js [hunk 1]
```diff
@@ -110,6 +111,7 @@ function (
   User,
   FormPrefill,
   Notifications,
+  PageRefreshWatch,
```
Comment (philbooth) [inline app/scripts/lib/app-start.js]: We have screens, we have views and we have pages. What's the difference between them, if any?

Comment (shane-tomlinson) [inline app/scripts/lib/app-start.js]: https://github.com/mozilla/fxa-content-server/issues/3185

Page in this situation is CMD-R refresh. `BrowserRefreshWatch`?

File: app/scripts/models/page-refresh-watch.js [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+ */
+
+define([
+  'backbone',
+  'lib/storage'
+], function (Backbone, Storage) {
+  'use strict';
+
+  function isRefresh (refreshMetrics, screenName) {
+    return refreshMetrics && refreshMetrics.view === screenName;
```
Comment (philbooth) [inline app/scripts/models/page-refresh-watch.js]: ...and just to underline that page/screen/view confusion, here `view` is compared to `screenName`.

File: app/tests/spec/models/page-refresh-watch.js [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+        notifications: notifications,
+        window: windowMock
+      });
+    });
+
+    describe('logIfRefresh', function () {
+      describe('with two consecutive views with different names', function () {
+        it('does not log a page refresh', function () {
+          pageRefreshWatch.logIfRefresh('screen1');
+          pageRefreshWatch.logIfRefresh('screen2');
```
Comment (philbooth) [inline app/tests/spec/models/page-refresh-watch.js]: This test and the following test contain identical boilerplate. Should be extracted to `before`.

File: app/tests/spec/models/page-refresh-watch.js [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+          assert.isTrue(
+              metrics.logScreenEvent.calledWith('screen1', 'refresh'));
+        });
+      });
+    });
+
+    describe('notifications', function () {
+      describe('show-view', function () {
+        it('calls `logIfRefresh', function () {
+          sinon.spy(pageRefreshWatch, 'logIfRefresh');
```
Comment (philbooth) [inline app/tests/spec/models/page-refresh-watch.js]: Common boilerplate here too.

File: app/scripts/lib/app-start.js (hunk 1 above)
Comment (philbooth) [inline app/scripts/lib/app-start.js]: > `BrowserRefreshWatch`

Hmm, mebbe. Or mebs just `RefreshWatch`? Lose the page/browser/whatever bit entirely?

File: app/tests/spec/views/base.js [hunk 5]
```diff
@@ -589,6 +589,13 @@ function (chai, $, sinon, BaseView, p, Translator, EphemeralMessages, Metrics,
       });
     });
 
+    describe('logScreenEvent', function () {
+      it('logs an event with the screen name as a prefix to the event stream', function () {
+        view.logScreenEvent('event1');
+        assert.isTrue(TestHelpers.isEventLogged(metrics, 'screen.event1'));
```
Comment (philbooth) [inline app/tests/spec/views/base.js]: One of these things belongs in `before` and the other one belongs in `it`.

File: app/tests/spec/lib/metrics.js [hunk 6]
```diff
@@ -552,6 +552,13 @@ function (chai, $, p, Metrics, AuthErrors, Environment, sinon, _, WindowMock, Te
       });
     });
 
+    describe('logScreenEvent', function () {
+      it('logs an event with the screen name as a prefix to the event stream', function () {
+        metrics.logScreenEvent('screen', 'event1');
+        assert.isTrue(TestHelpers.isEventLogged(metrics, 'screen.event1'));
```
Comment (philbooth) [inline app/tests/spec/lib/metrics.js]: `before` / `it`

File: app/tests/spec/lib/app-start.js [hunk 7]
```diff
@@ -708,6 +709,20 @@ function (chai, sinon, Raven, AppStart, Session, NullChannel, Constants, p,
...
+    describe('initializePageRefreshWatch', function () {
+      beforeEach(function () {
+        appStart = new AppStart({
+          notifications: notifications,
+          window: windowMock
+        });
+      });
+
+      it('creates a PageRefreshWatch instance', function () {
+        appStart.initializePageRefreshWatch();
```
Comment (philbooth) [inline app/tests/spec/lib/app-start.js]: Should be in `beforeEach`.

File: app/scripts/lib/app-start.js (hunk 1 above)
Comment (philbooth) [inline app/scripts/lib/app-start.js]: Actually, while I'm picking out colours for your new bikeshed, I wonder if `Listener` or `Observer` might be more a more appropriate suffix than `Watch`? :grin:

File: app/scripts/lib/router.js [hunk 8]
```diff
@@ -228,22 +227,6 @@ function (
       return viewOptions;
     },
 
-    _checkForRefresh: function (currentView) {
-      var refreshMetrics = this.storage.get('last_page_loaded');
-      var screenName = currentView.getScreenName();
-
-      if (refreshMetrics && refreshMetrics.view === screenName && this.metrics) {
```
Comment (philbooth) [inline app/scripts/lib/router.js]: I notice that here we used to check `this.metrics` but in the code extracted to `page-refresh-watch.js` we don't bother. Is it okay to assume that it will always be set?

**Comment by philbooth** [comment]
Despite my pedantic commentary inline, this LGTM. :+1:

**Comment by shane-tomlinson** [comment]
> Despite my pedantic commentary inline, this LGTM. :+1:

More of this! Pedantry is how we are going to improve the quality over time! I'll address the concerns on Monday, thanks @philbooth!

File: app/scripts/lib/router.js (hunk 8 above)
Comment (shane-tomlinson) [inline app/scripts/lib/router.js]: Yup, metrics is always created now. The backend drops metrics on the ground if not being saved for the user.

File: app/tests/spec/lib/metrics.js [hunk 9]
```diff
@@ -552,6 +552,16 @@ function (chai, $, p, Metrics, AuthErrors, Environment, sinon, _, WindowMock, Te
       });
     });
 
+    describe('logScreenEvent', function () {
+      beforeEach(function () {
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/metrics.js]: @philbooth - if I use `before` instead of `beforeEach`, `before` is run before the outer `beforeEach` that creates the dependencies, and `metrics` is undefined. This was also a problem for router.js and refresh-observer.js. Am I doing it wrong?

**Comment by shane-tomlinson** [comment]
@philbooth - I have [one question](https://github.com/mozilla/fxa-content-server/pull/3184#discussion_r42355996), otherwise updated with your suggestions.

File: app/tests/spec/lib/metrics.js (hunk 9 above)
Comment (philbooth) [inline app/tests/spec/lib/metrics.js]: Don't think so, I didn't know that about `before`. Whatever gets the tests to pass is good with me. :)

**Comment by philbooth** [comment]
> updated with your suggestions

:+1:

File: app/scripts/views/base.js [hunk 10]
```diff
@@ -611,14 +610,12 @@ function (Cocktail, _, Backbone, Raven, $, p, AuthErrors,
 
     /**
      * Log an event with the screen name as a prefix
+     *
+     * @param {string} screenName
```
Comment (vladikoff) [inline app/scripts/views/base.js]: nit: no param screenName

Comment (shane-tomlinson) [inline app/scripts/views/base.js]: Great catch. I copied and pasted from the metrics docs.
