### PR TITLE
fix(experiment): Disable A/B experiment interface for navigator.webdr…

### LINKED ISSUE #6026: Opt out of experiments when `navigator.webdriver` is set
From https://github.com/mozilla/fxapom/issues/206#issuecomment-378859781, there is a `navigator.webdriver` flag that will be set when a page is being run by automated tests:

  https://w3c.github.io/webdriver/webdriver-spec.html#interface

Can we use this as an additional flag to opt out of experiments in order to provide stable UI for testing?  Similar to what we already do here:

  https://github.com/mozilla/fxa-content-server/blob/d1f878b0d4909ca100d488e1a7d9834803ac95c8/app/scripts/lib/experiment.js#L66

### PR DESCRIPTION
**Pull request by vladikoff**
…iver

Fixes #6026 

@mozilla/fxa-devs r?

### CODE REVIEW

File: app/tests/spec/lib/experiment.js [hunk 1]
```diff
@@ -70,6 +70,12 @@ define(function (require, exports, module) {
         assert.equal(expInt3.forceExperiment, 'something');
         assert.isTrue(expInt3.initialized, 'forceExperiment overrides user agent');
       });
+
+      it('supports webdriver override', () => {
+        expOptions.window.navigator.webdriver = true;
+        const expInt4 = new ExperimentInterface(expOptions);
+        assert.isFalse(expInt4.initialized, 'do not init if webdriver override');
+      });
```
Comment (rfk) [inline app/tests/spec/lib/experiment.js]: Is it worth adding a "forceExperiment overrides webdriver" test similar to the "forceExperiment overrides user agent" one above?

Comment (vladikoff) [reply app/tests/spec/lib/experiment.js]: Sure!
