### PR TITLE
fix(stderr events): allow independent on/off configurations for amplitude, client_metrics and flow events

### LINKED ISSUE #6956: Allow for independent on/off configuration items for flow-events, amplitude, and stderr.
Right now the configuration item [client_metrics.stderr_collection_disabled](https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/server/lib/configuration.js#L75) disables *all* the server side metrics, and I inadvertently caused a metrics black-hole expecting just the StderrCollector metrics to be disabled. We should have a way of enabling or disabling these 3 independently.

Blocks #6932

### PR DESCRIPTION
**Pull request by farhan787**
fixes #6956

### CODE REVIEW

File: server/lib/configuration.js [hunk 1]
```diff
@@ -30,6 +30,13 @@ const conf = module.exports = convict({
     env: 'ALLOWED_PARENT_ORIGINS',
     format: Array
   },
+  amplitude: {
+    disabled: {
+      default: false,
+      doc: 'disable amplitude events to stderr',
+      env: 'DISABLE_AMPLITUDE_STDERR'
```
Comment (philbooth) [inline server/lib/configuration.js]: This should have `format: Boolean`.

File: server/lib/configuration.js [hunk 2]
```diff
@@ -217,6 +224,11 @@ const conf = module.exports = convict({
     env: 'FLOW_ID_KEY',
     format: String
   },
+  flow_metrics_disabled: {
+    default: false,
+    doc: 'disable flow metrics output to stderr',
+    env: 'DISABLE_FLOW_METRICS_STDERR'
```
Comment (philbooth) [inline server/lib/configuration.js]: This should have `format: Boolean`.

File: server/lib/amplitude.js [hunk 3]
```diff
@@ -151,7 +152,7 @@ function receiveEvent (event, request, data) {
     )
   );
 
-  if (amplitudeEvent) {
+  if (! amplitude && amplitudeEvent) {
```
Comment (philbooth) [inline server/lib/amplitude.js]: Shouldn't this be testing `amplitude.disabled`?

File: tests/server/flow-event.js [hunk 4]
```diff
@@ -13,11 +13,11 @@ registerSuite('flow-event', {
...
     config = {
       /*eslint-disable camelcase*/
-      client_metrics: {
-        stderr_collector_disabled: false
-      },
       flow_id_expiry: 7200000,
-      flow_id_key: 'foo'
+      flow_id_key: 'foo',
+      flow_metrics_disabled: {
+        default: false
```
Comment (philbooth) [inline tests/server/flow-event.js]: It looks like this should be `flow_metrics_disabled: false`.

**Comment by philbooth** [comment]
@farhan787, a shorter commit message would work better with `git log`. 72 characters is usually the maximum length we try to stay within.

Anything you think is appropriate, or something along the lines of `fix(metrics): add independent config to disable amplitude/flow events` if you're not sure...

**Comment by farhan787** [comment]
> @farhan787, a shorter commit message would work better with `git log`. 72 characters is usually the maximum length we try to stay within.

@philbooth thanks a lot for correcting me, I'll keep this in my mind. Btw, this is the fastest review that I've got ever 💯

File: server/lib/amplitude.js [hunk 5]
```diff
@@ -19,6 +19,7 @@ const logger = require('./logging/log')();
 const ua = require('./user-agent');
 
 const SERVICES = require('./configuration').get('oauth_client_id_map');
```
Comment (shane-tomlinson) [inline server/lib/amplitude.js]: `require('./configuration')` is called twice, before either of these lines can you set a variable `const config=require('./configuration');` and update these two lines to use the `config` reference?

File: server/lib/configuration.js [hunk 6]
```diff
@@ -30,6 +30,14 @@ const conf = module.exports = convict({
     env: 'ALLOWED_PARENT_ORIGINS',
     format: Array
   },
+  amplitude: {
+    disabled: {
+      default: false,
```
Comment (shane-tomlinson) [inline server/lib/configuration.js]: Perfect!

File: server/lib/amplitude.js [hunk 7]
```diff
@@ -151,7 +152,7 @@ function receiveEvent (event, request, data) {
     )
   );
 
-  if (amplitudeEvent) {
+  if (! amplitude.disabled && amplitudeEvent) {
```
Comment (shane-tomlinson) [inline server/lib/amplitude.js]: Instead of wasting CPU cycles doing the processing only to ignore the result, return early [on line 137](https://github.com/mozilla/fxa-content-server/pull/7088/files#diff-2a83e43540a70e8aa80daa6c26a3de6dR137) if `amplitude.disabled` is true.

File: server/lib/configuration.js [hunk 8]
```diff
@@ -30,6 +30,14 @@ const conf = module.exports = convict({
...
+      doc: 'disable amplitude events to stderr',
```
Comment (shane-tomlinson) [inline server/lib/configuration.js]: Can you change this doc for clarity to `Disable amplitude events`

File: server/lib/configuration.js [hunk 9]
```diff
@@ -30,6 +30,14 @@ const conf = module.exports = convict({
...
+      env: 'DISABLE_AMPLITUDE_STDERR',
```
Comment (shane-tomlinson) [inline server/lib/configuration.js]: Can you remove the `_STDERR` suffix here?

File: server/lib/configuration.js [hunk 10]
```diff
@@ -217,6 +225,12 @@ const conf = module.exports = convict({
     env: 'FLOW_ID_KEY',
     format: String
   },
+  flow_metrics_disabled: {
+    default: false,
+    doc: 'disable flow metrics output to stderr',
+    env: 'DISABLE_FLOW_METRICS_STDERR',
```
Comment (shane-tomlinson) [inline server/lib/configuration.js]: Since the previous two environment variables start with `FLOW_`, let's keep the same prefix. Can you remove the `_STDERR` suffix too? Maybe just `FLOW_METRICS_DISABLED`.

File: server/lib/flow-event.js [hunk 11]
```diff
@@ -226,8 +226,10 @@ function logFlowEvent (event, data, request) {
   optionallySetFallbackData(eventData, 'service', data.client_id);
   optionallySetFallbackData(eventData, 'entrypoint', data.entryPoint);
 
-  // The data pipeline listens on stderr.
-  process.stderr.write(JSON.stringify(eventData) + '\n');
+  if (! FLOW_METRICS_DISABLED) {
```
Comment (shane-tomlinson) [inline server/lib/flow-event.js]: You are already returning early [if FLOW_METRICS_DISABLED](https://github.com/mozilla/fxa-content-server/pull/7088/files#diff-426670954645c673de319a60a241f7c4R87) is true, no need to do it here too.

File: tests/server/flow-event.js [hunk 12]
```diff
@@ -13,11 +13,9 @@ registerSuite('flow-event', {
   beforeEach: function() {
     config = {
       /*eslint-disable camelcase*/
-      client_metrics: {
-        stderr_collector_disabled: false
-      },
       flow_id_expiry: 7200000,
-      flow_id_key: 'foo'
+      flow_id_key: 'foo',
+      flow_metrics_disabled: false
```
Comment (shane-tomlinson) [inline tests/server/flow-event.js]: We are going to need a test if `flow_metrics_disabled` is true, then no flow events should be logged.

File: server/lib/amplitude.js (hunk 5 above)
Comment (farhan787) [reply server/lib/amplitude.js]: sure

File: server/lib/configuration.js (hunk 6 above)
Comment (farhan787) [reply server/lib/configuration.js]: Thanks

File: server/lib/configuration.js (hunk 8 above)
Comment (farhan787) [reply server/lib/configuration.js]: sure, that's a nice one.

File: tests/server/amplitude.js [hunk 13]
```diff
@@ -26,6 +26,7 @@ const APP_VERSION = /^[0-9]+\.([0-9]+)\./.exec(pkg.version)[1];
 
 registerSuite('amplitude', {
   beforeEach: function() {
+    amplitude.disabled = false;
```
Comment (farhan787) [inline tests/server/amplitude.js]: @shane-tomlinson I think I'm messing something here

File: server/lib/amplitude.js [hunk 14]
```diff
@@ -133,7 +135,7 @@ const transform = initialize(SERVICES, EVENTS, FUZZY_EVENTS);
 module.exports = receiveEvent;
 
 function receiveEvent (event, request, data) {
-  if (! event || ! request || ! data) {
+  if (! amplitude.disabled || ! event || ! request || ! data) {
```
Comment (vbudhram) [inline server/lib/amplitude.js]: We should remove the `!` here since we would want it to return if the `amplitude.disabled=true`

Comment (vbudhram) [reply server/lib/amplitude.js]: This is probably the cause of some of your test failures.

File: tests/server/amplitude.js [hunk 15]
```diff
@@ -46,6 +47,14 @@ registerSuite('amplitude', {
       assert.lengthOf(amplitude, 3);
     },
 
+    'disable writing amplitude events if amplitude.diabled is true': () => {
```
Comment (vbudhram) [inline tests/server/amplitude.js]: Your comment seems right, but in the test case you are not actually sending an amplitude event. See the `flow.signin_from.bar` test below for an basic example that sends an amplitude event and then tries to see what was logged.

In the disabled case, nothing should have been logged.

File: tests/server/flow-event.js [hunk 16]
```diff
@@ -60,6 +58,18 @@ registerSuite('flow-event', {
       assert.lengthOf(flowEvent, 3);
     },
 
+    'call flowEvent with flow_metrics_disabled true': {
+      beforeEach() {
```
Comment (vbudhram) [inline tests/server/flow-event.js]: Same as above, you will need to actually try to log a flowEvent and test that nothing was output. See `call flowEvent with valid flow data` test for an example

File: tests/server/amplitude.js (hunk 15 above)
Comment (farhan787) [reply tests/server/amplitude.js]: @vbudhram thanks for correcting me.

File: server/lib/configuration.js [hunk 17]
```diff
@@ -30,6 +30,14 @@ const conf = module.exports = convict({
     env: 'ALLOWED_PARENT_ORIGINS',
     format: Array
   },
+  amplitude: {
+    disabled: {
+      default: false,
+      doc: 'Disable amplitude events',
+      env: 'DISABLE_AMPLITUDE',
```
Comment (shane-tomlinson) [inline server/lib/configuration.js]: Could you rename the environment variable to `AMPLITUDE_DISABLED` for consistency with other environment variable names?

Comment (farhan787) [reply server/lib/configuration.js]: @shane-tomlinson sure.
