### PR TITLE
fix(settings): unblock rendering of settings on communication prefs screen

### LINKED ISSUE #3061: new settings panel blocks waiting on basket /lookup-user
It looks to me that the new settings panel blocks waiting on basket /lookup-user.

### PR DESCRIPTION
**Pull request by zaach**
Fixes #3061. Using `afterVisible` from subviews does not block rendering of the settings page.

@shane-tomlinson r?

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@zaach - With this diff applied, I see some unexpected behavior:

```diffdiff --git a/app/scripts/lib/marketing-email-client.js b/app/scripts/lib/marketing-email-client.js
index b30f3f1..8b6c641 100644
--- a/app/scripts/lib/marketing-email-client.js
+++ b/app/scripts/lib/marketing-email-client.js
@@ -42,6 +42,8 @@ define([
       var self = this;
       return this._request('get', '/lookup-user', accessToken)
         .then(function (response) {
+          throw MarketingEmailErrors.toError('NETWORK_FAILURE');
+
           // TODO
           // I would prefer to place this into the MarketingEmailPrefs model
           // but doing so required passing around the preferencesUrl to lots of
```

No error message is displayed. Expected?

File: app/scripts/views/settings/communication_preferences.js [hunk 1]
```diff
@@ -35,11 +41,15 @@ function (Cocktail, Xss, Constants, MarketingEmailErrors, Metrics, BaseView, For
...
 
-    beforeRender: function () {
+    afterVisible: function () {
       var self = this;
       var emailPrefs = self.getMarketingEmailPrefs();
+
       return emailPrefs.fetch()
-        .fail(function (err) {
+        .then(function () {
+          return self.render();
```
Comment (shane-tomlinson) [inline app/scripts/views/settings/communication_preferences.js]: For this PR this approach is fine, but it does allow for a flash of button content if the user reloads the page with the communications_preferences panel open:

subscribe-unsubscribe-flash

A solution to this is to render the page with a "loading" button (gray button with throbber) while the fetch is outstanding, then re-render the button (or the entire screen) with the appropriate text once the emailPrefs fetch has completed.

Since re-loading the page with the communication prefs screen is probably not a common occurrence, "meh" for now.

**Comment by shane-tomlinson** [comment]
If all the tests go green, r+, thanks @zaach!

**Comment by shane-tomlinson** [comment]
@zaach - the `communication preferences - do not opt in to the marketing email` consistently fails for me.

```
× firefox on any platform - communication preferences - do not opt in to the marketing email (30.044s)
CancelError: Timeout reached on firefox on any platform - communication preferences - do not opt in to the marketing email
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.do not opt in to the marketing email [as test]  <tests/functional/email_opt_in.js:215:12>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
```

**Comment by zaach** [comment]
@shane-tomlinson I can't reproduce– have you made sure to rebuild the SASS files?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson I can't reproduce– have you made sure to rebuild the SASS files?

I'll re-check to make sure, I'd guess this as the most likely cause of the issue.

**Comment by shane-tomlinson** [comment]
@zaach - I had two problems, the first is I needed to regenerate the SASS, the second is I had a fake-basket-server that intentionally introduced delay in responding.
