### PR TITLE
fix(test): Fix the requireOnDemand unit tests in Fx 52.

### LINKED ISSUE #4274: Failing unit tests against Fx 52
When running the unit tests with Nightly, I see these errors:

```
lib/require-on-demand

    successful load
        "before each" hook
        ‣

        Not allowed to define a non-configurable property on the WindowProxy object
        wrapMethod@http://127.0.0.1:3030/bower_components/sinon/lib/sinon/util/core.js:128:17
        stub@http://127.0.0.1:3030/bower_components/sinon/lib/sinon/stub.js:67:20
        stub@http://127.0.0.1:3030/bower_components/sinon/lib/sinon/collection.js:117:33
        @http://127.0.0.1:3030/tests/spec/lib/require-on-demand.js:24:9
        callFn@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4338:18
        Runnable.prototype.run@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4331:7
        next@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4613:5
        Runner.prototype.hook/<@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4630:5
        timeslice@http://127.0.0.1:3030/bower_components/mocha/mocha.js:5761:5
        setTimeout handler*Mocha.Runner.immediately@http://127.0.0.1:3030/bower_components/mocha/mocha.js:5777:24
        Runner.prototype.hook@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4629:3
        next@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4656:5
        Runner.prototype.hooks@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4667:3
        Runner.prototype.hookUp@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4680:3
        next/</<@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4818:9
        done@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4300:5

    unsuccessful load
        "before each" hook
        ‣

        Not allowed to define a non-configurable property on the WindowProxy object
        wrapMethod@http://127.0.0.1:3030/bower_components/sinon/lib/sinon/util/core.js:128:17
        stub@http://127.0.0.1:3030/bower_components/sinon/lib/sinon/stub.js:67:20
        stub@http://127.0.0.1:3030/bower_components/sinon/lib/sinon/collection.js:117:33
        @http://127.0.0.1:3030/tests/spec/lib/require-on-demand.js:67:9
        callFn@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4338:18
        Runnable.prototype.run@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4331:7
        next@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4613:5
        Runner.prototype.hook/<@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4630:5
        timeslice@http://127.0.0.1:3030/bower_components/mocha/mocha.js:5761:5
        setTimeout handler*Mocha.Runner.immediately@http://127.0.0.1:3030/bower_components/mocha/mocha.js:5777:24
        Runner.prototype.hook@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4629:3
        next@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4656:5
        Runner.prototype.hooks@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4667:3
        Runner.prototype.hookUp@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4680:3
        next/</<@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4818:9
        done@http://127.0.0.1:3030/bower_components/mocha/mocha.js:4300:5

```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Unit tests blow up in Fx 52 when trying to stub window.require, saying
defining a non-configurable property on a WindowProxy is verboten.

Instead of working with the real window object, pass in a window mock

fixes #4274

@vbudhram and @philbooth - another one!
@seanmonstar - if you want to get in on the front-end action, have at it!

### CODE REVIEW

File: app/tests/spec/lib/require-on-demand.js [hunk 1]
```diff
@@ -34,26 +36,22 @@ define(function (require, exports, module) {
         });
       });
 
-      afterEach(function () {
-        sandbox.restore();
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/require-on-demand.js]: I don't believe so since windowMock is created again for each test. The stubs used to be created by overwriting the real `window.require`, and I wanted to restore that object to its original state.

**Comment by philbooth** [comment]
LGTM, r+! 👍

**Comment by philbooth** [comment]
@shane-tomlinson, that r+ carries forward to include b555c85 btw.
