### PR TITLE
fix(logging): switch to mozlog

### LINKED ISSUE #1994: convert logging from intel to mozlog
[mozlog](https://github.com/mozilla/mozlog) formats output using the Mozilla Cloud Services standard and can be grokked easier by the Heka parsers.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1994

### CODE REVIEW

File: server/lib/configuration.js [hunk 1]
```diff
@@ -75,6 +75,19 @@ var conf = module.exports = convict({
...
+      env: 'LOG_LEVEL',
+      default: 'info'
+    },
+    fmt: {
+      format: ['heka', 'pretty'],
+      default: 'heka'
+    }
+  },
   route_log_format: {
     format: [ 'default_fxa', 'dev_fxa', 'default', 'dev', 'short', 'tiny' ],
```
Comment (zaach) [inline server/lib/configuration.js]: Nevermind– we're still using the express logger for route logging, which has its own format setting.

**Comment by zaach** [comment]
:+1:
