### PR TITLE
fix(config): allow env vars for experiment config

### LINKED ISSUE #4780: docker: .git/FETCH_HEAD: Permission denied
Experiment with the container for this server, I'm getting:

> fxa-content-web_1  | {"Timestamp":1488734612102000000,"Logger":"fxa-content-server","Type":"route.500.Error: Command failed: /bin/sh -c git fetch -v origin dev && git reset --hard FETCH_HEAD\nerror: cannot open .git/FETCH_HEAD: Permission denied\n\n","Severity":2,"Pid":7,"EnvVersion":"2.0","Fields":{"stack":"\nerror: cannot open .git/FETCH_HEAD: Permission denied\n\n\n    at ChildProcess.exithandler (child_process.js:213:12)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:854:16)\n    at Socket.<anonymous> (internal/child_process.js:330:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:487:12)"}}

Besides fixing this I guess it might be useful to also add ENV vars for the experiments section

cc @jbuck

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4780 

@mozilla/fxa-devs r?

### CODE REVIEW

File: server/lib/configuration.js [hunk 1]
```diff
@@ -123,15 +123,18 @@ const conf = module.exports = convict({
...
       default: 'github:mozilla/fxa-content-experiments#dev',
-      doc: 'git url for experiments repo. set to empty to not pull'
+      doc: 'git url for experiments repo. set to empty to not pull',
+      env: 'EXPERIMENTS_GIT_REPO'
     },
     watch: {
       default: false,
-      doc: 'poll the experiments git repo for changes'
+      doc: 'poll the experiments git repo for changes',
+      env: 'EXPERIMENTS_POLL'
```
Comment (philbooth) [inline server/lib/configuration.js]: Shouldn't we also specify a `format` for this one to ensure it coerces to `Boolean` correctly?

Also, the current `doc` and `env` don't make clear that we're looking for an on/off value here, only the `default` does. Should we update them to make the booleanness explicit, `EXPERIMENTS_ENABLE_POLLING`?

(the current name/description could equally apply to, say, milliseconds polling interval)

**Comment by philbooth** [comment]
r+, I also a left a little inline comment about including a `format` and changing the name of the `_POLL` variable.

**Comment by vladikoff** [comment]
> r+, I also a left a little inline comment about including a format and changing the name of the _POLL variable.

Yeah, exactly the feedback I was looking for, thanks! Will updated
