### PR TITLE
fix(basket): Match the expected basket subscribe & lookup-user API

### LINKED ISSUE #6076: Update marketing-email-prefs and marketing-email-client to match native basket api
See https://bugzilla.mozilla.org/show_bug.cgi?id=1417298#c6 and https://github.com/mozilla/fxa-basket-proxy/pull/56

* [x] - [SCOPES](https://github.com/mozilla/fxa-content-server/blob/71a20af50045a4e62bc5f42f216a92b727fb4543/app/scripts/models/marketing-email-prefs.js#L16) should be `basket profile:email`
* [ ] - POST to `/subscribe/` not `/subscribe`, ensure request includes the `X-Requested-With: XMLHttpRequest` header
* [x] - The [POST to /subscribe/](https://github.com/mozilla/fxa-content-server/blob/71a20af50045a4e62bc5f42f216a92b727fb4543/app/scripts/lib/marketing-email-client.js#L67) should encode data as `application/x-www-form-urlencoded` instead of JSON.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
* POST to `/subscribe/`
  * Set `content-type: application/x-www-form-urlencoded` header
  * Send `X-Requested-With: XMLHttpRequest` header
* GET /lookup-user with a new query parameter, email

fixes #6076

@rfk - r?

screen shot 2018-05-03 at 20 47 31

screen shot 2018-05-03 at 20 29 49

screen shot 2018-05-03 at 20 47 42

### CODE REVIEW

File: app/scripts/lib/marketing-email-client.js [hunk 1]
```diff
@@ -9,7 +9,8 @@
 define(function (require, exports, module) {
```
Comment (vladikoff) [inline app/scripts/lib/marketing-email-client.js]: While we are here, do you wanna nuke this `define` wrapper? :D

File: app/scripts/lib/marketing-email-client.js [hunk 2]
```diff
@@ -29,44 +30,56 @@ define(function (require, exports, module) {
...
     optIn (accessToken, newsletterId) {
       const cleanedSourceUrl =
         Url.cleanSearchString(this._window.location.href, ALLOWED_SOURCE_URL_QUERY_PARAMS);
-      return this._request('post', '/subscribe', accessToken, {
-        newsletters: newsletterId,
-        source_url: cleanedSourceUrl //eslint-disable-line camelcase
+
+      return this._request({
+        accessToken,
+        // Baskset expectes form-urlencoded data rather than JSON, see #6076
```
Comment (vladikoff) [inline app/scripts/lib/marketing-email-client.js]: typo `Baskset`

File: app/scripts/lib/marketing-email-client.js (hunk 1 above)
Comment (shane-tomlinson) [reply app/scripts/lib/marketing-email-client.js]: I was tempted to, but didn't want to cause a blowup in the diff size. Will remove the wrapper now. ;)
