### PR TITLE
fix(metrics): Cap the max user submitted event offset to 2 days.

### LINKED ISSUE #5188: Some fxa.content.loaded.median time values are totally unrealistic, causing problems with metrics
screen shot 2017-06-30 at 00 04 08

We should filter out values > N. Maybe N should be 2 days.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #5188 

@philbooth - mind giving this a review since we spoke about this in SF?

### CODE REVIEW

File: server/lib/routes/post-metrics.js [hunk 1]
```diff
@@ -44,7 +47,7 @@ const BODY_SCHEMA = {
   entryPoint: STRING_TYPE.regex(ENTRYPOINT_PATTERN).optional(),
   entrypoint: STRING_TYPE.regex(ENTRYPOINT_PATTERN).optional(),
   events: joi.array().items(joi.object().keys({
```
Comment (vladikoff) [inline server/lib/routes/post-metrics.js]: do we have the data of the current average offset?  or should we submit that ?

**Comment by philbooth** [comment]
LGTM, r+

Just wondering, would it also be possible to do some stricter validation in the code itself that ensures `offset` for each event is less than whatever the offset would have been when flush was called?

**Comment by vladikoff** [comment]
```
FAIL: metrics-collector-stderr - it is enabled  with config options set to false (150ms)
Error: limit must be a number or reference
  at Object.exports.assert  <node_modules/joi/node_modules/hoek/lib/index.js:736:11>
  at .max  <node_modules/joi/lib/number.js:141:14>
  at Object.<anonymous>  <server/lib/routes/post-metrics.js:50:25>
  at Module._compile  <module.js:570:32>
  at Object.Module._extensions..js  <module.js:579:10>
  at Object.require.extensions.(anonymous function)  <node_modules/proxyquire/lib/proxyquire.js:243:43>
  at Module.load  <module.js:487:32>
  at tryModuleLoad  <module.js:446:12>
  at Function.Module._load  <module.js:438:3>
  at Module.require  <module.js:497:17>
  at Proxyquire._withoutCache  <node_modules/proxyquire/lib/proxyquire.js:177:12>
  at Proxyquire.load  <node_modules/proxyquire/lib/proxyquire.js:134:15>
  at Test.suite.it is enabled  with config options set to false [as test]  <tests/server/metrics-collector-stderr.js:154:23>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
FAIL: metrics-collector-stderr - it can be disabled with config options (1ms)
Error: limit must be a number or reference
  at Object.exports.assert  <node_modules/joi/node_modules/hoek/lib/index.js:736:11>
  at .max  <node_modules/joi/lib/number.js:141:14>
  at Object.<anonymous>  <server/lib/routes/post-metrics.js:50:25>
  at Module._compile  <module.js:570:32>
  at Object.Module._extensions..js  <module.js:579:10>
  at Object.require.extensions.(anonymous function)  <node_modules/proxyquire/lib/proxyquire.js:243:43>
  at Module.load  <module.js:487:32>
  at tryModuleLoad  <module.js:446:12>
  at Function.Module._load  <module.js:438:3>
  at Module.require  <module.js:497:17>
  at Proxyquire._withoutCache  <node_modules/proxyquire/lib/proxyquire.js:177:12>
  at Proxyquire.load  <node_modules/proxyquire/lib/proxyquire.js:134:15>
  at Test.suite.it can be disabled with config options [as test]  <tests/server/metrics-collector-stderr.js:179:23>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
2/3 tests failed
PASS: metrics-errors - #get deprecated /metrics-errors endpoint - retu
```

File: server/lib/routes/post-metrics.js (hunk 1 above)
Comment (shane-tomlinson) [inline server/lib/routes/post-metrics.js]: We don't, and since metrics can be sent in distinct bundles, it'd be tough to find out. Perhaps a good measure is the flow complete time?

**Comment by philbooth** [comment]
Still LGTM, r+
