### PR TITLE
fix(client): Flush metrics before redirecting to an external link.

### LINKED ISSUE #4458: metrics not reported in Safari for iOS if user clicks App Store link
Noticed this while testing https://github.com/mozilla/fxa-content-server/pull/4370

STR:
1. Using Fx Desktop, sign up for Sync
2. Using Safari simulator, open verification link
3. Click on App Store link.
4. Look at console for metrics (in the background).

no-metrics-reported

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Safari for iOS cannot flush metrics in an `unload` or `beforeunload`
handler. We had code in the `signup-mixin` to flush metrics for the
"Looking for Sync" button, but not elsewhere. This is problematic for
the App Store links that cause a redirect, but do not flush metrics.

This PR ensures all redirecting external links flush metrics before
doing the redirect.

fixes #4458

@vladikoff or @vbudhram - mind reviewing?

Here's a video to contrast with the bug report:

metrics-reported

### CODE REVIEW

File: app/scripts/views/mixins/signup-mixin.js [hunk 1]
```diff
@@ -90,19 +90,8 @@ define(function (require, exports, module) {
...
-     * interceptor function. Flushes metrics before redirecting
-     * @param {Event} event - click event
-     */
-    onSuggestSyncClick (event) {
-      event.preventDefault();
-
+    onSuggestSyncClick () {
       this.logViewEvent('sync-suggest.clicked');
-
-      this.metrics.flush()
```
Comment (shane-tomlinson) [inline app/scripts/views/mixins/signup-mixin.js]: I took the idea from here, and removed this.

File: app/scripts/views/mixins/external-links-mixin.js [hunk 2]
```diff
@@ -32,14 +37,91 @@ define(function (require, exports, module) {
...
+      if (this._shouldIgnoreClick(event)) {
+        return p();
+      }
+
+      event.preventDefault();
+      // Let the current view handle this, otherwise
+      // the `app` view will also flush.
+      event.stopImmediatePropagation();
+
+      return this._flushMetricsThenRedirect(event.currentTarget.href);
```
Comment (vladikoff) [inline app/scripts/views/mixins/external-links-mixin.js]: 👍

**Comment by vladikoff** [comment]
LGTM 👍
