### PR TITLE
fix(sentry): adjust cache busting files for Sentry

### LINKED ISSUE #3363: figure out how to not have sentry ask for defunct /scripts/deadbeef.main.js when release goes live
Not sure this is possible. Maybe the fix will be for kibana to have a UA that it can exclude. 

But anyways, when a new release goes live, there are a flurry of requests for the old version of main.js that shows as a spike of 404, which is an unsettling bit of noise.

### LINKED ISSUE #3420: Remove the hex hash from main.js Sentry reports
Talked to @ckarlof a bit about Sentry and we can try removing the cache busting from Sentry reports to get consistent errors for each deploy.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3420
Fixes #3363

### CODE REVIEW

**Comment by vladikoff** [comment]
Basically strips the hex cache busters here:

https://cloud.githubusercontent.com/assets/128755/12521729/537bce90-c11a-11e5-9154-67144a5ce67d.png

This should make errors work better in Sentry

@shane-tomlinson @philbooth r?

File: app/scripts/lib/sentry.js [hunk 1]
```diff
@@ -43,6 +43,22 @@ define(function (require, exports, module) {
       if (data.request.headers && data.request.headers.Referer) {
         data.request.headers.Referer = cleanUpQueryParam(data.request.headers.Referer);
       }
+
+      // in production we remove cache busting file names from js files.
+      // replace any 'scripts/1a22742b.head.js' with 'scripts/head.js'
+      // this helps errors consistent across deploys
```
Comment (shane-tomlinson) [inline app/scripts/lib/sentry.js]: `errors consistent` => `errors stay consistent`

File: app/scripts/lib/sentry.js [hunk 2]
```diff
@@ -43,6 +43,22 @@ define(function (require, exports, module) {
...
+      var removeRegex = /\/[0-9A-Fa-f]{8}./g;
```
Comment (shane-tomlinson) [inline app/scripts/lib/sentry.js]: If you only want a final period to be removed, you should use `\.`, otherwise, any character that follows the hex value will be removed. You can also shorten this by using case insensitive matching:

```js
var removeRegex = /\/[0-9a-f]{8}\./gi;
```

File: app/scripts/lib/sentry.js [hunk 3]
```diff
@@ -43,6 +43,22 @@ define(function (require, exports, module) {
...
+      var addPart = '/';
+      if (data.stacktrace && data.stacktrace.frames) {
+        _.each(data.stacktrace.frames, function (frame) {
+          frame.filename = frame.filename.replace(removeRegex, addPart);
+        });
+      }
+
+      if (data.culprit) {
+        data.culprit = data.culprit.replace(removeRegex, addPart);
```
Comment (shane-tomlinson) [inline app/scripts/lib/sentry.js]: Can we get a test for these two changes?

**Comment by shane-tomlinson** [comment]
Manual testing looks good. Using production resource, I manually throw an error in `app.js->allResourcesReady` and see the following reported to metrics-errors (decoded for readability):

> {"project":"metrics-errors","logger":"javascript","platform":"javascript","request":{"url":"http://127.0.0.1:3030/signup","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"}},"exception":{"type":"Error","value":"uh oh"},"stacktrace":{"frames":[{"filename":"http://127.0.0.1:3030/scripts/main.js","lineno":17,"colno":21137,"function":"l","in_app":true},{"filename":"http://127.0.0.1:3030/scripts/main.js","lineno":17,"colno":23089,"function":"E","in_app":true},{"filename":"http://127.0.0.1:3030/scripts/main.js","lineno":17,"colno":23135,"function":"F","in_app":true},{"filename":"http://127.0.0.1:3030/scripts/main.js","lineno":33,"colno":5629,"function":"d.prototype.allResourcesReady","in_app":true}]},"culprit":"http://127.0.0.1:3030/scripts/main.js","message":"uh oh","extra":{"session:duration":200},"event_id":"7ea374d90f0b486da4cced9071c16250"}"



Let's ensure we don't regress and add a test that ensures the sha is removed.

With the above error thrown, I do not see a subsequent request for main.js in the developer console. Where are the requests that generate the 404s made, from the server?

File: app/scripts/lib/sentry.js (hunk 3 above)
Comment (vladikoff) [inline app/scripts/lib/sentry.js]: Done!

**Comment by vladikoff** [comment]
> Let's ensure we don't regress and add a test that ensures the sha is removed.

:+1: 

> With the above error thrown, I do not see a subsequent request for main.js in the developer console. Where are the requests that generate the 404s made, from the server?

Yeap Sentry does that sometimes, but this should fix it. More importantly we should now get more consistent errors throughout the train deploys.

**Comment by shane-tomlinson** [comment]
@vladikoff - Obviously not for this now merged PR - would the FxA version, e.g., v0.54.1, be useful in the error reports sent to Sentry and internal metrics?
