### PR TITLE
fix(content-server): open TOS/PP in new tab if inside an iframe

### LINKED ISSUE #2351: TOS/PP have an ugly scroll bar when loaded in an iframe
When FxA is loaded in an iframe, the TOS/PP agreements cause an ugly scroll bar to be displayed:

screen shot 2015-04-26 at 17 17 06

Possible work arounds:

* Expand the containing iframe to expand to the size of the contents.
* Open the TOS/PP agreements in a new tab.

cc @ryanfeeley and @johngruen - what should we do here?

Ref #1968, #2101, #2225, #2337

### PR DESCRIPTION
**Pull request by TDA**
Fixes #2351
Check for presence of link inside iframe
Open link in new tab
Unit tests pass, travis should be green.
@shane-tomlinson 
@zaach 
@pdehaan 
@vladikoff

### CODE REVIEW

**Comment by pdehaan** [comment]
@TDA:

```
app/scripts/router.js
  293:19  error  Function 'anonymous' has a complexity of 9  complexity
  312:27  error  A space is required after ','               comma-spacing
✖ 2 problems (2 errors, 0 warnings)
Warning: Task "eslint:app" failed. Use --force to continue.
Aborted due to warnings.
```

**Comment by TDA** [comment]
@pdehaan Should be fixed now, thanks for that!

**Comment by shane-tomlinson** [comment]
@TDA - I like the simplicity of this approach, a few comments:

* It would be preferable if all of the logic related to the TOS/PP agreements lived in the views related to the TOS/PP agreements. Having all the related logic centralized makes it easier to find and causes less surprises. Try to move your logic to any of:
  * https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/tos.js
  * https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/pp.js
  * https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/legal_copy.js
* Instead of using a [localized iframe check](https://github.com/mozilla/fxa-content-server/pull/2643/files#diff-7dc4529b94b3a1ef3fd9ca92068a3bbeR309), use [environment.js->isFramed)(https://github.com/mozilla/fxa-content-server/blob/7ee292d3af9f68afb088de14c723f1ae6369f5cb/app/scripts/lib/environment.js#L66) so only one location ever needs to be updated if the check changes.
* Instead of adding an event handler to open the link, consider adding the `target="_blank"` attribute to the links in the templates if the user is currently viewing FxA from within an iframe.

**Comment by shane-tomlinson** [comment]
I'm a total idiot, ignore tos.js, pp.js and legal_copy.js. The logic needs to make its way into sign_in.js, sign_up.js, and force_auth.js.  Hmmm. What's the best approach here?

**Comment by shane-tomlinson** [comment]
I'm backtracking on everything. Keep it in router.js.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f07fa325768101797dd8dae4d6c52ad0c3d501f6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by pdehaan** [comment]
```
app/scripts/router.js
  312:6  error  Trailing spaces not allowed  no-trailing-spaces
✖ 1 problem (1 error, 0 warnings)
Warning: Task "eslint:app" failed. Use --force to continue.
Aborted due to warnings.
```

These ESLint rules don't mess around!

**Comment by TDA** [comment]
@pdehaan T_T I was still working on it. Forgive me Sensei! I shall not mess with ESLint here upon. :D

**Comment by TDA** [comment]
@shane-tomlinson 
@vladikoff 
@pdehaan 
@zaach 
Hulk Squash? (am i doing it right?)
hulk

File: app/scripts/router.js [hunk 1]
```diff
@@ -290,7 +292,9 @@ function (
       $(document).on('click', 'a[href^="/"]', this.onAnchorClick.bind(this));
     },
 
-    onAnchorClick: function (event) {
+    onAnchorClick: function (event, environment) {
+      /*eslint complexity: [2, 8] */
+      environment = environment || new Environment(this.window);
```
Comment (vladikoff) [inline app/scripts/router.js]: is it possible to initialize the environment in the initialization of router.js: https://github.com/TDA/fxa-content-server/blob/issue-2351-tos-pp-new-window/app/scripts/router.js#L125 and use it here ?

Comment (TDA) [inline app/scripts/router.js]: @vladikoff  Da-Doneee :dancer:

File: app/scripts/router.js [hunk 2]
```diff
@@ -305,7 +308,10 @@ function (
 
       // Remove leading slashes
       var url = $(event.currentTarget).attr('href').replace(/^\//, '');
-
+      if (this.environment.isFramed() && url.indexOf('legal') > -1) {
+        window.open(url, '_blank');
```
Comment (shane-tomlinson) [inline app/scripts/router.js]: Use `this.window` instead of `window` directly. Ensure this path is tested.

File: app/tests/spec/lib/router.js [hunk 3]
```diff
@@ -431,6 +438,20 @@ function (chai, sinon, Backbone, Router, SignInView, SignUpView, ReadyView,
...
+      it('does not call navigate if inside an iframe', function () {
+        setUpIFrameLink();
+
+        testNoNavigation();
+      });
+
+      it('opens a new window if inside an iframe', function () {
+        setUpIFrameLink();
+
+        sinon.spy(window, 'open');
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/router.js]: Use a mock window object instead of spying on window.open directly.

File: app/scripts/router.js [hunk 4]
```diff
@@ -139,7 +141,7 @@ function (
       // back is enabled after the first view is rendered or
       // if the user is re-starts the app.
       this.canGoBack = this.window.sessionStorage.canGoBack || false;
-
+      this.environment = new Environment(this.window);
```
Comment (shane-tomlinson) [inline app/scripts/router.js]: Make this a pseudo-private variable by adding the `_` prefix. Allow an environment to be passed in for testing like:

```js
this.environment = options.environment || new Environment(this.window);
```

That way, we can pass in an environment for unit tests without reaching in to private variables like `this._environment` directly.

Comment (shane-tomlinson) [inline app/scripts/router.js]: Huh, the other private variables do not have the `_` prefix. Hmmm..  That should be changed, but not in this PR.

File: app/tests/spec/lib/router.js [hunk 5]
```diff
@@ -399,6 +399,13 @@ function (chai, sinon, Backbone, Router, SignInView, SignUpView, ReadyView,
         assert.isFalse(router.navigate.called);
       }
 
+      function setUpIFrameLink() {
+        sinon.stub(router.environment, 'isFramed', function () {
```
Comment (shane-tomlinson) [inline app/tests/spec/lib/router.js]: Instead of accessing `router.environment` directly, I would create and pass in an `Environment` object to the Router constructor, then do:

```js
sinon.stub(environment, 'isFramed', function () {
```

This is a subtle change, but the change makes fewer assumptions about what should be internal implementation details of router and the name where the environment object is stored.

File: app/scripts/router.js (hunk 2 above)
Comment (TDA) [inline app/scripts/router.js]: fixed!

File: app/tests/spec/lib/router.js (hunk 3 above)
Comment (TDA) [inline app/tests/spec/lib/router.js]: da-done!

File: app/scripts/router.js (hunk 4 above)
Comment (TDA) [inline app/scripts/router.js]: i added the option thing in. Did u mean leave out '_' for all the variables and add it in a later commit?

File: app/tests/spec/lib/router.js (hunk 5 above)
Comment (TDA) [inline app/tests/spec/lib/router.js]: done :)

**Comment by TDA** [comment]
@pdehaan r?

File: app/scripts/router.js [hunk 6]
```diff
@@ -291,8 +293,10 @@ function (
     },
 
     onAnchorClick: function (event) {
+      /*eslint complexity: [2, 7] */
       // if someone killed this event, or the user is holding a modifier
       // key, ignore the event.
+      var self = this;
```
Comment (vladikoff) [inline app/scripts/router.js]: do we need `self` here?

File: app/scripts/router.js [hunk 7]
```diff
@@ -305,7 +309,10 @@ function (
 
       // Remove leading slashes
       var url = $(event.currentTarget).attr('href').replace(/^\//, '');
-
+      if (this.environment.isFramed() && url.indexOf('legal') > -1) {
+        self.window.open(url, '_blank');
```
Comment (vladikoff) [inline app/scripts/router.js]: https://github.com/mozilla/fxa-content-server/pull/2643/files#r33779332 see, use both of `self` and `this` in the context. there is no nested function

File: app/tests/spec/lib/router.js [hunk 8]
```diff
@@ -431,6 +442,20 @@ function (chai, sinon, Backbone, Router, SignInView, SignUpView, ReadyView,
...
+
+        testNoNavigation();
+      });
+
+      it('opens a new window if inside an iframe', function () {
+        setUpIFrameLink();
+
+        sinon.spy(windowMock, 'open');
+        router.onAnchorClick(event);
+        assert.isTrue(windowMock.open.called);
```
Comment (vladikoff) [inline app/tests/spec/lib/router.js]: :+1:

File: app/scripts/router.js (hunk 6 above)
Comment (TDA) [inline app/scripts/router.js]: oops, must have been left from the time i used a function to test it :D fixed now @vladikoff

**Comment by TDA** [comment]
@vladikoff Squashed, thoughts?

**Comment by vladikoff** [comment]
Tested via 123done, worked well!

**Comment by shane-tomlinson** [comment]
ref #2101

**Comment by TDA** [comment]
@vladikoff Thankoo!
