### PR TITLE
fix(confirm): change resend email limit to first 4 attempts

### LINKED ISSUE #3777: Resend email is limited to the first and forth click
@ryanfeeley says this is a recipe for confusion and we should send every email instead.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3777

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram r?

File: app/tests/spec/views/confirm.js [hunk 1]
```diff
@@ -347,13 +347,13 @@ define(function (require, exports, module) {
                 assert.equal(count, 1);
```
Comment (vbudhram) [inline app/tests/spec/views/confirm.js]: nit: Could possibly assert that resend is visible after each submit to ensure that it disappears at correct value?

**Comment by vbudhram** [comment]
Just the one comment, r+
