### PR TITLE
fix(test): Fix the flaky "learn more" SMS test.

### LINKED ISSUE #4880: flaky functional test - send_sms - learn more
From https://tc-test.dev.lcip.org/viewLog.html?buildId=9265&tab=buildResultsDiv&buildTypeId=fxa_StageTests

> NoSuchWindow: [POST http://localhost:4444/wd/hub/session/bdec3d4b-4870-43f2-a27e-5279fe80291a/window / {"name":"_learn-more"}] Unable to locate window: _learn-more Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800' System info: host: 'cacbf53a9ab5', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '3.14.48-33.39.amzn1.x86_64', java.version: '1.8.0_112' Driver info: org.openqa.selenium.firefox.FirefoxDriver Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, firefox_binary=/home/teamcity/firefox-channels/latest/en-US/firefox/firefox-bin, acceptSslCerts=false, processId=14128, browserVersion=50.1.0, platformVersion=3.14.48-33.39.amzn1.x86_64, name=tests/intern_functional_full, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux, firefox_profile=UEsDBBQACAgIABqafUoAAAAAAAAAA...}] Session ID: 9ecce089-f90c-48f7-996f-3f63ed6f3eab at runRequest <node_modules/intern/node_modules/leadfoot/Session.js:92:40> at <node_modules/intern/node_modules/leadfoot/Session.js:113:39> at new Promise <node_modules/intern/node_modules/dojo/Promise.ts:411:3> at ProxiedSession._post <node_modules/intern/node_modules/leadfoot/Session.js:67:10> at ProxiedSession.Session.switchToWindow <node_modules/intern/node_modules/leadfoot/Session.js:835:15> at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:635:19> at <node_modules/intern/node_modules/dojo/Promise.ts:393:15> at run <node_modules/intern/node_modules/dojo/Promise.ts:237:7> at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at Command.target.(anonymous function) [as switchToWindow] <node_modules/intern/node_modules/leadfoot/Command.js:610:11> at Test.suite.learn more [as test] <tests/functional/send_sms.js:148:10> at <node_modules/intern/lib/Test.js:191:24> at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15> at runCallbacks <node_modules/intern/browser_modules/dojo/Promise.ts:11:11> at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4> at run <node_modules/intern/browser_modules/dojo/Promise.ts:237:7> at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at process._tickCallback <node.js:365:13>

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Sometimes the "_learn_more" window would not be open, esp when run
on slow machines. Use the `switchToWindow` helper which will check
for open windows, and use the window index instead of name.

fixes #4880 

@vladikoff, @jrgm, @vbudhram  - r?

### CODE REVIEW

File: tests/functional/send_sms.js [hunk 1]
```diff
@@ -145,7 +144,7 @@
         .then(openPage(SEND_SMS_URL, SELECTOR_SEND_SMS_HEADER))
         .then(testElementExists(SELECTOR_MARKETING_LINK))
         .then(click(SELECTOR_LEARN_MORE))
-        .switchToWindow(LEARN_MORE_WINDOW_HANDLE)
+        .then(switchToWindow(1))
```
Comment (vladikoff) [inline tests/functional/send_sms.js]: hm i'm surprised this works, i thought they removed lookup by index

Comment (shane-tomlinson) [inline tests/functional/send_sms.js]: We go and get the window handle from the index.

Comment (shane-tomlinson) [inline tests/functional/send_sms.js]: I tried updating the helper function, but that looked like it was going to be a challenge.
