### PR TITLE
fix(broker): Fix the POST /metrics validation error w/ FxSync broker.

### LINKED ISSUE #5066: validation error w/ fx_sync broker
STR

1. Sign up
2. Verify in a different browser
3. Look in the content-server console for:

> 3|content- | fxa-content-server.server.main.ERROR: validation.error {"error":"\"broker\" with value \"fx_sync\" fails to match the required pattern: /^[0-9a-z-]+$/","path":"/metrics"}

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Server validation allows `-`, not `_`. This updates the FxSync
broker's type to be consistent with others and use `-` instead of `_`.

fixes #5066

@philbooth - r?

### CODE REVIEW

File: app/scripts/models/auth_brokers/fx-sync.js [hunk 1]
```diff
@@ -12,14 +12,13 @@ define(function (require, exports, module) {
...
   const BaseAuthenticationBroker = require('models/auth_brokers/base');
-  const { FX_SYNC_CONTEXT } = require('lib/constants');
 
   const proto = BaseAuthenticationBroker.prototype;
 
   module.exports = BaseAuthenticationBroker.extend({
     defaultBehaviors: proto.defaultBehaviors,
 
-    type: FX_SYNC_CONTEXT
+    type: 'fx-sync'
```
Comment (philbooth) [inline app/scripts/models/auth_brokers/fx-sync.js]: Part of me wonders whether we should have some kind of client-side unit test that iterates over all the auth brokers and makes sure their `type` matches the validation regex. What do you think, worth it or a pointless test?

**Comment by philbooth** [comment]
Looks good to me, r+.

File: app/scripts/models/auth_brokers/fx-sync.js (hunk 1 above)
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/fx-sync.js]: Probably a good check to have.
