### PR TITLE
fix(client): No screen transition post confirm signin for OAuth Webchannel keys

### LINKED ISSUE #3966: Patch for https://nodesecurity.io/advisories/130
According to NSP and https://nodesecurity.io/advisories/130, we have four vulnerable dependencies:

```
Running "nsp" task
Warning: (+) 4 vulnerabilities found
 Name           Installed   Patched   Path                                                                                                       
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > grunt-sass@1.1.0 > node-sass@3.8.0 > request@2.71.0 > tough-cookie@2.2.2       https://nodesecurity.io/advisories/130 
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > grunt-z-schema@0.1.0 > z-schema@2.4.10 > request@2.71.0 > tough-cookie@2.2.2   https://nodesecurity.io/advisories/130 
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > request@2.71.0 > tough-cookie@2.2.2                                            https://nodesecurity.io/advisories/130 
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > universal-analytics@0.3.11 > request@2.71.0 > tough-cookie@2.2.2               https://nodesecurity.io/advisories/130 
 Use --force to continue.
```

We should patch this asap.
@vladikoff @pdehaan

### LINKED ISSUE #3996: Failing functional test on latest: " firefox on any platform - oauth webchannel keys - signin a verified account and requesting keys after signing in to sync "
See https://tc-test.dev.lcip.org/viewLog.html?buildId=8014&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests.

The test passes locally, but only because of a timing.

The [last four lines of the test are](https://github.com/mozilla/fxa-content-server/blob/a756fd6b590ad2661be09a04fc36344af51c3c6e/tests/functional/oauth_webchannel_keys.js#L333:L336):

```js
        .then(testElementExists('#fxa-confirm-signin-header'))
        .then(openVerificationLinkDifferentBrowser(email, 1))
        .then(noPageTransition('#fxa-confirm-signin-header'))
        .then(testIsBrowserNotifiedOfLogin(this, { shouldCloseTab: true }));
```

The `noPageTransition` test is done before `testIsBrowserNotifiedOfLogin`, yet the page only transitions after the login notification is sent. This passes locally because the verification link is opened and before the page has a chance to transition, the `noPageTransition` test is run and passes.

When run against a remote server where latency affects tests, the page transitions before the `noPageTransition` test is run.

Applying this patch causes the tests to fail locally too:

```diff
diff --git a/tests/functional/oauth_webchannel_keys.js b/tests/functional/oauth_webchannel_keys.js
index 730265d..ca4257d 100644
@@ -332,8 +332,8 @@ define([
 
         .then(testElementExists('#fxa-confirm-signin-header'))
         .then(openVerificationLinkDifferentBrowser(email, 1))
-        .then(noPageTransition('#fxa-confirm-signin-header'))
-        .then(testIsBrowserNotifiedOfLogin(this, { shouldCloseTab: true }));
+        .then(testIsBrowserNotifiedOfLogin(this, { shouldCloseTab: true }))
+        .then(noPageTransition('#fxa-confirm-signin-header'));
     }
   });
 });
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
We forgot to add a `HaltBehavior` to `afterSignInConfirmationPoll` and the
functional tests were not failing locally but were remotely due to
the way the tests were structured and the effects of latency.

fixes #3996

This is for train-66 too. :(

@vladikoff or @vbudhram - mind an r? If an r+, we should merge this back to train-66.

### CODE REVIEW

File: app/scripts/models/auth_brokers/oauth.js [hunk 1]
```diff
@@ -55,7 +55,8 @@ define(function (require, exports, module) {
     defaultBehaviors: _.extend({}, proto.defaultBehaviors, {
       // the relier will take over after sign in, no need to transition.
       afterForceAuth: new HaltBehavior(),
-      afterSignIn: new HaltBehavior()
+      afterSignIn: new HaltBehavior(),
+      afterSignInConfirmationPoll: new HaltBehavior()
```
Comment (vladikoff) [inline app/scripts/models/auth_brokers/oauth.js]: 👍
