### PR TITLE
fix(client): Firstrun flow should not halt the screens after login.

### LINKED ISSUE #2658: user is able to sign out if they sign in from firstrun flow
STR

1. Get yer hands on the development firstrun flow (https://github.com/shane-tomlinson/firstrun-example/)
1. Update the SERVER_ORIGIN to `http://127.0.0.1:3030` in https://github.com/shane-tomlinson/firstrun-example/blob/master/client/index.html#L14
1. Start the firstrun sample server.
1. Update the Firefox profile's user.js to point to the local stack
1. open 127.0.0.1:8111
1. Sign up or sign in. Complete verification if signing up
1. Re-open 127.0.0.1:8111 after signup/signin completes.
1. The "sign out" link should not be displayed

ref #2101

### LINKED ISSUE #2674: Ensure firstrun flows act as expected
Here are the latest mocks:

09june2015-growth-firstrun

Unlike the normal Sync flow, the "settings" page should be displayed after sign in, and the "account verified" page should be displayed in the original tab after account verification.

ref #2101

### PR DESCRIPTION
**Pull request by shane-tomlinson**
* Make fx-desktop authentication broker's halt behavior configurable
  with three new configuration options:
  * haltAfterResetPasswordConfirmationPoll
  * haltAfterSignIn
  * haltBeforeSignUpConfirmationPoll
* Add the FirstRunAuthenticationBroker which specifies its halt behavior.
  * Will also be used to communicate with the iframe.

Use these options when creating the first run's auth broker to prevent halting.

fixes #2674 
ref #2101

### CODE REVIEW

File: app/scripts/models/auth_brokers/first-run.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * embedded in the Firefox firstrun flow.
+ */
+
+define([
+  'models/auth_brokers/fx-desktop-v2'
+], function (FxDesktopV2AuthenticationBroker) {
+  'use strict';
+
+  var FirstRunAuthenticationBroker = FxDesktopV2AuthenticationBroker.extend({
+    haltAfterResetPasswordConfirmationPoll: false,
```
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/first-run.js]: Another approach I tried, instead of creating a complete new broker, is to pass these values as configuration to the FxDesktopV2AuthenticationBroker. I settled on creating the FirstRunAuthenticationBroker because I need it for #2705

**Comment by shane-tomlinson** [comment]
ref #2752

**Comment by shane-tomlinson** [comment]
@zaach - you reviewed the first version and found an issue, can I pester you for a final r?

File: app/scripts/models/auth_brokers/first-run.js (hunk 1 above)
Comment (zaach) [inline app/scripts/models/auth_brokers/first-run.js]: :+1:

**Comment by zaach** [comment]
This looks spot on!
