### PR TITLE
fix(client): always send a service param to /certificate/sign

### LINKED ISSUE #3933: empty current device shows up under devices
@philbooth I was working on some stuff locally (using fxa-local-dev) and noticed a device with no name showed up in the devices view. I did not use the account for sync. Should it be there?

### PR DESCRIPTION
**Pull request by philbooth**
This fixes #3933, setting a `service` query param on requests to `/certificate/sign` so that the auth server can accurately identify requests that come from Sync, in order to create placeholder device records for them.

It relies on https://github.com/mozilla/fxa-js-client/pull/205/commits/d68dd76dc0e666e0f84ba1d0013259cae9d1a95e, hence the dependency bump.

@vbudhram, r?

### CODE REVIEW

**Comment by philbooth** [comment]
Fixes #3933.

(commenting to link the two in waffle)

File: app/scripts/lib/fxa-client.js [hunk 1]
```diff
@@ -571,7 +571,8 @@ define(function (require, exports, module) {
                 return client.certificateSign(
                   sessionToken,
                   pubkey,
-                  duration);
+                  duration,
+                  { service: 'content-server' });
```
Comment (vbudhram) [inline app/scripts/lib/fxa-client.js]: Is this a static value? Should we pull it into constants file?

Comment (philbooth) [inline app/scripts/lib/fxa-client.js]: I'm happy to. There's also a constant defined at the top of this module, which point would you rather define it at?

**Comment by vbudhram** [comment]
> accurately identify requests that come from Sync

Is my understanding correct that you want to distinguish content-server and Sync requests? And only create device records for Sync? That is why using `content-server` service name?

Besides the minor nit, LGTM 👍

**Comment by philbooth** [comment]
> Is my understanding correct that you want to distinguish content-server and Sync requests? And only create device records for Sync? That is why using `content-server` service name?

Yep, exactly.

File: app/scripts/lib/fxa-client.js (hunk 1 above)
Comment (vbudhram) [inline app/scripts/lib/fxa-client.js]: Maybe [here](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/constants.js#L42)?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a3781fd501b6680f04b1e5a6a8f68f20d32f4d91
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com
