### PR TITLE
fix(clients): retry with a fresh token on OAuth requests

### LINKED ISSUE #4659: Error metrics tagged as `object_Object` in datadog
I noticed this oddity in datadog just now:

screen shot 2017-01-24 at 13 58 12

There are error events in there named things like "fxa.content.error.settings.clients.disconnect.auth.object_Object".  I assume that's taken the classic "[object Object"] stringification of an object and converted it into a metric name.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4659

### CODE REVIEW

File: app/scripts/models/account.js [hunk 1]
```diff
@@ -772,6 +772,15 @@ define(function (require, exports, module) {
      */
     fetchOAuthApps () {
       return this._oAuthClient.fetchOAuthApps(this.get('accessToken'))
+        .fail((err) => {
+          if (! AuthErrors.is(err, 'UNAUTHORIZED')) {
+            // the accessToken is very lived.
```
Comment (shane-tomlinson) [inline app/scripts/models/account.js]: `very lived` seems like it should have `short` or `long` in there.

File: app/scripts/models/account.js [hunk 2]
```diff
@@ -809,6 +818,15 @@ define(function (require, exports, module) {
       var accessToken = this.get('accessToken');
 
       return this._oAuthClient.destroyOAuthApp(accessToken, oAuthAppId)
+        .fail((err) => {
+          if (! AuthErrors.is(err, 'UNAUTHORIZED')) {
+            // the accessToken is short lived.
```
Comment (shane-tomlinson) [inline app/scripts/models/account.js]: Same here too.

File: app/scripts/models/account.js (hunk 1 above)
Comment (vladikoff) [inline app/scripts/models/account.js]: Hahahahah I meant to remove `very`but instead  the word `short` got removed.  ⏰
