### PR TITLE
fix(views): only log ephemeral messages on the screen navigated from

### LINKED ISSUE #2519: Multiple messages logged to console if Gravatar image cannot be found
### Steps to reproduce:
1. Create a new account at https://accounts.firefox.com/
2. Verify your account and go to https://accounts.firefox.com/settings/avatar/change
3. Set your account picture to "Gravatar"

### Actual results:
Two messages get logged to your console saying:
> "No Gravatar found"

account_picture

### Expected results:
1 error message is fine (if we must) but 2 seems excessive.
It almost seems like one is coming from the API and the other may be from the ephemeral message.

### PR DESCRIPTION
**Pull request by zaach**
Fixes #2519. We were logging ephemeral errors on the page that calls `navigate` as well as on the page that displays the error, when it should only be logged on the former.

### CODE REVIEW

File: app/scripts/views/base.js [hunk 1]
```diff
@@ -55,7 +55,9 @@ function (Cocktail, _, Backbone, Raven, $, p, AuthErrors,
 
     err = this._normalizeError(err);
 
-    this.logError(err);
+    if (shouldLog) {
+      this.logError(err);
```
Comment (shane-tomlinson) [inline app/scripts/views/base.js]: Something fishy is happening here, on L490, [logError checks if the error has been logged](https://github.com/mozilla/fxa-content-server/blob/issue-2519-ephemeral-logged-twice/app/scripts/views/base.js#L490), and if so, does not re-log. That was supposed to fix this issue.

Comment (shane-tomlinson) [inline app/scripts/views/base.js]: What's doubly fishy is [the comment mentions the exact situation this PR fixes](https://github.com/mozilla/fxa-content-server/blob/issue-2519-ephemeral-logged-twice/app/scripts/views/base.js#L485-L489).

**Comment by shane-tomlinson** [comment]
Ref 084fce06ae1bb1acde9fb71e1ccdfce90ad9ea11 and #1119.

**Comment by shane-tomlinson** [comment]
Further ref https://github.com/mozilla/fxa-content-server/commit/084fce06ae1bb1acde9fb71e1ccdfce90ad9ea11#diff-af500bac5338814fda67ec4de209ac46R417

**Comment by shane-tomlinson** [comment]
> Further ref 084fce0#diff-af500bac5338814fda67ec4de209ac46R417

@zaach - if the view sets `ephemeralMessages.error` itself, then the [`logError` in base.js->navigate](https://github.com/mozilla/fxa-content-server/commit/084fce06ae1bb1acde9fb71e1ccdfce90ad9ea11#diff-af500bac5338814fda67ec4de209ac46R417) will not be called. Possibility here?

**Comment by shane-tomlinson** [comment]
@zaach - the root of the problem is [views/settings/avatar_gravatar.js->_notFound](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/settings/avatar_gravatar.js#L57) passes a string instead of an `Error` object. This causes the string to be converted to an Error object twice, so `err.logged` is not set when `logError` is called the second time.

This diff fixes the problem:

```diff
diff --git a/app/scripts/views/settings/avatar_gravatar.js b/app/scripts/views/settings/avatar_gravatar.js
index 7129f4e..5e4d035 100644
--- a/app/scripts/views/settings/avatar_gravatar.js
+++ b/app/scripts/views/settings/avatar_gravatar.js
@@ -11,13 +11,15 @@ define([
   'views/mixins/settings-mixin',
   'views/mixins/avatar-mixin',
   'stache!templates/settings/avatar_gravatar',
+  'lib/auth-errors',
   'lib/constants',
   'lib/image-loader',
   'views/decorators/progress_indicator',
   'models/profile-image'
 ],
 function ($, _, md5, Cocktail, FormView, SettingsMixin, AvatarMixin,
-    Template, Constants, ImageLoader, showProgressIndicator, ProfileImage) {
+  Template, AuthErrors, Constants, ImageLoader, showProgressIndicator,
+  ProfileImage) {
   'use strict';
 
   function t (s) { return s; }
@@ -54,7 +56,7 @@ function ($, _, md5, Cocktail, FormView, SettingsMixin, AvatarMixin,
 
     _notFound: function () {
       this.navigate('settings/avatar/change', {
-        error: t('No Gravatar found')
+        error: AuthErrors.toError('No Gravatar found')
       });
     },
 ```

Even better than this would be to put that error into ProfileErrors and give it a client-side only error number.


screen shot 2015-08-19 at 12 31 50

**Comment by zaach** [comment]
Aha – maybe we should look into gradual typing (e.g. [Flow type](http://flowtype.org/)) as a way to prevent type errors like this.

/cc @eoger

**Comment by shane-tomlinson** [comment]
> Aha – maybe we should look into gradual typing (e.g. Flow type) as a way to prevent type errors like this.
>
> /cc @eoger

In lieu of adding a full build step to support Flow, we could also use duck typing.

FWIW, I'm not against using a build step, we just have to be aware of the effects on the development cycle. I'd personally like to integrate Babel and ES6 awesomeness.

**Comment by zaach** [comment]
> In lieu of adding a full build step to support Flow, we could also use duck typing.

> FWIW, I'm not against using a build step, we just have to be aware of the effects on the development cycle. I'd personally like to integrate Babel and ES6 awesomeness.

+1 to ES6! As for duck typing– Flow can also check your ducks statically. It's basically letting the machine handle all of the assertions you'd have to insert around your code to check ducks, which, as with linting, the machine is usually more thorough at doing. Type inference also means it can be less verbose. That's my sell at least :)
