### PR TITLE
fix(client): Fix sign in from the firstrun flow.

### LINKED ISSUE #3880: Sign-in confirmation fails during a slow confirmation in Firefox Desktop
## STR

1. Get a clean firefox profile  
1. Trigger Sign-in confirmation and wait in the browser 
1. Wait >30 seconds before verifying the email link

## Expected

image

## Actual 

image

## Log

```
foxfire
1467062258496	FirefoxAccounts	ERROR	Error updating FxA account info: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11
1467062258496	FirefoxAccounts	ERROR	Error updating FxA account info: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11
1467062258510	browserwindow.syncui	ERROR	updateUI failed: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11
1467062258516	browserwindow.syncui	ERROR	updateUI failed: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11 1467062402412	FirefoxAccountERROR	error POSTing /account/device: {"code":400,"errno":124,"error":"Bad Request","message":"Session already registered by another device","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402412	FirefoxAccounts	ERROR	error POSTing /account/device: {"code":400,"errno":124,"error":"Bad Request","message":"Session already registered by another device","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402917	FirefoxAccounts	ERROR	error GETing /account/keys: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402917	FirefoxAccounts	ERROR	error GETing /account/keys: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402919	Sync.BrowserIDManager	ERROR	Authentication error in _fetchTokenForUser: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062402920	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403397	Sync.BrowserIDManager	ERROR	Could not authenticate: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403717	Sync.BrowserIDManager	ERROR	Authentication error in _fetchTokenForUser: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403718	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403839	Sync.ErrorHandler	ERROR	Some engines did not sync correctly.
1467062403872	Sync.ErrorHandler	ERROR	Sync encountered a login error
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Two `fxaccounts:login` messages were being sent, both with the same
sessionToken and keyFetchToken. When the 2nd message was received by
the browser, it would attempt to re-use the keyFetchToken to fetch
keys. Since keyFetchTokens are single use, this failed.

This occurred because the signin confirmation flow called the
`beforeSignUpConfirmationPoll` broker method before the confirmation poll,
which sent one notice, and then `afterSignIn` when the poll completed, which
sent another notice.

The solution is to only send one `fxaccounts:login` message.

Instead of re-using `afterSignIn`, a new broker method is created,
`afterSignInConfirmationPoll`. The firstrun flow uses
`afterSignInConfirmationPoll` to notify the firstrun page of the signin, but
does NOT notify the browser.

fixes #3880 

@vbudhram, @vladikoff - r?

### CODE REVIEW

File: app/scripts/models/auth_brokers/base.js [hunk 1]
```diff
@@ -142,6 +143,15 @@ define(function (require, exports, module) {
     },
 
     /**
+     * Called after sign in confirmation poll. Can be usedc to notify the RP
```
Comment (vladikoff) [inline app/scripts/models/auth_brokers/base.js]: nit : `usedc`

**Comment by vbudhram** [comment]
Tested this a several times using the first run flow and worked as expected. Also, verified that regular signup/login flows work correctly.

Pending tests, r+

File: app/scripts/models/auth_brokers/base.js (hunk 1 above)
Comment (shane-tomlinson) [inline app/scripts/models/auth_brokers/base.js]: Nice catch.
