### PR TITLE
fix(client): Hide all visible passwords on form submit.

### LINKED ISSUE #3799: Make sure that shown passwords are saved as passwords
Make sure that shown passwords are saved as passwords and not form data.

When users show the password field, I'm told it does not save the password, and instead saves it as regular form data (e.g. phone number).

True @shane-tomlinson @vladikoff?

### PR DESCRIPTION
**Pull request by shane-tomlinson**
This builds on @TDA's work.

Before the form is submit, convert all visible passwords from
[type=text] to [type=password] so that they are not saved as
form data.

In the process, I noticed two problems that are fixed:

* The cursor was not being correctly replaced to its original position
   once a password field was converted.
* If `setPasswordVisibility` was called programatically to toggle the
   state of the password field, the corresponding "Show" checkbox was
   not kept in sync.

fixes #3799

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Failures are due to nsp.

**Comment by shane-tomlinson** [comment]
> Failures are due to nsp.

And code coverage has gone down on the password-mixin according to coveralls, yet locally all lines are covered.

**Comment by shane-tomlinson** [comment]
@vladikoff - mind an r?

File: app/tests/spec/views/base.js [hunk 1]
```diff
@@ -589,20 +589,54 @@ define(function (require, exports, module) {
       });
     });
 
-    describe('focus', function () {
-      it('focuses an element', function (done) {
-        requiresFocus(function () {
+    describe('focus', () => {
+      it('focuses an element, sets the cursor position', (done) => {
+        requiresFocus(() => {
           // wekbit fails unless focusing another element first.
```
Comment (vladikoff) [inline app/tests/spec/views/base.js]: nit: `wekbit` -> `webkit`

Comment (shane-tomlinson) [inline app/tests/spec/views/base.js]: I'm learning to speak Dutch, can you tell?

Comment (shane-tomlinson) [inline app/tests/spec/views/base.js]: > I'm learning to speak Dutch

I'm not really, but it's the first thing that popped into my mind.

File: app/scripts/views/form.js [hunk 2]
```diff
@@ -172,6 +172,8 @@ define(function (require, exports, module) {
         event.stopImmediatePropagation();
       }
 
+      this.trigger('submitStart');
```
Comment (vladikoff) [inline app/scripts/views/form.js]: 👍

**Comment by vladikoff** [comment]
r+! The only thing we should chat about is disabling the "Show" button if needed.
