### PR TITLE
fix(metrics): prevent utm parameters from being dropped after verific…

### LINKED ISSUE #2937: utm parameters being dropped after verification?
From Chris More in IRC:

-------------------------------------

[21:31:03]  <cmore>	stomlinson: one thing i noticed about the UTM parameters on the iframe is that they get dropped when a user verifies their email address and the iframe URL changes. All verified emails have no source/medium. Not sure what we can do about that other than preserving the UTM tags being passed when redirecting after verified.

### PR DESCRIPTION
**Pull request by vladikoff**
…ation

Fixes #2937

### CODE REVIEW

**Comment by vladikoff** [comment]
@zaach r?

File: app/scripts/models/reliers/relier.js [hunk 1]
```diff
@@ -21,7 +21,15 @@ define([
...
   'use strict';
 
-  var RELIER_FIELDS_IN_RESUME_TOKEN = ['campaign', 'entrypoint'];
+  var RELIER_FIELDS_IN_RESUME_TOKEN = [
+    'utmTerm',
+    'utmSource',
+    'utmMedium',
+    'utmContent',
+    'utmCampaign',
+    'campaign',
```
Comment (vladikoff) [inline app/scripts/models/reliers/relier.js]: this is going to be going away soon via https://github.com/mozilla/fxa-content-server/issues/2920

File: app/tests/spec/models/reliers/relier.js [hunk 2]
```diff
@@ -194,16 +194,28 @@ define([
...
           campaign: CAMPAIGN,
           entrypoint: ENTRYPOINT,
+          utmCampaign: CAMPAIGN,
+          utmSource: ITEM,
+          utmMedium: ITEM,
+          utmTerm: ITEM,
+          utmContent: ITEM,
           notPassed: 'this should not be picked'
         });
+        console.log(relier.pickResumeTokenInfo());
```
Comment (zaach) [inline app/tests/spec/models/reliers/relier.js]: :eyes:

Comment (vladikoff) [inline app/tests/spec/models/reliers/relier.js]: /flip

**Comment by zaach** [comment]
:+1:

File: app/scripts/models/reliers/relier.js (hunk 1 above)
Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: Huh, adding UTM parameters here doesn't seem right and breaks encapsulation. I thought an OAuth relier should be created in app-start.js when verifying for an OAuth service, and if so, this would not be needed.

Comment (shane-tomlinson) [inline app/scripts/models/reliers/relier.js]: Ignore me.
