### PR TITLE
fix(metrics): postpone OAuth navigation until metrics are flushed

### LINKED ISSUE #2493: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience
Was trying to quickly test https://email.dev.lcip.org/signup in Chrome, and noticed this gem in the developer tools console:

> #### _Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/._

For some reason Chrome isn't letting me see the source code for that line, but it's minified anyways so it may not be uber helpful.

ref #2577

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #2493.

This change performs an async metrics flush before redirecting during the OAuth flow. The `unload` (and, when it's merged, `blur`) flushes are unaffected, still being flushed synchronously unless `sendBeacon` is available.

### CODE REVIEW

File: app/scripts/lib/metrics.js [hunk 1]
```diff
@@ -141,7 +141,7 @@ define([
     /**
      * Send the collected data to the backend.
      */
-    flush: function () {
+    flush: function (flushSynchronously) {
```
Comment (shane-tomlinson) [inline app/scripts/lib/metrics.js]: The change from `flushSynchronously` to `async` in _send is a bit confusing. Can we keep the same semantics in both places?

File: app/scripts/lib/metrics.js [hunk 2]
```diff
@@ -235,7 +235,7 @@ define([
       return filteredData;
     },
 
-    _send: function (data, url) {
+    _send: function (data, url, async) {
       var self = this;
       var payload = JSON.stringify(data);
```
Comment (shane-tomlinson) [inline app/scripts/lib/metrics.js]: It looks like even if `async===false`, if the environment has `navigator.sendBeacon`, that will be used. Expected? If so, can you add a note about why that's OK?

Comment (philbooth) [inline app/scripts/lib/metrics.js]: Where do you want the note? In a comment or here in the PR?

Comment (shane-tomlinson) [inline app/scripts/lib/metrics.js]: In a comment just before the sendBeacon code.

File: app/scripts/lib/metrics.js [hunk 3]
```diff
@@ -152,7 +152,7 @@ define([
       var url = this._collector + '/metrics';
       var self = this;
 
-      return this._send(filteredData, url)
+      return this._send(filteredData, url, ! flushSynchronously)
```
Comment (shane-tomlinson) [inline app/scripts/lib/metrics.js]: @philbooth - While we are working in this module, would you mind if we did a tad bit of cleanup?

* Passing in the `url` to `_send` seems a bit silly, send is an instance function and should be able to create its own URL. Maybe the original intention was to send metrics to different endpoints for different situations. I don't remember.
* If a flush has already occurred and filteredData.events, filteredData.timers, and filteredData.ab are all empty, then we have no new information; pinging the metrics endpoint doesn't really make sense. I wonder if this could ever occur on the first send.

File: app/tests/spec/views/ready.js [hunk 4]
```diff
@@ -40,12 +42,18 @@ function (chai, sinon, View, Session, FxaClient, Able, FxDesktopRelier,
       fxaClient = new FxaClient();
 
       able = new Able();
+      metrics = {
+        flush: p,
```
Comment (shane-tomlinson) [inline app/tests/spec/views/ready.js]: I think you can add the spy directly to p like so:

```js
flush: sinon.spy(p),
```

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b046776bff425fb38d0ff851f7a1f8adb728034a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

File: app/scripts/lib/metrics.js (hunk 3 above)
Comment (philbooth) [inline app/scripts/lib/metrics.js]: > * If a flush has already occurred and filteredData.events, filteredData.timers, and filteredData.ab are all empty, then we have no new information; pinging the metrics endpoint doesn't really make sense. I wonder if this could ever occur on the first send.

@shane-tomlinson, I am seeing this happen quite frequently locally; I think, as a result of the new `blur` behaviour.

I have a fix locally, checking whether `events` and `timers` are populated, but I am confused by your mention of `filteredData.ab`. I don't see it get emptied like the other two. Should I instead be checking to see whether it has changed since the last invocation, or am I missing something?

Comment (shane-tomlinson) [inline app/scripts/lib/metrics.js]: > am I missing something?

I doubt you are missing something. This sounds like a bigger task than I expected, do you think it is worthwhile to open a new PR and merge this one as is?

Comment (philbooth) [inline app/scripts/lib/metrics.js]: Not yet. :)

File: app/scripts/lib/metrics.js [hunk 5]
```diff
@@ -240,22 +237,29 @@ define([
...
-    _send: function (data, url) {
+    _send: function (data, isPageUnloading) {
       var self = this;
+      var url = this._collector + '/metrics';
       var payload = JSON.stringify(data);
 
       if (this._env.hasSendBeacon()) {
+        // Always use sendBeacon if it is available because:
+        //   1. it works asynchronously, even on unload.
+        //   2. user agents SHOULD make "multiple attempts to transmit the
```
Comment (shane-tomlinson) [inline app/scripts/lib/metrics.js]: ooh, I had no idea.

**Comment by philbooth** [comment]
@shane-tomlinson, I've pushed fixes to your comments and also the `_isFlushRequired` implementation we chatted about earlier. You may want to view the diff with `?w=1` as the indentation of some tests had to change.

**Comment by shane-tomlinson** [comment]
This gets an r+ from me @philbooth, could you review my patch on your patch?

**Comment by philbooth** [comment]
Oh, that's heaps better @shane-tomlinson! :smile: :+1:
