### PR TITLE
fix(build): extend r.js timeout for building production

### LINKED ISSUE #3166: `grunt build` fails on latest.dev with error from requirejs:dist
I've removed /data/fxa-content-server and let it try to rebuild several times, but it fails with this error on requirejs:dist

```
Running "requirejs:dist" (requirejs) task
>> Error: Error: Module loading did not complete for: main, lib/app-start, backbone, lib/router, views/base, lib/ephemeral-messages, lib/nu\
ll-metrics, lib/metrics, views/cannot_create_account, views/choose_what_to_sync, views/form, views/tooltip, views/decorators/progress_indic\
ator, views/progress_indicator, views/mixins/back-mixin, views/clear_storage, views/complete_account_unlock, models/verification/account-un\
lock, models/verification/base, views/complete_reset_password, views/mixins/resume-token-mixin, models/resume-token, views/mixins/service-m\
ixin, models/verification/reset-password, views/complete_sign_up, views/mixins/experiment-mixin, lib/experiment, lib/experiments/coppa-view\
, lib/experiments/base, lib/experiments/mailcheck, lib/experiments/open-gmail, lib/experiments/sync-checkbox, views/mixins/resend-mixin, mo\
dels/email-resend, models/verification/sign-up, views/confirm, views/confirm_account_unlock, views/confirm_reset_password, views/cookies_di\
sabled, views/force_auth, views/sign_in, views/mixins/avatar-mixin, models/profile-image, views/mixins/account-locked-mixin, views/legal, v\
iews/openid/login, views/openid/start, views/permissions, views/pp, views/legal_copy, views/ready, views/marketing_snippet, views/marketing\
_snippet_ios, views/reset_password, views/settings, views/settings/avatar, views/mixins/settings-panel-mixin, views/settings/avatar_change,\
 views/mixins/modal-settings-panel-mixin, models/cropper-image, views/settings/avatar_crop, views/settings/avatar_camera, views/settings/av\
atar_gravatar, views/settings/gravatar_permissions, views/settings/communication_preferences, views/settings/change_password, views/setting\
s/delete_account, views/settings/display_name, views/sub_panels, views/sign_up, lib/mailcheck, views/coppa/coppa-date-picker, views/coppa/c\
oppa-age-input, views/tos, views/unexpected_error, lib/storage-metrics, lib/assertion, vendor/jwcrypto, vendor/jwcrypto/index, vendor/jwcry\
pto/lib/jwcrypto, vendor/jwcrypto/lib/cert, lib/channels/iframe, lib/channels/duplex, lib/channels/base, lib/channels/receivers/postmessage\
, lib/channels/null, lib/channels/web, lib/channels/receivers/web-channel, lib/origin-check, lib/height-observer, models/reliers/relier, mo\
dels/reliers/base, models/mixins/resume-token, models/reliers/oauth, models/reliers/sync, models/auth_brokers/base, models/auth_brokers/fx-\
desktop-v1, lib/channels/fx-desktop-v1, models/auth_brokers/fx-sync, models/auth_brokers/fx-desktop-v2, models/auth_brokers/fx-fennec-v1, m\
odels/auth_brokers/fx-ios-v1, models/auth_brokers/first-run, models/auth_brokers/web-channel, models/auth_brokers/oauth, models/auth_broker\
s/redirect, models/auth_brokers/iframe, models/unique-user-id, models/user, models/account, models/oauth-token, models/marketing-email-pref\
s, models/form-prefill, models/notifications, views/close_button                                                                            
>> The following modules share the same URL. This could be a misconfiguration if that URL only has one anonymous module in it:              
>> /data/fxa-content-server/app/bower_components/backbone/backbone.js: backbone, backbone                                                   
>> /data/fxa-content-server/app/scripts/vendor/jwcrypto.js: vendor/jwcrypto, vendor/jwcrypto                                                
>> /data/fxa-content-server/app/scripts/vendor/jwcrypto/index.js: vendor/jwcrypto/index, vendor/jwcrypto/index                              
>> /data/fxa-content-server/app/scripts/vendor/jwcrypto/lib/jwcrypto.js: vendor/jwcrypto/lib/jwcrypto, vendor/jwcrypto/lib/jwcrypto         
>> /data/fxa-content-server/app/scripts/vendor/jwcrypto/lib/cert.js: vendor/jwcrypto/lib/cert, vendor/jwcrypto/lib/cert                     
>>     at Function.build.checkForErrors (/data/fxa-content-server/node_modules/grunt-requirejs/node_modules/requirejs/bin/r.js:30026:19)
Warning: Task "requirejs:dist" failed.^G Use --force to continue.

Aborted due to warnings.
```

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3166

### CODE REVIEW

File: grunttasks/requirejs.js [hunk 1]
```diff
@@ -12,9 +12,6 @@ module.exports = function (grunt) {
         // be added manually to the bundle.
         deps: ['nocache'],
         findNestedDependencies: true,
-        // TODO: (Issue #560) Figure out how to make sourcemaps work with grunt-usemin
-        // https://github.com/yeoman/grunt-usemin/issues/30
-        //generateSourceMaps: true,
```
Comment (rfk) [inline grunttasks/requirejs.js]: \o/ for removing ancient TODOs :-)

**Comment by rfk** [comment]
:+1:, assuming travis says ok
