### PR TITLE
fix(sms): Only show the SMS form to desktop users.

### LINKED ISSUE #4855: Only show the "Send SMS" feature in a desktop browser
Right now the "Send SMS" form is displayed to users who are already on a mobile device. That's kinda silly.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #4855 

@philbooth, @vbudhram, @vladikoff - r?

### CODE REVIEW

File: tests/functional/lib/helpers.js [hunk 1]
```diff
@@ -545,33 +544,32 @@ define([
    * Open a verification link in a new tab of the same browser.
    * @param {string} email user's email
    * @param {number} index verification email index
+   * @param {object} [options] options
+   *   @param {object} [options.query] extra query parameters to add to the verification link
    * @returns {promise} resolves when complete
    */
-  const openVerificationLinkInNewTab = thenify(function (email, index, windowName) {
```
Comment (shane-tomlinson) [inline tests/functional/lib/helpers.js]: `windowName` wasn't passed in anywhere, so I re-purposed the parameter.

File: app/tests/spec/lib/user-agent.js [hunk 2]
```diff
@@ -100,6 +100,50 @@ define(function (require, exports, module) {
       });
     });
 
+    describe('isDesktop', () => {
+      it('returns `true` if on a desktop device', () => {
```
Comment (vbudhram) [inline app/tests/spec/lib/user-agent.js]: For unknown user agents, this would also be displayed? Should it we worded as `if not on mobile`?

File: tests/functional/fx_firstrun_v2_sign_up.js [hunk 3]
```diff
@@ -14,6 +14,25 @@ define([
...
+  const SELECTOR_CHOOSE_WHAT_TO_SYNC_PASSWORD_ENTRY = 'div.two-col-block:nth-child(1) > div:nth-child(3) > label:nth-child(1)';
+  const SELECTOR_CHOOSE_WHAT_TO_SYNC_SUBMIT = 'button[type=submit]';
+  const SELECTOR_CONFIRM_HEADER = '#fxa-confirm-header';
+  const SELECTOR_CONNECT_ANOTHER_DEVICE_HEADER = '#fxa-connect-another-device-header';
+  const SELECTOR_SEND_SMS_HEADER = '#fxa-send-sms-header';
+  const SELECTOR_SIGN_UP_HEADER = '#fxa-signup-header';
+  const SELECTOR_SIGN_UP_COMPLETE_HEADER = '#fxa-sign-up-complete-header';
+
+  /*eslint-disable max-len*/
+  var UA_STRINGS = {
```
Comment (vbudhram) [inline tests/functional/fx_firstrun_v2_sign_up.js]: nit `const`

**Comment by shane-tomlinson** [comment]
The failing functional test is because /sms/status returns `ok: false` and the `#fxa-send-sms-header` element is not found.

That brings up the question, should the circle box have the ability to send SMS?

If yes, @philbooth's [auth-server PR](https://github.com/mozilla/fxa-auth-server/pull/1766/files) will help with this if we set the functional tests up to specify `country=US`

If no, maybe if `country=XX` is specified, we ignore the result of `/sms/status` and if the country is one of US,CA,RO,GB, allow the form to be displayed but sending uses some mock?

Ref https://github.com/mozilla/fxa-content-server/issues/4807 for mocking out the SMS provider for functional tests.
Ref https://github.com/mozilla/fxa-content-server/issues/4862 to run SMS functional tests on circle.

**Comment by philbooth** [comment]
> The failing functional test is because /sms/status returns `ok: false` and the `#fxa-send-sms-header` element is not found...

@shane-tomlinson, the other option would be to set `sms.isStatusGeoEnabled` / `SMS_STATUS_GEO_ENABLED` to `false` in the auth server config for CI. Then we'd just skip the geo-lookup entirely and gate the `/status` response purely on the balance with Nexmo.

File: app/scripts/lib/user-agent.js [hunk 4]
```diff
@@ -31,6 +31,15 @@ define(function (require, exports, module) {
       },
 
       /**
+       * Check if on a desktop device
+       *
+       * @returns {Boolean}
+       */
+      isDesktop () {
+        return ! this.isAndroid() && ! this.isIos();
```
Comment (philbooth) [inline app/scripts/lib/user-agent.js]: Although it's not significant for the correctness of this PR, going forward I think this is a mildly surprising definition for an `isDesktop` predicate. It seems like what we're really expressing is something more like `isPlatformThatDoesntHaveAnAppStore` (thank you, unwieldy names are my forté).

I wouldn't have bothered mentioning it, but the fact that this lives in a generic user-agent module makes me more cautious. Might this be a name we regret using in the future? Is there a better name we could come up with? (and not my ridiuclous suggestion from the previous paragraph)

Or maybe we should just suck it up and force callers to inline this function themselves? Explicitly writing:

```
! this.isAndroid() && ! this.isIos()
``` 

...doesn't seem lilke a huge imposition and is more honest than `isDesktop` in this case.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson, the other option would be to set sms.isStatusGeoEnabled / SMS_STATUS_GEO_ENABLED to false in the auth server config for CI. Then we'd just skip the geo-lookup entirely and gate the /sms/status response purely on the balance with Nexmo.

Thanks for this tip @philbooth - I'll set isStatusGeoEnabled to false and set up fxa-ci with Nexmo creds until https://github.com/mozilla/fxa-auth-server/pull/1772 lands. I'm going to add the Nexmo creds by hand, not checked into config so that they aren't made public. :( It's ugly, but it'll get this test unblocked.

File: app/scripts/lib/user-agent.js (hunk 4 above)
Comment (shane-tomlinson) [inline app/scripts/lib/user-agent.js]: I kinda sorta hoped someone would call me out on this. I want to keep a helper function, I just don't know what to call it.

Comment (philbooth) [inline app/scripts/lib/user-agent.js]: We could flip my silly suggestion round so it's a bit less silly:

```js
isPlatformWithAppStore () {
   return this.isAndroid() || this.isIos();
}
```

Warmer?

Comment (shane-tomlinson) [inline app/scripts/lib/user-agent.js]: > We could flip my silly suggestion round so it's a bit less silly:

Excellent name.
